'use client';

import * as React from 'react';
import { X } from 'lucide-react';
import * as Popover from '@radix-ui/react-popover';
import { cn } from '@/lib/utils';


// Comprehensive list of Israeli cities and towns with Hebrew names
const ISRAEL_CITIES = [
  // א
  { en: 'Abu Bilal', he: 'אבו בלאל' },
  { en: 'Abu Juweiid (Tribe)', he: 'אבו גווייעד (שבט)' },
  { en: 'Abu Ghosh', he: 'אבו גוש' },
  { en: 'Abu Gaada', he: 'אבו געדה' },
  { en: 'Abu Dis', he: 'אבו דיס' },
  { en: 'Abu Hamra', he: 'אבו חמרה' },
  { en: 'Abu Tuweileh', he: 'אבו טוילה' },
  { en: 'Abu Sinan', he: 'אבו סנאן' },
  { en: 'Abu Sureihan (Tribe)', he: 'אבו סריחאן (שבט)' },
  { en: 'Abu Abdun (Tribe)', he: 'אבו עבדון (שבט)' },
  { en: 'Abu Ammar (Tribe)', he: 'אבו עמאר (שבט)' },
  { en: 'Abu Amra (Tribe)', he: 'אבו עמרה (שבט)' },
  { en: 'Abu Qureinat (Tribe)', he: 'אבו קורינאת (שבט)' },
  { en: 'Abu Qreinat (Settlement)', he: 'אבו קרינאת (יישוב)' },
  { en: 'Abu Qash', he: 'אבו קש' },
  { en: 'Abu Rubeia (Tribe)', he: 'אבו רובייעה (שבט)' },
  { en: 'Abu Ruqeiq (Tribe)', he: 'אבו רוקייק (שבט)' },
  { en: 'Abu Shchidam', he: 'אבו שחידם' },
  { en: 'Abu Talul', he: 'אבו תלול' },
  { en: 'Ibtin', he: 'אבטין' },
  { en: 'Avtalyon', he: 'אבטליון' },
  { en: 'Aviel', he: 'אביאל' },
  { en: 'Avivim', he: 'אביבים' },
  { en: 'Avigdor', he: 'אביגדור' },
  { en: 'Avichail', he: 'אביחיל' },
  { en: 'Avital', he: 'אביטל' },
  { en: 'Aviezer', he: 'אביעזר' },
  { en: 'Abirim', he: 'אבירים' },
  { en: 'Even Yehuda', he: 'אבן יהודה' },
  { en: 'Even Menachem', he: 'אבן מנחם' },
  { en: 'Even Sapir', he: 'אבן ספיר' },
  { en: 'Even Shmuel', he: 'אבן שמואל' },
  { en: 'Avnei Eitan', he: 'אבני איתן' },
  { en: 'Avnei Hefetz', he: 'אבני חפץ' },
  { en: 'Avnat', he: 'אבנת' },
  { en: 'Avshalom', he: 'אבשלום' },
  { en: 'Ibtan', he: 'אבתאן' },
  { en: 'Ajnasnya', he: 'אג\'נסניא' },
  { en: 'Adora', he: 'אדורה' },
  { en: 'Adirim', he: 'אדירים' },
  { en: 'Adamit', he: 'אדמית' },
  { en: 'Adana', he: 'אדנה' },
  { en: 'Aderet', he: 'אדרת' },
  { en: 'Ohalo', he: 'אהלו' },
  { en: 'Udim', he: 'אודים' },
  { en: 'Udla', he: 'אודלה' },
  { en: 'Odem', he: 'אודם' },
  { en: 'Ohad', he: 'אוהד' },
  { en: 'Umm al-Fahm', he: 'אום אל-פחם' },
  { en: 'Umm al-Qutuf', he: 'אום אל-קוטוף' },
  { en: 'Umm al-Tut', he: 'אום אל תות' },
  { en: 'Umm Batin', he: 'אום בטין' },
  { en: 'Oman', he: 'אומן' },
  { en: 'Ometz', he: 'אומץ' },
  { en: 'Ofakim', he: 'אופקים' },
  { en: 'Otzarin', he: 'אוצרין' },
  { en: 'Or HaGanuz', he: 'אור הגנוז' },
  { en: 'Or HaNer', he: 'אור הנר' },
  { en: 'Or Yehuda', he: 'אור יהודה' },
  { en: 'Or Akiva', he: 'אור עקיבא' },
  { en: 'Ora', he: 'אורה' },
  { en: 'Orot', he: 'אורות' },
  { en: 'Ortal', he: 'אורטל' },
  { en: 'Urim', he: 'אורים' },
  { en: 'Oranim', he: 'אורנים' },
  { en: 'Oranit', he: 'אורנית' },
  { en: 'Usha', he: 'אושה' },
  { en: 'Azor', he: 'אזור' },
  { en: 'Achva', he: 'אחווה' },
  { en: 'Achuzam', he: 'אחוזם' },
  { en: 'Achuzat Barak', he: 'אחוזת ברק' },
  { en: 'Achihud', he: 'אחיהוד' },
  { en: 'Achituv', he: 'אחיטוב' },
  { en: 'Achisamakh', he: 'אחיסמך' },
  { en: 'Achiezer', he: 'אחיעזר' },
  { en: 'Atrash (Tribe)', he: 'אטרש (שבט)' },
  { en: 'Ivim', he: 'איבים' },
  { en: 'Eyal', he: 'אייל' },
  { en: 'Ayelet HaShachar', he: 'איילת השחר' },
  { en: 'Eilon', he: 'אילון' },
  { en: 'Eilot', he: 'אילות' },
  { en: 'Ilaniya', he: 'אילניה' },
  { en: 'Eilat', he: 'אילת' },
  { en: 'Itamar', he: 'איתמר' },
  { en: 'Eitan', he: 'איתן' },
  { en: 'Eitanim', he: 'איתנים' },
  { en: 'Iksal', he: 'אכסאל' },
  { en: 'Iktaba', he: 'אכתאבא' },
  { en: 'Al-Azi', he: 'אל-עזי' },
  { en: 'Al-Aryan', he: 'אל-עריאן' },
  { en: 'El Rom', he: 'אל-רום' },
  { en: 'El Bireh', he: 'אל בירה' },
  { en: 'Al Sayyid', he: 'אל סייד' },
  { en: 'Al Arish', he: 'אל עריש' },
  { en: 'Alumah', he: 'אלומה' },
  { en: 'Alumot', he: 'אלומות' },
  { en: 'Alon HaGalil', he: 'אלון הגליל' },
  { en: 'Alon Moreh', he: 'אלון מורה' },
  { en: 'Alon Shvut', he: 'אלון שבות' },
  { en: 'Alonei Aba', he: 'אלוני אבא' },
  { en: 'Alonei HaBashan', he: 'אלוני הבשן' },
  { en: 'Alonei Yitzchak', he: 'אלוני יצחק' },
  { en: 'Alonim', he: 'אלונים' },
  { en: 'Eli Ad', he: 'אלי-עד' },
  { en: 'Eli Sinai', he: 'אלי סיני' },
  { en: 'Elyakhin', he: 'אליכין' },
  { en: 'Elifaz', he: 'אליפז' },
  { en: 'Elifelet', he: 'אליפלט' },
  { en: 'Elyakim', he: 'אליקים' },
  { en: 'Elishiv', he: 'אלישיב' },
  { en: 'Elishama', he: 'אלישמע' },
  { en: 'Almagor', he: 'אלמגור' },
  { en: 'Almog', he: 'אלמוג' },
  { en: 'Elad', he: 'אלעד' },
  { en: 'Elazar', he: 'אלעזר' },
  { en: 'Alfei Menashe', he: 'אלפי מנשה' },
  { en: 'Elkosh', he: 'אלקוש' },
  { en: 'Elkana', he: 'אלקנה' },
  { en: 'Um a-Tala', he: 'אם א טלע' },
  { en: 'Um al-Ghanam', he: 'אם אל גנם' },
  { en: 'Um Hashiba', he: 'אם חשיבה' },
  { en: 'Um Salamuna', he: 'אם סלמונה' },
  { en: 'Um Alas', he: 'אם עלאס' },
  { en: 'Um Asla', he: 'אם עסלה' },
  { en: 'Um Tsafa', he: 'אם צפא' },
  { en: 'Um Qutzari', he: 'אם קוצרי' },
  { en: 'Imatin', he: 'אמאתין' },
  { en: 'Emunim', he: 'אמונים' },
  { en: 'Amirim', he: 'אמירים' },
  { en: 'Amnon', he: 'אמנון' },
  { en: 'Amatzya', he: 'אמציה' },
  { en: 'Amarish', he: 'אמריש' },
  { en: 'Aniam', he: 'אניעם' },
  { en: 'Asad (Tribe)', he: 'אסד (שבט)' },
  { en: 'Iskaka', he: 'אסכאכא' },
  { en: 'Aspar', he: 'אספר' },
  { en: 'Ibillin', he: 'אעבלין' },
  { en: 'Aatsam (Tribe)', he: 'אעצם (שבט)' },
  { en: 'Afinish (Tribe)', he: 'אפיניש (שבט)' },
  { en: 'Afik', he: 'אפיק' },
  { en: 'Afikim', he: 'אפיקים' },
  { en: 'Efal Beit Av', he: 'אפעל בית אב' },
  { en: 'Efal Merkaz S', he: 'אפעל מרכז ס' },
  { en: 'Afek', he: 'אפק' },
  { en: 'Efrata', he: 'אפרתה' },
  { en: 'Arbel', he: 'ארבל' },
  { en: 'Argaman', he: 'ארגמן' },
  { en: 'Erez', he: 'ארז' },
  { en: 'Artas', he: 'ארטאס' },
  { en: 'Ariel', he: 'אריאל' },
  { en: 'Arsuf', he: 'ארסוף' },
  { en: 'Artah', he: 'ארתאח' },
  { en: 'Eshbol', he: 'אשבול' },
  { en: 'Eshbal', he: 'אשבל' },
  { en: 'Ashdod', he: 'אשדוד' },
  { en: 'Ashdot Yaakov (Ichud)', he: 'אשדות יעקב (איחוד)' },
  { en: 'Ashdot Yaakov (Meuchad)', he: 'אשדות יעקב (מאוחד)' },
  { en: 'Eshchar', he: 'אשחר' },
  { en: 'Eshkolot', he: 'אשכולות' },
  { en: 'Eshel HaNasi', he: 'אשל הנשיא' },
  { en: 'Ashalim', he: 'אשלים' },
  { en: 'Ashkelon', he: 'אשקלון' },
  { en: 'Asherat', he: 'אשרת' },
  { en: 'Eshtaol', he: 'אשתאול' },
  { en: 'Etgar', he: 'אתגר' },
  { en: 'Atar Metzada', he: 'אתר מצדה' },

  // ב
  { en: 'Baga', he: 'באגה' },
  { en: 'Baqa', he: 'באקה' },
  { en: 'Baqa al-Gharbiyye', he: 'באקה אל-גרביה' },
  { en: 'Baqa al-Sharqiyya', he: 'באקה אל שרק' },
  { en: 'Beer Ora', he: 'באר אורה' },
  { en: 'Beer Ganim', he: 'באר גנים' },
  { en: 'Beer Tuvia', he: 'באר טוביה' },
  { en: 'Beer Yaakov', he: 'באר יעקב' },
  { en: 'Beer Milka', he: 'באר מילכה' },
  { en: 'Beer Sheva', he: 'באר שבע' },
  { en: 'Beerot Yitzchak', he: 'בארות יצחק' },
  { en: 'Beerotayim', he: 'בארותיים' },
  { en: 'Beeri', he: 'בארי' },
  { en: 'Baghdad', he: 'בגדד' },
  { en: 'Badu', he: 'בדו' },
  { en: 'Bedolach', he: 'בדולח' },
  { en: 'Badia', he: 'בדיא' },
  { en: 'Badras', he: 'בדרס' },
  { en: 'Buga', he: 'בוגה' },
  { en: 'Bustan HaGalil', he: 'בוסתן הגליל' },
  { en: 'Bueine-Nujeidat', he: 'בועיינה-נוגידאת' },
  { en: 'Buqata', he: 'בוקעאתא' },
  { en: 'Burgata', he: 'בורגתה' },
  { en: 'Burham', he: 'בורהאם' },
  { en: 'Burin', he: 'בורין' },
  { en: 'Burqa', he: 'בורקה' },
  { en: 'Bazariya', he: 'בזאריה' },
  { en: 'Bachan', he: 'בחן' },
  { en: 'Bitcha', he: 'בטחה' },
  { en: 'Biada', he: 'ביאדה' },
  { en: 'Bida', he: 'בידא' },
  { en: 'Biukhi', he: 'ביוכי' },
  { en: 'Bitzaron', he: 'ביצרון' },
  { en: 'Bir a-Natsab', he: 'ביר א נצב' },
  { en: 'Bir a-Sakka', he: 'ביר א סכה' },
  { en: 'Bir Abu Suwi', he: 'ביר אבו סוי' },
  { en: 'Bir Abu Tsui', he: 'ביר אבו צוי' },
  { en: 'Bir al-Maksur', he: 'ביר אל-מכסור' },
  { en: 'Bir al-Hasi', he: 'ביר אל חסי' },
  { en: 'Bir al-Malha', he: 'ביר אל מלחה' },
  { en: 'Bir al-Main', he: 'ביר אל מעין' },
  { en: 'Bir al-Abd', he: 'ביר אל עבד' },
  { en: 'Bir Almayin', he: 'ביר אלמיין' },
  { en: 'Bir Jala', he: 'ביר ג\'אלא' },
  { en: 'Bir Hadag', he: 'ביר הדאג' },
  { en: 'Bir Halil', he: 'ביר הליל' },
  { en: 'Bir Zeit', he: 'ביר זית' },
  { en: 'Bir Hasana', he: 'ביר חסנה' },
  { en: 'Bir Lahfan', he: 'ביר לחפאן' },
  { en: 'Bir Malaki', he: 'ביר מלאקי' },
  { en: 'Bir Maar', he: 'ביר מער' },
  { en: 'Bir Nabala', he: 'ביר נבאלא' },
  { en: 'Bir Natsab', he: 'ביר נצב' },
  { en: 'Bir Sidri', he: 'ביר סדרי' },
  { en: 'Bir Sheikh Hami', he: 'ביר שיח חמי' },
  { en: 'Bir Tel', he: 'ביר תל' },
  { en: 'Bira Hebron', he: 'בירה חברון' },
  { en: 'Biriya', he: 'ביריה' },
  { en: 'Beit Ajza', he: 'בית אג\'זא' },
  { en: 'Beit Ula', he: 'בית אולא' },
  { en: 'Beit Oren', he: 'בית אורן' },
  { en: 'Beit Iba', he: 'בית איבא' },
  { en: 'Beit Iksa', he: 'בית אכסא' },
  { en: 'Beit El', he: 'בית אל' },
  { en: 'Beit El B', he: 'בית אל ב' },
  { en: 'Beit Alalu', he: 'בית אללו' },
  { en: 'Beit Elazari', he: 'בית אלעזרי' },
  { en: 'Beit Alfa', he: 'בית אלפא' },
  { en: 'Beit Amin', he: 'בית אמין' },
  { en: 'Beit Ummar', he: 'בית אמר' },
  { en: 'Beit Amrin', he: 'בית אמרין' },
  { en: 'Beit Anan', he: 'בית אענאן' },
  { en: 'Beit Arush Fu', he: 'בית ארוש פו' },
  { en: 'Beit Arush Tach', he: 'בית ארוש תח' },
  { en: 'Beit Arye', he: 'בית אריה' },
  { en: 'Beit Berl', he: 'בית ברל' },
  { en: 'Beit Jala', he: 'בית ג\'אלא' },
  { en: 'Beit Guvrin', he: 'בית גוברין' },
  { en: 'Beit Gamal', he: 'בית גמאל' },
  { en: 'Beit Gamliel', he: 'בית גמליאל' },
  { en: 'Beit Gan', he: 'בית גן' },
  { en: 'Beit Dagan', he: 'בית דגן' },
  { en: 'Beit Daku', he: 'בית דקו' },
  { en: 'Beit HaGadi', he: 'בית הגדי' },
  { en: 'Beit HaLevi', he: 'בית הלוי' },
  { en: 'Beit Hillel', he: 'בית הלל' },
  { en: 'Beit HaEmek', he: 'בית העמק' },
  { en: 'Beit HaArava', he: 'בית הערבה' },
  { en: 'Beit HaShita', he: 'בית השיטה' },
  { en: 'Beit Wazan', he: 'בית וזן' },
  { en: 'Beit Zeid', he: 'בית זיד' },
  { en: 'Beit Zayit', he: 'בית זית' },
  { en: 'Beit Zera', he: 'בית זרע' },
  { en: 'Beit Horon', he: 'בית חורון' },
  { en: 'Beit Cherot', he: 'בית חירות' },
  { en: 'Beit Chilkiya', he: 'בית חלקיה' },
  { en: 'Beit Hanoun', he: 'בית חנון' },
  { en: 'Beit Hanina', he: 'בית חנינא' },
  { en: 'Beit Hanan', he: 'בית חנן' },
  { en: 'Beit Chananya', he: 'בית חנניה' },
  { en: 'Beit Hashmonai', he: 'בית חשמונאי' },
  { en: 'Beit Yehoshua', he: 'בית יהושע' },
  { en: 'Beit Yosef', he: 'בית יוסף' },
  { en: 'Beit Yanai', he: 'בית ינאי' },
  { en: 'Beit Yitzchak-Shaar Hefer', he: 'בית יצחק-שער חפר' },
  { en: 'Beit Kachel Gam', he: 'בית כאחל גמ' },
  { en: 'Beit Lahia', he: 'בית לאהיה' },
  { en: 'Beit Lechem', he: 'בית לחם' },
  { en: 'Beit Lechem HaGlilit', he: 'בית לחם הגלילית' },
  { en: 'Beit Lid', he: 'בית ליד' },
  { en: 'Beit Liqya', he: 'בית לקיא' },
  { en: 'Beit Meir', he: 'בית מאיר' },
  { en: 'Beit Machsir', he: 'בית מחסיר' },
  { en: 'Beit Marsam', he: 'בית מרסם' },
  { en: 'Beit Nechemya', he: 'בית נחמיה' },
  { en: 'Beit Nir', he: 'בית ניר' },
  { en: 'Beit Nekufa', he: 'בית נקופה' },
  { en: 'Beit Sahour', he: 'בית סאחור' },
  { en: 'Beit Surik', he: 'בית סוריכ' },
  { en: 'Beit Sira', he: 'בית סירא' },
  { en: 'Beit Awa', he: 'בית עוא' },
  { en: 'Beit Oved', he: 'בית עובד' },
  { en: 'Beit Uziel', he: 'בית עוזיאל' },
  { en: 'Beit Ur al-Fauqa', he: 'בית עור אל' },
  { en: 'Beit Ezra', he: 'בית עזרא' },
  { en: 'Beit Amra', he: 'בית עמרא' },
  { en: 'Beit Arif', he: 'בית עריף' },
  { en: 'Beit Fajar', he: 'בית פג\'אר' },
  { en: 'Beit Furik', he: 'בית פוריכ' },
  { en: 'Beit Tzvi', he: 'בית צבי' },
  { en: 'Beit Qad Dro', he: 'בית קאד דרו' },
  { en: 'Beit Qad Tso', he: 'בית קאד צפו' },
  { en: 'Beit Kama', he: 'בית קמה' },
  { en: 'Beit Keshet', he: 'בית קשת' },
  { en: 'Beit Rabban', he: 'בית רבן' },
  { en: 'Beit Rima', he: 'בית רימא' },
  { en: 'Beit Rimon', he: 'בית רימון' },
  { en: 'Beit Shean', he: 'בית שאן' },
  { en: 'Beit Shemesh', he: 'בית שמש' },
  { en: 'Beit Shearim', he: 'בית שערים' },
  { en: 'Beit Shikma', he: 'בית שקמה' },
  { en: 'Beita a-Tachta', he: 'ביתא א תחתא' },
  { en: 'Beita Fauqa', he: 'ביתא פוקא' },
  { en: 'Beitunya', he: 'ביתוניא' },
  { en: 'Beitin', he: 'ביתין' },
  { en: 'Bitan Aharon', he: 'ביתן אהרן' },
  { en: 'Beitar Illit', he: 'ביתר עילית' },
  { en: 'Bechora', he: 'בכורה' },
  { en: 'Balata', he: 'בלאטה' },
  { en: 'Bala', he: 'בלעא' },
  { en: 'Bilin', he: 'בלעין' },
  { en: 'Balfouriya', he: 'בלפוריה' },
  { en: 'Ben Zakkai', he: 'בן זכאי' },
  { en: 'Ben Ami', he: 'בן עמי' },
  { en: 'Ben Shemen (Youth Village)', he: 'בן שמן (כפר נוער)' },
  { en: 'Ben Shemen (Moshav)', he: 'בן שמן (מושב)' },
  { en: 'Bnei Brak', he: 'בני ברק' },
  { en: 'Bnei Dekalim', he: 'בני דקלים' },
  { en: 'Bnei Darom', he: 'בני דרום' },
  { en: 'Bnei Dror', he: 'בני דרור' },
  { en: 'Bnei Yehuda', he: 'בני יהודה' },
  { en: 'Bani Naim', he: 'בני נעים' },
  { en: 'Bnei Netzarim', he: 'בני נצרים' },
  { en: 'Bani Suheila', he: 'בני סוהילה' },
  { en: 'Bnei Atarot', he: 'בני עטרות' },
  { en: 'Bnei Ayish', he: 'בני עי"ש' },
  { en: 'Bnei Atzmon', he: 'בני עצמון' },
  { en: 'Bnei Tzion', he: 'בני ציון' },
  { en: 'Bnei Raam', he: 'בני ראם' },
  { en: 'Bnaya', he: 'בניה' },
  { en: 'Binyamina-Givat Ada', he: 'בנימינה-גבעת עדה' },
  { en: 'Basma', he: 'בסמ"ה' },
  { en: 'Basmat Tabun', he: 'בסמת טבעון' },
  { en: 'Baana', he: 'בענה' },
  { en: 'Batzra', he: 'בצרה' },
  { en: 'Betzet', he: 'בצת' },
  { en: 'Baqua', he: 'בקוע' },
  { en: 'Bekaot', he: 'בקעות' },
  { en: 'Bar Giora', he: 'בר גיורא' },
  { en: 'Bar Yochai', he: 'בר יוחאי' },
  { en: 'Barj', he: 'ברג\'' },
  { en: 'Bardala', he: 'ברדלא' },
  { en: 'Bruqin', he: 'ברוקין' },
  { en: 'Brur Chayil', he: 'ברור חיל' },
  { en: 'Berosh', he: 'ברוש' },
  { en: 'Bartaa', he: 'ברטעה' },
  { en: 'Breij', he: 'בריג' },
  { en: 'Bracha', he: 'ברכה' },
  { en: 'Brachya', he: 'ברכיה' },
  { en: 'Baram', he: 'ברעם' },
  { en: 'Barak', he: 'ברק' },
  { en: 'Barqa', he: 'ברקא' },
  { en: 'Barkai', he: 'ברקאי' },
  { en: 'Burqin', he: 'ברקין' },
  { en: 'Barkan', he: 'ברקן' },
  { en: 'Bareket', he: 'ברקת' },
  { en: 'Bat Hadar', he: 'בת הדר' },
  { en: 'Bat Chen', he: 'בת חן' },
  { en: 'Bat Hefer', he: 'בת חפר' },
  { en: 'Bat Chatzor', he: 'בת חצור' },
  { en: 'Bat Yam', he: 'בת ים' },
  { en: 'Bat Ayin', he: 'בת עין' },
  { en: 'Bat Shlomo', he: 'בת שלמה' },
  { en: 'Battir', he: 'בתיר' },

  // ג
  { en: 'Jalud', he: 'ג\'אלוד' },
  { en: 'Jania', he: 'ג\'אניה' },
  { en: 'Jarushiya', he: 'ג\'ארושיה' },
  { en: 'Jaba Jenin', he: 'ג\'בע ג\'נין' },
  { en: 'Jaba Ramallah', he: 'ג\'בע רמאללה' },
  { en: 'Jaba', he: 'ג\'בעה' },
  { en: 'Jadida', he: 'ג\'דידה' },
  { en: 'Jadira', he: 'ג\'דירה' },
  { en: 'Jurish', he: 'ג\'וריש' },
  { en: 'Jurat al-Sham', he: 'ג\'ורת אל שמ' },
  { en: 'Jaz Abu Raad', he: 'ג\'ז אבו רעד' },
  { en: 'Jib', he: 'ג\'יב' },
  { en: 'Jibia', he: 'ג\'יביא' },
  { en: 'Jiyus', he: 'ג\'יוס' },
  { en: 'Jit', he: 'ג\'ית' },
  { en: 'Jalbon', he: 'ג\'לבון' },
  { en: 'Jaljulia', he: 'ג\'לג\'ליה' },
  { en: 'Jalazoun', he: 'ג\'לזון' },
  { en: 'Jlama', he: 'ג\'למה' },
  { en: 'Jalqamus', he: 'ג\'לקמוס' },
  { en: 'Jamala', he: 'ג\'מאלה' },
  { en: 'Jamaain', he: 'ג\'מאעין' },
  { en: 'Jneid', he: 'ג\'ניד' },
  { en: 'Jenin', he: 'ג\'נין' },
  { en: 'Jinsafut', he: 'ג\'נצאפוט' },
  { en: 'Jarba', he: 'ג\'רבא' },
  { en: 'Geulei Teiman', he: 'גאולי תימן' },
  { en: 'Geulim', he: 'גאולים' },
  { en: 'Galya', he: 'גאליה' },
  { en: 'Jabalya', he: 'גבאליה' },
  { en: 'Jabalya City', he: 'גבאליה העיר' },
  { en: 'Gevulot', he: 'גבולות' },
  { en: 'Gevim', he: 'גבים' },
  { en: 'Jabal al-Araf', he: 'גבל אל ערף' },
  { en: 'Jabal Halal', he: 'גבל הלאל' },
  { en: 'Jabal Hamir', he: 'גבל חמיר' },
  { en: 'Jabal Magara', he: 'גבל מגארה' },
  { en: 'Geva', he: 'גבע' },
  { en: 'Geva Binyamin', he: 'גבע בנימין' },
  { en: 'Geva Carmel', he: 'גבע כרמל' },
  { en: 'Givolim', he: 'גבעולים' },
  { en: 'Givon HaChadasha', he: 'גבעון החדשה' },
  { en: 'Givot Bar', he: 'גבעות בר' },
  { en: 'Givat Avni', he: 'גבעת אבני' },
  { en: 'Givat Ela', he: 'גבעת אלה' },
  { en: 'Givat Brenner', he: 'גבעת ברנר' },
  { en: 'Givat HaShlosha', he: 'גבעת השלושה' },
  { en: 'Givat Zeev', he: 'גבעת זאב' },
  { en: 'Givat Chen', he: 'גבעת ח"ן' },
  { en: 'Givat Chaim (Ichud)', he: 'גבעת חיים (איחוד)' },
  { en: 'Givat Chaim (Meuchad)', he: 'גבעת חיים (מאוחד)' },
  { en: 'Givat Yoav', he: 'גבעת יואב' },
  { en: 'Givat Yearim', he: 'גבעת יערים' },
  { en: 'Givat Yeshayahu', he: 'גבעת ישעיהו' },
  { en: 'Givat Koach', he: 'גבעת כ"ח' },
  { en: 'Givat Nili', he: 'גבעת ניל"י' },
  { en: 'Givat Ada', he: 'גבעת עדה' },
  { en: 'Givat Oz', he: 'גבעת עוז' },
  { en: 'Givat Shmuel', he: 'גבעת שמואל' },
  { en: 'Givat Shemesh', he: 'גבעת שמש' },
  { en: 'Givat Shapira', he: 'גבעת שפירא' },
  { en: 'Givati', he: 'גבעתי' },
  { en: 'Givatayim', he: 'גבעתיים' },
  { en: 'Gevaram', he: 'גברעם' },
  { en: 'Gevat', he: 'גבת' },
  { en: 'Gadot', he: 'גדות' },
  { en: 'Gadid', he: 'גדיד' },
  { en: 'Gadida', he: 'גדידה' },
  { en: 'Judeida-Makr', he: 'גדיידה-מכר' },
  { en: 'Gadish', he: 'גדיש' },
  { en: 'Gidona', he: 'גדעונה' },
  { en: 'Gedera', he: 'גדרה' },
  { en: 'Gules', he: 'גולס' },
  { en: 'Gonen', he: 'גונן' },
  { en: 'Goren', he: 'גורן' },
  { en: 'Gornot HaGalil', he: 'גורנות הגליל' },
  { en: 'Gazit', he: 'גזית' },
  { en: 'Gezer', he: 'גזר' },
  { en: 'Gea', he: 'גיאה' },
  { en: 'Givton', he: 'גיבתון' },
  { en: 'Gizo', he: 'גיזו' },
  { en: 'Gilon', he: 'גילון' },
  { en: 'Gilat', he: 'גילת' },
  { en: 'Ginosar', he: 'גינוסר' },
  { en: 'Ginegar', he: 'גיניגר' },
  { en: 'Ginaton', he: 'גינתון' },
  { en: 'Gitta', he: 'גיתה' },
  { en: 'Gittit', he: 'גיתית' },
  { en: 'Gelaon', he: 'גלאון' },
  { en: 'Jalgulya', he: 'גלגוליה' },
  { en: 'Gilgal', he: 'גלגל' },
  { en: 'Galil Yam', he: 'גליל ים' },
  { en: 'Gilad (Even Yitzchak)', he: 'גלעד (אבן יצחק)' },
  { en: 'Gimzo', he: 'גמזו' },
  { en: 'Gan Or', he: 'גן אור' },
  { en: 'Gan HaDarom', he: 'גן הדרום' },
  { en: 'Gan HaShomron', he: 'גן השומרון' },
  { en: 'Gan Chaim', he: 'גן חיים' },
  { en: 'Gan Yoshiya', he: 'גן יאשיה' },
  { en: 'Gan Yavne', he: 'גן יבנה' },
  { en: 'Gan Ner', he: 'גן נר' },
  { en: 'Gan Sorek', he: 'גן שורק' },
  { en: 'Gan Shlomo', he: 'גן שלמה' },
  { en: 'Gan Shmuel', he: 'גן שמואל' },
  { en: 'Ganabib (Tribe)', he: 'גנאביב (שבט)' },
  { en: 'Ganot', he: 'גנות' },
  { en: 'Ganot Hadar', he: 'גנות הדר' },
  { en: 'Ganei Hadar', he: 'גני הדר' },
  { en: 'Ganei Tal', he: 'גני טל' },
  { en: 'Ganei Yehuda', he: 'גני יהודה' },
  { en: 'Ganei Yochanan', he: 'גני יוחנן' },
  { en: 'Ganei Modiin', he: 'גני מודיעין' },
  { en: 'Ganei Am', he: 'גני עם' },
  { en: 'Ganei Tikva', he: 'גני תקווה' },
  { en: 'Ganim', he: 'גנים' },
  { en: 'Jisr az-Zarqa', he: 'גסר א-זרקא' },
  { en: 'Gaash', he: 'געש' },
  { en: 'Geaton', he: 'געתון' },
  { en: 'Gefen', he: 'גפן' },
  { en: 'Gofna', he: 'גפנא' },
  { en: 'Jaqila', he: 'גקילה' },
  { en: 'Grofit', he: 'גרופית' },
  { en: 'Griya', he: 'גריעה' },
  { en: 'Gush Chalav', he: 'גש (גוש חלב)' },
  { en: 'Geshur', he: 'גשור' },
  { en: 'Gesher', he: 'גשר' },
  { en: 'Gesher HaZiv', he: 'גשר הזיו' },
  { en: 'Gat', he: 'גת' },
  { en: 'Gat (Kibbutz)', he: 'גת (קיבוץ)' },
  { en: 'Gat BaGalil', he: 'גת בגליל' },
  { en: 'Gat Rimon', he: 'גת רימון' },

  // ד
  { en: 'Dahariya', he: 'דאהריה' },
  { en: 'Daliyat al-Karmel', he: 'דאלית אל-כרמל' },
  { en: 'Devora', he: 'דבורה' },
  { en: 'Daburiyya', he: 'דבוריה' },
  { en: 'Devira', he: 'דבירה' },
  { en: 'Davrat', he: 'דברת' },
  { en: 'Deganya A', he: 'דגניה א' },
  { en: 'Deganya B', he: 'דגניה ב' },
  { en: 'Dahab', he: 'דהב' },
  { en: 'Dheisheh', he: 'דהישה' },
  { en: 'Dahar Halat al', he: 'דהר חלת אל' },
  { en: 'Dovev', he: 'דוב"ב' },
  { en: 'Dugit', he: 'דוגית' },
  { en: 'Dolev', he: 'דולב' },
  { en: 'Duma Hebron', he: 'דומא חברון' },
  { en: 'Duma Shechem', he: 'דומא שכם' },
  { en: 'Dor', he: 'דור' },
  { en: 'Dura', he: 'דורא' },
  { en: 'Dura al-Qara', he: 'דורא אל קרע' },
  { en: 'Dorot', he: 'דורות' },
  { en: 'Dahi', he: 'דחי' },
  { en: 'Dahit Brid', he: 'דחית בריד' },
  { en: 'Diuk', he: 'דיוכ' },
  { en: 'Deir Hanna', he: 'דייר חנא' },
  { en: 'Deir Rafat', he: 'דייר ראפאת' },
  { en: 'Dimona', he: 'דימונה' },
  { en: 'Deir a-Shams', he: 'דיר א שמס' },
  { en: 'Deir Abu Daif', he: 'דיר אבו דעי' },
  { en: 'Deir Abu Mashaal', he: 'דיר אבו משע' },
  { en: 'Deir Abziaa', he: 'דיר אבזיע' },
  { en: 'Deir al-Asad', he: 'דיר אל-אסד' },
  { en: 'Deir al-Balah', he: 'דיר אל בלח' },
  { en: 'Deir al-Ghusun', he: 'דיר אל גצון' },
  { en: 'Deir al-Hatab', he: 'דיר אל חטב' },
  { en: 'Deir as-Sudan', he: 'דיר אל סודא' },
  { en: 'Deir al-Asal', he: 'דיר אל עסל' },
  { en: 'Deir Istiya', he: 'דיר אסתיא' },
  { en: 'Deir Ballut', he: 'דיר בלוט' },
  { en: 'Deir Ghazaleh', he: 'דיר גזאלה' },
  { en: 'Deir Jassana', he: 'דיר גסאנה' },
  { en: 'Deir Jarir', he: 'דיר גריר' },
  { en: 'Deir Dibwan', he: 'דיר דבואן' },
  { en: 'Deir Nizam', he: 'דיר נזאם' },
  { en: 'Deir Ammar', he: 'דיר עמאר' },
  { en: 'Deir Qaddis', he: 'דיר קדיס' },
  { en: 'Deir Razah', he: 'דיר רזאח' },
  { en: 'Deir Sharaf', he: 'דיר שרף' },
  { en: 'Dishon', he: 'דישון' },
  { en: 'Dalya', he: 'דליה' },
  { en: 'Dalton', he: 'דלתון' },
  { en: 'Damayda', he: 'דמיידה' },
  { en: 'Dan', he: 'דן' },
  { en: 'Danaba', he: 'דנאבה' },
  { en: 'Dfidfif', he: 'דפידף' },
  { en: 'Dafna', he: 'דפנה' },
  { en: 'Dekel', he: 'דקל' },
  { en: 'Darb al-Malih', he: 'דרב אל מליח' },
  { en: 'Drigat', he: 'דריגאת' },

  // ה
  { en: 'HaOn', he: 'האון' },
  { en: 'HaAshmia', he: 'האשמיה' },
  { en: 'HaBonim', he: 'הבונים' },
  { en: 'HaGoshrim', he: 'הגושרים' },
  { en: 'Hadar Am', he: 'הדר עם' },
  { en: 'Hod HaSharon', he: 'הוד השרון' },
  { en: 'Hodiya', he: 'הודיה' },
  { en: 'Hodiyot', he: 'הודיות' },
  { en: 'Hawashla (Tribe)', he: 'הוואשלה (שבט)' },
  { en: 'Huzayel (Tribe)', he: 'הוזייל (שבט)' },
  { en: 'Hoshaya', he: 'הושעיה' },
  { en: 'HaZorea', he: 'הזורע' },
  { en: 'HaZorim', he: 'הזורעים' },
  { en: 'HaHoterim', he: 'החותרים' },
  { en: 'HaYogev', he: 'היוגב' },
  { en: 'Hila', he: 'הילה' },
  { en: 'HaMaapil', he: 'המעפיל' },
  { en: 'HaSolelim', he: 'הסוללים' },
  { en: 'HaOgen', he: 'העוגן' },
  { en: 'Har Adar', he: 'הר אדר' },
  { en: 'Har Gilo', he: 'הר גילה' },
  { en: 'Har Amasa', he: 'הר עמשא' },
  { en: 'Harel', he: 'הראל' },
  { en: 'Harduf', he: 'הרדוף' },
  { en: 'Herzliya', he: 'הרצליה' },
  { en: 'Hararit', he: 'הררית' },

  // ו
  { en: 'Wadi al-Ahm', he: 'ואדי אל אחמ' },
  { en: 'Wadi al-Bid', he: 'ואדי אל ביד' },
  { en: 'Wadi al-Waar', he: 'ואדי אל וער' },
  { en: 'Wadi al-Ara', he: 'ואדי אל ערא' },
  { en: 'Wadi al-Ari', he: 'ואדי אל ערי' },
  { en: 'Wadi Asla', he: 'ואדי אסלה' },
  { en: 'Wadi Burqin', he: 'ואדי ברקין' },
  { en: 'Wadi Gharandal', he: 'ואדי גרנדל' },
  { en: 'Wadi Hamar', he: 'ואדי חמר' },
  { en: 'Wadi Mabuq', he: 'ואדי מבעוק' },
  { en: 'Wadi Mahash', he: 'ואדי מחאש' },
  { en: 'Wadi Natsab', he: 'ואדי נצב' },
  { en: 'Wadi Natsaryan', he: 'ואדי נצריין' },
  { en: 'Wadi Saal', he: 'ואדי סעאל' },
  { en: 'Wadi Qid', he: 'ואדי קיד' },
  { en: 'Wadi Qirya', he: 'ואדי קריה' },
  { en: 'Wadi Rahba', he: 'ואדי רהבה' },
  { en: 'Wadi Rachba', he: 'ואדי רחבה' },
  { en: 'Wadi Rina', he: 'ואדי רינה' },
  { en: 'Wadi Taman', he: 'ואדי תמן' },
  { en: 'Wadi Tar', he: 'ואדי תר' },
  { en: 'Wadial Amar', he: 'ואדיאל עמר' },
  { en: 'Wast Nuweiba', he: 'ואסט נויבע' },
  { en: 'Vered Yericho', he: 'ורד יריחו' },
  { en: 'Vardon', he: 'ורדון' },

  // ז
  { en: 'Zawiya Jenin', he: 'זאויה ג\'נין' },
  { en: 'Zawiya Tulkarm', he: 'זאויה טול כ' },
  { en: 'Zababdeh', he: 'זבאבדה' },
  { en: 'Zbarga (Tribe)', he: 'זבארגה (שבט)' },
  { en: 'Zabda', he: 'זבדה' },
  { en: 'Zavdiel', he: 'זבדיאל' },
  { en: 'Zbuba', he: 'זבובה' },
  { en: 'Zbidat', he: 'זבידאת' },
  { en: 'Zawata', he: 'זואתה' },
  { en: 'Zohar', he: 'זוהר' },
  { en: 'Zuwaida', he: 'זוואידה' },
  { en: 'Zif', he: 'זיף' },
  { en: 'Zikim', he: 'זיקים' },
  { en: 'Zeita', he: 'זיתא' },
  { en: 'Zeita Jmaain', he: 'זיתא ג\'מעין' },
  { en: 'Zituna', he: 'זיתונה' },
  { en: 'Zetan', he: 'זיתן' },
  { en: 'Zichron Yaakov', he: 'זכרון יעקב' },
  { en: 'Zecharya', he: 'זכריה' },
  { en: 'Zalfa', he: 'זלפה' },
  { en: 'Zemer', he: 'זמר' },
  { en: 'Zimrat', he: 'זמרת' },
  { en: 'Zanoach', he: 'זנוח' },
  { en: 'Zaatara', he: 'זעתרה' },
  { en: 'Zerua', he: 'זרועה' },
  { en: 'Zarzir', he: 'זרזיר' },
  { en: 'Zrachya', he: 'זרחיה' },

  // ח
  { en: 'Khan Yunis', he: 'חאן יונס' },
  { en: 'Khan Yunis City', he: 'חאן יונס הע' },
  { en: 'Haras', he: 'חאראס' },
  { en: 'Haris', he: 'חארס' },
  { en: 'Chavila', he: 'חבילה' },
  { en: 'Habla', he: 'חבלה' },
  { en: 'Havatzelet HaSharon', he: 'חבצלת השרון' },
  { en: 'Chever', he: 'חבר' },
  { en: 'Hebron', he: 'חברון' },
  { en: 'Hagagra', he: 'חגאגרה' },
  { en: 'Haga', he: 'חגה' },
  { en: 'Hagor', he: 'חגור' },
  { en: 'Hagai', he: 'חגי' },
  { en: 'Hagila', he: 'חגילה' },
  { en: 'Hagla', he: 'חגלה' },
  { en: 'Chad Nes', he: 'חד-נס' },
  { en: 'Hadab', he: 'חדב' },
  { en: 'Chadid', he: 'חדיד' },
  { en: 'Cheder', he: 'חדר' },
  { en: 'Hadera', he: 'חדרה' },
  { en: 'Khawaled', he: 'חואלד' },
  { en: 'Khawaled (Tribe)', he: 'חואלד (שבט)' },
  { en: 'Huwara', he: 'חוארה' },
  { en: 'Hujeirat (Dahra)', he: 'חוגייראת (דהרה)' },
  { en: 'Chulda', he: 'חולדה' },
  { en: 'Holon', he: 'חולון' },
  { en: 'Cholit', he: 'חולית' },
  { en: 'Chulata', he: 'חולתה' },
  { en: 'Chomesh', he: 'חומש' },
  { en: 'Husan', he: 'חוסאן' },
  { en: 'Chosen', he: 'חוסן' },
  { en: 'Chusniya', he: 'חוסנייה' },
  { en: 'Chofit', he: 'חופית' },
  { en: 'Chukok', he: 'חוקוק' },
  { en: 'Hura', he: 'חורה' },
  { en: 'Khursa', he: 'חורסה' },
  { en: 'Hurfeish', he: 'חורפיש' },
  { en: 'Chorshim', he: 'חורשים' },
  { en: 'Chavat Shelem', he: 'חות שלם' },
  { en: 'Khuzaa', he: 'חזאעה' },
  { en: 'Chazon', he: 'חזון' },
  { en: 'Hizma', he: 'חזמא' },
  { en: 'Chibat Tzion', he: 'חיבת ציון' },
  { en: 'Chinanit', he: 'חיננית' },
  { en: 'Haifa', he: 'חיפה' },
  { en: 'Cherut', he: 'חירות' },
  { en: 'Chalutz', he: 'חלוץ' },
  { en: 'Halhul', he: 'חלחול' },
  { en: 'Chalmish', he: 'חלמיש' },
  { en: 'Chalaf', he: 'חלף' },
  { en: 'Cheletz', he: 'חלץ' },
  { en: 'Khallet al-Foula', he: 'חלת אל פולה' },
  { en: 'Hammam', he: 'חמאם' },
  { en: 'Chemed', he: 'חמד' },
  { en: 'Chamdiya', he: 'חמדיה' },
  { en: 'Chemdat', he: 'חמדת' },
  { en: 'Hamra', he: 'חמרה' },
  { en: 'Chaniel', he: 'חניאל' },
  { en: 'Chanita', he: 'חניתה' },
  { en: 'Chanton', he: 'חנתון' },
  { en: 'Chasaka', he: 'חסכה' },
  { en: 'Chispin', he: 'חספין' },
  { en: 'Chefetz Chaim', he: 'חפץ חיים' },
  { en: 'Cheftzi-Ba', he: 'חפצי-בה' },
  { en: 'Chatzav', he: 'חצב' },
  { en: 'Chatzeva', he: 'חצבה' },
  { en: 'Chatzor-Ashdod', he: 'חצור-אשדוד' },
  { en: 'Chatzor HaGlilit', he: 'חצור הגלילית' },
  { en: 'Chatzer Beerotayim', he: 'חצר בארותיים' },
  { en: 'Chatzrot Chulda', he: 'חצרות חולדה' },
  { en: 'Chatzrot Chefer', he: 'חצרות חפר' },
  { en: 'Chatzrot Yasef', he: 'חצרות יסף' },
  { en: 'Chatzrot Koach', he: 'חצרות כ"ח' },
  { en: 'Chatzarim', he: 'חצרים' },
  { en: 'Kharab Laat', he: 'חרב לאת' },
  { en: 'Khirbet Abu Ham', he: 'חרבת אבו חמ' },
  { en: 'Khirbet Abu Naj', he: 'חרבת אבו נג' },
  { en: 'Khirbet Abu Sal', he: 'חרבת אבו סל' },
  { en: 'Khirbet Abu Fal', he: 'חרבת אבו פל' },
  { en: 'Khirbet Um al', he: 'חרבת אום אל' },
  { en: 'Khirbet al-Naj', he: 'חרבת אל נג' },
  { en: 'Khirbet al-Aqr', he: 'חרבת אל אקר' },
  { en: 'Khirbet al-Ashq', he: 'חרבת אל אשק' },
  { en: 'Khirbet al-Deir', he: 'חרבת אל דיר' },
  { en: 'Khirbet al-Dalb', he: 'חרבת אל דלב' },
  { en: 'Khirbet al-Hajar', he: 'חרבת אל הגר' },
  { en: 'Khirbet al-Hadab', he: 'חרבת אל חדב' },
  { en: 'Khirbet al-Hafi', he: 'חרבת אל חפי' },
  { en: 'Khirbet al-Harz', he: 'חרבת אל חרז' },
  { en: 'Khirbet al-Tabaq', he: 'חרבת אל טבק' },
  { en: 'Khirbet al-Kum', he: 'חרבת אל כום' },
  { en: 'Khirbet al-Luz', he: 'חרבת אל לוז' },
  { en: 'Khirbet al-Mago', he: 'חרבת אל מגו' },
  { en: 'Khirbet al-Magn', he: 'חרבת אל מגנ' },
  { en: 'Khirbet al-Madu', he: 'חרבת אל מדו' },
  { en: 'Khirbet al-Matal', he: 'חרבת אל מטל' },
  { en: 'Khirbet al-Mansh', he: 'חרבת אל מנש' },
  { en: 'Khirbet al-Maatz', he: 'חרבת אל מעצ' },
  { en: 'Khirbet al-Marj', he: 'חרבת אל מרג' },
  { en: 'Khirbet al-Nabi', he: 'חרבת אל נבי' },
  { en: 'Khirbet al-Sakka', he: 'חרבת אל סכה' },
  { en: 'Khirbet al-Adas', he: 'חרבת אל עדס' },
  { en: 'Khirbet al-Aug', he: 'חרבת אל עוג' },
  { en: 'Khirbet al-Alaq', he: 'חרבת אל עלק' },
  { en: 'Khirbet al-Aqr2', he: 'חרבת אל עקר' },
  { en: 'Khirbet al-Aru', he: 'חרבת אל ערו' },
  { en: 'Khirbet al-Tsari', he: 'חרבת אל צרי' },
  { en: 'Khirbet al-Qatsu', he: 'חרבת אל קצו' },
  { en: 'Khirbet al-Sheikh', he: 'חרבת אל שיח' },
  { en: 'Khirbet Beit Has', he: 'חרבת בית חס' },
  { en: 'Khirbet Beit An', he: 'חרבת בית ענ' },
  { en: 'Khirbet Beit Taa', he: 'חרבת בית תע' },
  { en: 'Khirbet Brizaa', he: 'חרבת בריזעה' },
  { en: 'Khirbet Gador', he: 'חרבת גאדור' },
  { en: 'Khirbet Jahzam', he: 'חרבת גהזם' },
  { en: 'Khirbet Jib A', he: 'חרבת גיב א' },
  { en: 'Khirbet Jarad', he: 'חרבת גראד' },
  { en: 'Khirbet Deir Tsa', he: 'חרבת דיר צא' },
  { en: 'Khirbet Wadi A', he: 'חרבת ואדי א' },
  { en: 'Khirbet Wadah', he: 'חרבת ודח' },
  { en: 'Khirbet Zaher', he: 'חרבת זאהר' },
  { en: 'Khirbet Zeita', he: 'חרבת זיתא' },
  { en: 'Khirbet Hadir', he: 'חרבת חדיר' },
  { en: 'Khirbet Tawil', he: 'חרבת טויל' },
  { en: 'Khirbet Kazun', he: 'חרבת כזון' },
  { en: 'Khirbet Kanaan', he: 'חרבת כנעאן' },
  { en: 'Khirbet Karma', he: 'חרבת כרמה' },
  { en: 'Khirbet Murak', he: 'חרבת מורק' },
  { en: 'Khirbet Main', he: 'חרבת מעין' },
  { en: 'Khirbet Nabi Tsa', he: 'חרבת נבי צא' },
  { en: 'Khirbet Samia', he: 'חרבת סמיא' },
  { en: 'Khirbet Aba', he: 'חרבת עאבא' },
  { en: 'Khirbet Aud', he: 'חרבת עוד' },
  { en: 'Khirbet Ilat A', he: 'חרבת עילת ע' },
  { en: 'Khirbet Asla', he: 'חרבת עסלה' },
  { en: 'Khirbet Faqiqis', he: 'חרבת פקיקס' },
  { en: 'Khirbet Tsafa', he: 'חרבת צאפא' },
  { en: 'Khirbet Tsir', he: 'חרבת ציר' },
  { en: 'Khirbet Qeis', he: 'חרבת קיס' },
  { en: 'Khirbet Ras al', he: 'חרבת ראס אל' },
  { en: 'Khirbet Ras At', he: 'חרבת ראס עט' },
  { en: 'Khirbet Raqaa', he: 'חרבת רקעה' },
  { en: 'Khirbet Shweika', he: 'חרבת שויכה' },
  { en: 'Khirbata', he: 'חרבתא' },
  { en: 'Khirbata al-Matz', he: 'חרבתא אל מצ' },
  { en: 'Kharuba Kolel', he: 'חרובה כולל' },
  { en: 'Charutzim', he: 'חרוצים' },
  { en: 'Charish-Katzir', he: 'חריש-קציר' },
  { en: 'Charmala', he: 'חרמלה' },
  { en: 'Charmesh', he: 'חרמש' },
  { en: 'Charsa', he: 'חרסה' },
  { en: 'Charashim', he: 'חרשים' },
  { en: 'Chashmonaim', he: 'חשמונאים' },

  // ט
  { en: 'Tivon', he: 'טבעון' },
  { en: 'Tiberias', he: 'טבריה' },
  { en: 'Tuani', he: 'טואני' },
  { en: 'Tuba-Zangariyye', he: 'טובא-זנגריה' },
  { en: 'Tubas', he: 'טובאס' },
  { en: 'Tawil al-Ami', he: 'טויל אל אמי' },
  { en: 'Tulkarm', he: 'טול כרם' },
  { en: 'Tura al-Gharb', he: 'טורה אל גרב' },
  { en: 'Turan', he: 'טורעאן' },
  { en: 'Tiba Jenin', he: 'טיבה ג\'נין' },
  { en: 'Tiba Ramallah', he: 'טיבה רמאללה' },
  { en: 'Tayibe', he: 'טייבה' },
  { en: 'Tayibe (BaEmek)', he: 'טייבה (בעמק)' },
  { en: 'Tira', he: 'טירה' },
  { en: 'Tirat Yehuda', he: 'טירת יהודה' },
  { en: 'Tirat Carmel', he: 'טירת כרמל' },
  { en: 'Tirat Tzvi', he: 'טירת צבי' },
  { en: 'Tal-El', he: 'טל-אל' },
  { en: 'Tal Shachar', he: 'טל שחר' },
  { en: 'Taluza', he: 'טלוזה' },
  { en: 'Talalim', he: 'טללים' },
  { en: 'Talmon', he: 'טלמון' },
  { en: 'Tamun', he: 'טמון' },
  { en: 'Tamra', he: 'טמרה' },
  { en: 'Tamra (Yizrael)', he: 'טמרה (יזרעאל)' },
  { en: 'Tana', he: 'טנא' },
  { en: 'Tifchot', he: 'טפחות' },
  { en: 'Tarama', he: 'טראמה' },

  // י
  { en: 'Yatta', he: 'יאטה' },
  { en: 'Yamoun', he: 'יאמון' },
  { en: 'Yanouh', he: 'יאנוח' },
  { en: 'Yanouh-Jat', he: 'יאנוח-גת' },
  { en: 'Yanoun', he: 'יאנון' },
  { en: 'Yasuf', he: 'יאסוף' },
  { en: 'Yatzid', he: 'יאציד' },
  { en: 'Yevul', he: 'יבול' },
  { en: 'Yavneel', he: 'יבנאל' },
  { en: 'Yavne', he: 'יבנה' },
  { en: 'Yabrud', he: 'יברוד' },
  { en: 'Yagur', he: 'יגור' },
  { en: 'Yagel', he: 'יגל' },
  { en: 'Yad Binyamin', he: 'יד בנימין' },
  { en: 'Yad HaShmona', he: 'יד השמונה' },
  { en: 'Yad Chana', he: 'יד חנה' },
  { en: 'Yad Mordechai', he: 'יד מרדכי' },
  { en: 'Yad Natan', he: 'יד נתן' },
  { en: 'Yad Rambam', he: 'יד רמב"ם' },
  { en: 'Yedida', he: 'ידידה' },
  { en: 'Yehud-Monosson', he: 'יהוד-מונוסון' },
  { en: 'Yahel', he: 'יהל' },
  { en: 'Yuval', he: 'יובל' },
  { en: 'Yuvalim', he: 'יובלים' },
  { en: 'Yodfat', he: 'יודפת' },
  { en: 'Yonatan', he: 'יונתן' },
  { en: 'Yoshivya', he: 'יושיביה' },
  { en: 'Yizrael', he: 'יזרעאל' },
  { en: 'Yizraam', he: 'יזרעם' },
  { en: 'Yechiam', he: 'יחיעם' },
  { en: 'Yotvata', he: 'יטבתה' },
  { en: 'Yitav', he: 'ייט"ב' },
  { en: 'Yakhini', he: 'יכיני' },
  { en: 'Yama', he: 'ימא' },
  { en: 'Yanuv', he: 'ינוב' },
  { en: 'Yinon', he: 'ינון' },
  { en: 'Yesod HaMaala', he: 'יסוד המעלה' },
  { en: 'Yesodot', he: 'יסודות' },
  { en: 'Yasour', he: 'יסעור' },
  { en: 'Yabed', he: 'יעבד' },
  { en: 'Yaad', he: 'יעד' },
  { en: 'Yael', he: 'יעל' },
  { en: 'Yaaf', he: 'יעף' },
  { en: 'Yaara', he: 'יערה' },
  { en: 'Yafia', he: 'יפיע' },
  { en: 'Yafit', he: 'יפית' },
  { en: 'Yifat', he: 'יפעת' },
  { en: 'Yiftach', he: 'יפתח' },
  { en: 'Yitzhar', he: 'יצהר' },
  { en: 'Yatzitz', he: 'יציץ' },
  { en: 'Yakum', he: 'יקום' },
  { en: 'Yakir', he: 'יקיר' },
  { en: 'Yokneam (Moshava)', he: 'יקנעם (מושבה)' },
  { en: 'Yokneam Illit', he: 'יקנעם עילית' },
  { en: 'Yiron', he: 'יראון' },
  { en: 'Yardena', he: 'ירדנה' },
  { en: 'Yeruham', he: 'ירוחם' },
  { en: 'Jerusalem', he: 'ירושלים' },
  { en: 'Yarchiv', he: 'ירחיב' },
  { en: 'Jericho', he: 'יריחו' },
  { en: 'Yarka', he: 'ירכא' },
  { en: 'Yarkona', he: 'ירקונה' },
  { en: 'Yesha', he: 'ישע' },
  { en: 'Yishai', he: 'ישעי' },
  { en: 'Yashresh', he: 'ישרש' },
  { en: 'Yated', he: 'יתד' },
  { en: 'Yatir', he: 'יתיר' },
  { en: 'Yatma', he: 'יתמא' },

  // כ
  { en: 'Kabul', he: 'כאבול' },
  { en: 'Kaukab Abu al-Hija', he: 'כאוכב אבו אל-היגא' },
  { en: 'Kabri', he: 'כברי' },
  { en: 'Kadoorie', he: 'כדורי' },
  { en: 'Kedim', he: 'כדים' },
  { en: 'Kadita', he: 'כדיתה' },
  { en: 'Kubar', he: 'כובר' },
  { en: 'Kochav HaShachar', he: 'כוכב השחר' },
  { en: 'Kochav Yair', he: 'כוכב יאיר' },
  { en: 'Kochav Yaakov', he: 'כוכב יעקב' },
  { en: 'Kochav Michael', he: 'כוכב מיכאל' },
  { en: 'Kuntila', he: 'כונתילא' },
  { en: 'Kur', he: 'כור' },
  { en: 'Korazim', he: 'כורזים' },
  { en: 'Kaziya al-Ratar', he: 'כזיה אל רטר' },
  { en: 'Kachal', he: 'כחל' },
  { en: 'Kachla', he: 'כחלה' },
  { en: 'Kissufim', he: 'כיסופים' },
  { en: 'Kishur', he: 'כישור' },
  { en: 'Klil', he: 'כליל' },
  { en: 'Kalanit', he: 'כלנית' },
  { en: 'Kamana', he: 'כמאנה' },
  { en: 'Kamhin', he: 'כמהין' },
  { en: 'Kamon', he: 'כמון' },
  { en: 'Kanot', he: 'כנות' },
  { en: 'Kanaf', he: 'כנף' },
  { en: 'Kinneret (Moshava)', he: 'כנרת (מושבה)' },
  { en: 'Kinneret (Kvutza)', he: 'כנרת (קבוצה)' },
  { en: 'Kseifa', he: 'כסיפה' },
  { en: 'Kisalon', he: 'כסלון' },
  { en: 'Kisra', he: 'כסרא' },
  { en: 'Kisra-Sumei', he: 'כסרא-סמיע' },
  { en: 'Kaabiyye-Tabbash-Hajajre', he: 'כעביה-טבאש-חגאגרה' },
  { en: 'Kaabiye Tribe', he: 'כעביה שבט' },
  { en: 'Kfir', he: 'כפיר' },
  { en: 'Kfirat', he: 'כפירת' },
  { en: 'Kifl Haris', he: 'כפל חארת' },
  { en: 'Kfar Aviv', he: 'כפר אביב' },
  { en: 'Kfar Adumim', he: 'כפר אדומים' },
  { en: 'Kfar Uriya', he: 'כפר אוריה' },
  { en: 'Kfar Azar', he: 'כפר אזר' },
  { en: 'Kfar Achim', he: 'כפר אחים' },
  { en: 'Kafr al-Dik', he: 'כפר אל דיכ' },
  { en: 'Kafr al-Labad', he: 'כפר אל לבד' },
  { en: 'Kfar Bialik', he: 'כפר ביאליק' },
  { en: 'Kfar Bilu', he: 'כפר ביל"ו' },
  { en: 'Kfar Blum', he: 'כפר בלום' },
  { en: 'Kfar Ben Nun', he: 'כפר בן נון' },
  { en: 'Kafr Bara', he: 'כפר ברא' },
  { en: 'Kfar Baruch', he: 'כפר ברוך' },
  { en: 'Kfar Gidon', he: 'כפר גדעון' },
  { en: 'Kfar Galim', he: 'כפר גלים' },
  { en: 'Kfar Glikson', he: 'כפר גליקסון' },
  { en: 'Kfar Giladi', he: 'כפר גלעדי' },
  { en: 'Kafr Jamal', he: 'כפר גמאל' },
  { en: 'Kafr Dan', he: 'כפר דאן' },
  { en: 'Kfar Daniel', he: 'כפר דניאל' },
  { en: 'Kfar Darom', he: 'כפר דרום' },
  { en: 'Kfar HaOranim', he: 'כפר האורנים' },
  { en: 'Kfar HaChoresh', he: 'כפר החורש' },
  { en: 'Kfar HaMaccabi', he: 'כפר המכבי' },
  { en: 'Kfar HaNagid', he: 'כפר הנגיד' },
  { en: 'Kfar HaNoar HaDati', he: 'כפר הנוער הדתי' },
  { en: 'Kfar HaNasi', he: 'כפר הנשיא' },
  { en: 'Kfar HaS', he: 'כפר הס' },
  { en: 'Kfar HaRoeh', he: 'כפר הרא"ה' },
  { en: 'Kfar HaRif', he: 'כפר הרי"ף' },
  { en: 'Kfar Vitkin', he: 'כפר ויתקין' },
  { en: 'Kfar Warburg', he: 'כפר ורבורג' },
  { en: 'Kfar Vradim', he: 'כפר ורדים' },
  { en: 'Kfar Zoharim', he: 'כפר זוהרים' },
  { en: 'Kafr Zibad', he: 'כפר זיבאד' },
  { en: 'Kfar Zeitim', he: 'כפר זיתים' },
  { en: 'Kfar Chabad', he: 'כפר חב"ד' },
  { en: 'Kfar Chushen', he: 'כפר חושן' },
  { en: 'Kfar Chitim', he: 'כפר חיטים' },
  { en: 'Kfar Chaim', he: 'כפר חיים' },
  { en: 'Kfar Chananya', he: 'כפר חנניה' },
  { en: 'Kfar Chasidim A', he: 'כפר חסידים א' },
  { en: 'Kfar Chasidim B', he: 'כפר חסידים ב' },
  { en: 'Kfar Charuv', he: 'כפר חרוב' },
  { en: 'Kfar Truman', he: 'כפר טרומן' },
  { en: 'Kfar Yasif', he: 'כפר יאסיף' },
  { en: 'Kfar Yedidya', he: 'כפר ידידיה' },
  { en: 'Kfar Yehoshua', he: 'כפר יהושע' },
  { en: 'Kfar Yona', he: 'כפר יונה' },
  { en: 'Kfar Yechezkel', he: 'כפר יחזקאל' },
  { en: 'Kfar Yabetz', he: 'כפר יעבץ' },
  { en: 'Kfar Kama', he: 'כפר כמא' },
  { en: 'Kfar Kana', he: 'כפר כנא' },
  { en: 'Kafr Laqif', he: 'כפר לאקף' },
  { en: 'Kafr Malik', he: 'כפר מאלכ' },
  { en: 'Kfar Monash', he: 'כפר מונש' },
  { en: 'Kfar Maimon', he: 'כפר מימון' },
  { en: 'Kfar Malal', he: 'כפר מל"ל' },
  { en: 'Kafr Manda', he: 'כפר מנדא' },
  { en: 'Kfar Menachem', he: 'כפר מנחם' },
  { en: 'Kfar Masaryk', he: 'כפר מסריק' },
  { en: 'Kfar Mitzar', he: 'כפר מצר' },
  { en: 'Kfar Mordechai', he: 'כפר מרדכי' },
  { en: 'Kfar Netar', he: 'כפר נטר' },
  { en: 'Kafr Naama', he: 'כפר נעמה' },
  { en: 'Kfar Szold', he: 'כפר סאלד' },
  { en: 'Kfar Saba', he: 'כפר סבא' },
  { en: 'Kfar Silver', he: 'כפר סילבר' },
  { en: 'Kfar Sirkin', he: 'כפר סירקין' },
  { en: 'Kafr Sumei', he: 'כפר סמיע' },
  { en: 'Kfar Avoda', he: 'כפר עבודה' },
  { en: 'Kafr Abush', he: 'כפר עבוש' },
  { en: 'Kfar Aza', he: 'כפר עזה' },
  { en: 'Kfar Aziz', he: 'כפר עזיז' },
  { en: 'Kafr Ein', he: 'כפר עין' },
  { en: 'Kfar Etzion', he: 'כפר עציון' },
  { en: 'Kafr Aqab', he: 'כפר עקב' },
  { en: 'Kfar Pines', he: 'כפר פינס' },
  { en: 'Kfar Tzur', he: 'כפר צור' },
  { en: 'Kafr Qasim', he: 'כפר קאסם' },
  { en: 'Kfar Kadum', he: 'כפר קדום' },
  { en: 'Kafr Qud', he: 'כפר קוד' },
  { en: 'Kfar Kish', he: 'כפר קיש' },
  { en: 'Kafr Qalil', he: 'כפר קליל' },
  { en: 'Kafr Qara', he: 'כפר קרע' },
  { en: 'Kafr Rai', he: 'כפר ראעי' },
  { en: 'Kfar Rosh HaNikra', he: 'כפר ראש הנקרה' },
  { en: 'Kfar Rosenwald (Zarit)', he: 'כפר רוזנואלד (זרעית)' },
  { en: 'Kfar Ruppin', he: 'כפר רופין' },
  { en: 'Kfar Ruth', he: 'כפר רות' },
  { en: 'Kafr Raman', he: 'כפר רמאן' },
  { en: 'Kfar Shamai', he: 'כפר שמאי' },
  { en: 'Kfar Shmuel', he: 'כפר שמואל' },
  { en: 'Kfar Shmaryahu', he: 'כפר שמריהו' },
  { en: 'Kfar Tavor', he: 'כפר תבור' },
  { en: 'Kafr Thulth', he: 'כפר תלת' },
  { en: 'Kfar Tapuach', he: 'כפר תפוח' },
  { en: 'Karza', he: 'כרזה' },
  { en: 'Kerei Deshe', he: 'כרי דשא' },
  { en: 'Karkum', he: 'כרכום' },
  { en: 'Kerem Abu Matsal', he: 'כרם אבו מצל' },
  { en: 'Kerem Abu Shari', he: 'כרם אבו שרי' },
  { en: 'Kerem Ben Zimra', he: 'כרם בן זמרה' },
  { en: 'Kerem Ben Shemen', he: 'כרם בן שמן' },
  { en: 'Kerem Yavne (Yeshiva)', he: 'כרם יבנה (ישיבה)' },
  { en: 'Kerem Maharal', he: 'כרם מהר"ל' },
  { en: 'Kerem Shalom', he: 'כרם שלום' },
  { en: 'Karmei Yosef', he: 'כרמי יוסף' },
  { en: 'Karmei Tzur', he: 'כרמי צור' },
  { en: 'Karmiel', he: 'כרמיאל' },
  { en: 'Karmiya', he: 'כרמיה' },
  { en: 'Kramim', he: 'כרמים' },
  { en: 'Carmel', he: 'כרמל' },

  // ל
  { en: 'Lavon', he: 'לבון' },
  { en: 'Lavi', he: 'לביא' },
  { en: 'Lavan', he: 'לבן' },
  { en: 'Lavan Sharkiya', he: 'לבן שרקיה' },
  { en: 'Lehavim', he: 'לבנים' },
  { en: 'Lahav', he: 'להב' },
  { en: 'Lahavot HaBashan', he: 'להבות הבשן' },
  { en: 'Lahavot Chaviva', he: 'להבות חביבה' },
  { en: 'Lehavim', he: 'להבים' },
  { en: 'Lod', he: 'לוד' },
  { en: 'Luzit', he: 'לוזית' },
  { en: 'Lochamei HaGetaot', he: 'לוחמי הגיטאות' },
  { en: 'Lotem', he: 'לוטם' },
  { en: 'Lotan', he: 'לוטן' },
  { en: 'Liman', he: 'לימן' },
  { en: 'Lachish', he: 'לכיש' },
  { en: 'Lapid', he: 'לפיד' },
  { en: 'Lapidot', he: 'לפידות' },
  { en: 'Laqiya', he: 'לקיה' },

  // מ
  { en: 'Madama', he: 'מאדמא' },
  { en: 'Maor', he: 'מאור' },
  { en: 'Meir Shfeya', he: 'מאיר שפיה' },
  { en: 'Masura', he: 'מאסורה' },
  { en: 'Maqura', he: 'מאקורה' },
  { en: 'Mevo Beitar', he: 'מבוא ביתר' },
  { en: 'Mevo Dotan', he: 'מבוא דותן' },
  { en: 'Mevo Horon', he: 'מבוא חורון' },
  { en: 'Mevo Hama', he: 'מבוא חמה' },
  { en: 'Mevo Modiin', he: 'מבוא מודיעים' },
  { en: 'Mevoat Yam', he: 'מבואות ים' },
  { en: 'Mabuim', he: 'מבועים' },
  { en: 'Mivtachim', he: 'מבטחים' },
  { en: 'Mavkiim', he: 'מבקיעים' },
  { en: 'Mevaseret Tzion', he: 'מבשרת ציון' },
  { en: 'Maghazi', he: 'מגאזי' },
  { en: 'Mughar', he: 'מגאר' },
  { en: 'Meged', he: 'מגד' },
  { en: 'Majd al-Krum', he: 'מגד אל-כרום' },
  { en: 'Megadim', he: 'מגדים' },
  { en: 'Migdal', he: 'מגדל' },
  { en: 'Migdal Bnei Pa', he: 'מגדל בני פא' },
  { en: 'Migdal HaEmek', he: 'מגדל העמק' },
  { en: 'Migdal Oz', he: 'מגדל עוז' },
  { en: 'Majdal Shams', he: 'מגדל שמס' },
  { en: 'Migdalim', he: 'מגדלים' },
  { en: 'Megiddo', he: 'מגידו' },
  { en: 'Mughayir Jenin', he: 'מגיר ג\'נין' },
  { en: 'Mughayir Ramallah', he: 'מגיר רמאללה' },
  { en: 'Megal', he: 'מגל' },
  { en: 'Magen', he: 'מגן' },
  { en: 'Magen Shaul', he: 'מגן שאול' },
  { en: 'Magshimim', he: 'מגשימים' },
  { en: 'Midya', he: 'מדיה' },
  { en: 'Madfuna', he: 'מדפונה' },
  { en: 'Midrach Oz', he: 'מדרך עוז' },
  { en: 'Midreshet Ben Gurion', he: 'מדרשת בן גוריון' },
  { en: 'Midreshet Ruppin', he: 'מדרשת רופין' },
  { en: 'Modiin-Maccabim-Reut', he: 'מודיעין-מכבים-רעות' },
  { en: 'Modiin Illit', he: 'מודיעין עילית' },
  { en: 'Molada', he: 'מולדה' },
  { en: 'Moledet', he: 'מולדת' },
  { en: 'Motza Illit', he: 'מוצא עילית' },
  { en: 'Motza Tachtit', he: 'מוצא תחתית' },
  { en: 'Mutsmuts', he: 'מוצמוץ' },
  { en: 'Muqeibila', he: 'מוקייבלה' },
  { en: 'Morag', he: 'מורג' },
  { en: 'Moran', he: 'מורן' },
  { en: 'Moreshet', he: 'מורשת' },
  { en: 'Moshav Elyav', he: 'מושב אליאב' },
  { en: 'Mazar', he: 'מזאר' },
  { en: 'Mazaria al-Nu', he: 'מזארע אל נו' },
  { en: 'Mazor', he: 'מזור' },
  { en: 'Mazkeret Batya', he: 'מזכרת בתיה' },
  { en: 'Mizra', he: 'מזרע' },
  { en: 'Mizraa', he: 'מזרעה' },
  { en: 'Mizraa al-Qib', he: 'מזרעה אל קב' },
  { en: 'Mizraa al-Shar', he: 'מזרעה אל שר' },
  { en: 'Mechola', he: 'מחולה' },
  { en: 'Machim al-Far', he: 'מחים אל פאר' },
  { en: 'Machim Kalandiya', he: 'מחים קלנדיה' },
  { en: 'Machmas', he: 'מחמאס' },
  { en: 'Machane Givat Ch', he: 'מחנה גבעת ח' },
  { en: 'Machane Hila', he: 'מחנה הילה' },
  { en: 'Machane Tali', he: 'מחנה טלי' },
  { en: 'Machane Yabor', he: 'מחנה יבור' },
  { en: 'Machane Yehudit', he: 'מחנה יהודית' },
  { en: 'Machane Yocheved', he: 'מחנה יוכבד' },
  { en: 'Machane Yafa', he: 'מחנה יפה' },
  { en: 'Machane Yatir', he: 'מחנה יתיר' },
  { en: 'Machane Miriam', he: 'מחנה מרים' },
  { en: 'Machane Adi', he: 'מחנה עדי' },
  { en: 'Machane Tel Nof', he: 'מחנה תל נוף' },
  { en: 'Machanayim', he: 'מחניים' },
  { en: 'Machseya', he: 'מחסיה' },
  { en: 'Machshiv', he: 'מחשיב' },
  { en: 'Metula', he: 'מטולה' },
  { en: 'Mata', he: 'מטע' },
  { en: 'Mei Ami', he: 'מי עמי' },
  { en: 'Midan', he: 'מידאן' },
  { en: 'Meitav', he: 'מיטב' },
  { en: 'Meiser', he: 'מייסר' },
  { en: 'Meitzar', he: 'מיצר' },
  { en: 'Merav', he: 'מירב' },
  { en: 'Meiron', he: 'מירון' },
  { en: 'Mishor', he: 'מישר' },
  { en: 'Mitla', he: 'מיתלה' },
  { en: 'Meithalon', he: 'מיתלון' },
  { en: 'Meitar', he: 'מיתר' },
  { en: 'Maccabim', he: 'מכבים' },
  { en: 'Makhora', he: 'מכורה' },
  { en: 'Makchul', he: 'מכחול' },
  { en: 'Michmoret', he: 'מכמורת' },
  { en: 'Michmanim', he: 'מכמנים' },
  { en: 'Maksura', he: 'מכסורה' },
  { en: 'Makr', he: 'מכר' },
  { en: 'Mala', he: 'מלאה' },
  { en: 'Melilot', he: 'מלילות' },
  { en: 'Malkiya', he: 'מלכיה' },
  { en: 'Malkishua', he: 'מלכישוע' },
  { en: 'Mnabtech', he: 'מנבטח' },
  { en: 'Menucha', he: 'מנוחה' },
  { en: 'Manof', he: 'מנוף' },
  { en: 'Manot', he: 'מנות' },
  { en: 'Menachamiya', he: 'מנחמיה' },
  { en: 'Manara', he: 'מנרה' },
  { en: 'Manshit Zbada', he: 'מנשית זבדה' },
  { en: 'Masad', he: 'מסד' },
  { en: 'Masada', he: 'מסדה' },
  { en: 'Mascha', he: 'מסחה' },
  { en: 'Mesilot', he: 'מסילות' },
  { en: 'Mesilat Tzion', he: 'מסילת ציון' },
  { en: 'Maslul', he: 'מסלול' },
  { en: 'Masliya', he: 'מסליה' },
  { en: 'Masada', he: 'מסעדה' },
  { en: 'Masoudin al-Azazme', he: 'מסעודין אל-עזאזמה' },
  { en: 'Maawiya', he: 'מעאויה' },
  { en: 'Maavarot', he: 'מעברות' },
  { en: 'Maagalim', he: 'מעגלים' },
  { en: 'Maagan', he: 'מעגן' },
  { en: 'Maagan Michael', he: 'מעגן מיכאל' },
  { en: 'Maoz Chaim', he: 'מעוז חיים' },
  { en: 'Maon', he: 'מעון' },
  { en: 'Meona', he: 'מעונה' },
  { en: 'Maof', he: 'מעוף' },
  { en: 'Maalya', he: 'מעיליא' },
  { en: 'Maayan Baruch', he: 'מעין ברוך' },
  { en: 'Maayan Tzvi', he: 'מעין צבי' },
  { en: 'Maale Adumim', he: 'מעלה אדומים' },
  { en: 'Maale Efraim', he: 'מעלה אפרים' },
  { en: 'Maale Gilboa', he: 'מעלה גלבוע' },
  { en: 'Maale Gamla', he: 'מעלה גמלא' },
  { en: 'Maale HaChamisha', he: 'מעלה החמישה' },
  { en: 'Maale Levona', he: 'מעלה לבונה' },
  { en: 'Maale Michmash', he: 'מעלה מכמש' },
  { en: 'Maale Iron', he: 'מעלה עירון' },
  { en: 'Maale Amos', he: 'מעלה עמוס' },
  { en: 'Maale Shomron', he: 'מעלה שומרון' },
  { en: 'Maalot-Tarshicha', he: 'מעלות-תרשיחא' },
  { en: 'Maani Abu Ha', he: 'מעני אבו חא' },
  { en: 'Maanit', he: 'מענית' },
  { en: 'Maaskar al-Ar', he: 'מעסכר אל ער' },
  { en: 'Maas', he: 'מעש' },
  { en: 'Mefalsim', he: 'מפלסים' },
  { en: 'Matzbach', he: 'מצבח' },
  { en: 'Metzadot Yehuda', he: 'מצדות יהודה' },
  { en: 'Matzuva', he: 'מצובה' },
  { en: 'Matzliach', he: 'מצליח' },
  { en: 'Mitzpe', he: 'מצפה' },
  { en: 'Mitzpe Aviv', he: 'מצפה אבי"ב' },
  { en: 'Mitzpe Ilan', he: 'מצפה אילן' },
  { en: 'Mitzpe Yericho', he: 'מצפה יריחו' },
  { en: 'Mitzpe Netofa', he: 'מצפה נטופה' },
  { en: 'Mitzpe Ramon', he: 'מצפה רמון' },
  { en: 'Mitzpe Shalem', he: 'מצפה שלם' },
  { en: 'Mitzpak', he: 'מצפק' },
  { en: 'Mitzar', he: 'מצר' },
  { en: 'Maqdaba (Agila)', he: 'מקדבה (עגילה)' },
  { en: 'Mikveh Israel', he: 'מקווה ישראל' },
  { en: 'Marach al-Baqar', he: 'מראח אל בקר' },
  { en: 'Marach Rabah', he: 'מראח רבאח' },
  { en: 'Marj Naaja', he: 'מרג נעגה' },
  { en: 'Marga', he: 'מרגה' },
  { en: 'Margaliot', he: 'מרגליות' },
  { en: 'Marda', he: 'מרדה' },
  { en: 'Merom Golan', he: 'מרום גולן' },
  { en: 'Merchav Am', he: 'מרחב עם' },
  { en: 'Merhavya (Moshav)', he: 'מרחביה (מושב)' },
  { en: 'Merhavya (Kibbutz)', he: 'מרחביה (קיבוץ)' },
  { en: 'Marka', he: 'מרכה' },
  { en: 'Merkaz Shapira', he: 'מרכז שפירא' },
  { en: 'Mashabe Sadeh', he: 'משאבי שדה' },
  { en: 'Mashaich Sadiya', he: 'משאיח סעדיה' },
  { en: 'Misgav Dov', he: 'משגב דב' },
  { en: 'Misgav Am', he: 'משגב עם' },
  { en: 'Mashad', he: 'משהד' },
  { en: 'Mashua', he: 'משואה' },
  { en: 'Mashuot Yitzchak', he: 'משואות יצחק' },
  { en: 'Mashirfa', he: 'משירפה' },
  { en: 'Mishkiyot', he: 'משכיות' },
  { en: 'Mishmar Ayalon', he: 'משמר איילון' },
  { en: 'Mishmar David', he: 'משמר דוד' },
  { en: 'Mishmar HaYarden', he: 'משמר הירדן' },
  { en: 'Mishmar HaNegev', he: 'משמר הנגב' },
  { en: 'Mishmar HaEmek', he: 'משמר העמק' },
  { en: 'Mishmar HaShiva', he: 'משמר השבעה' },
  { en: 'Mishmar HaSharon', he: 'משמר השרון' },
  { en: 'Mishmarot', he: 'משמרות' },
  { en: 'Mishmeret', he: 'משמרת' },
  { en: 'Mishaan', he: 'משען' },
  { en: 'Mashrua Musa', he: 'משרוע מוסא' },
  { en: 'Matmatni', he: 'מתמתני' },
  { en: 'Matan', he: 'מתן' },
  { en: 'Matat', he: 'מתת' },
  { en: 'Matityahu', he: 'מתתיהו' },

  // נ
  { en: 'Naot Golan', he: 'נאות גולן' },
  { en: 'Naot HaKikar', he: 'נאות הכיכר' },
  { en: 'Naot Mordechai', he: 'נאות מרדכי' },
  { en: 'Naot Smadar', he: 'נאות סמדר' },
  { en: 'Naura', he: 'נאעורה' },
  { en: 'Naqura', he: 'נאקורה' },
  { en: 'Nevatim', he: 'נבטים' },
  { en: 'Nabi Salih', he: 'נבי צאלח' },
  { en: 'Nabi Samuel', he: 'נבי צמויל' },
  { en: 'Neviot', he: 'נביעות' },
  { en: 'Nabaq', he: 'נבק' },
  { en: 'Negba', he: 'נגבה' },
  { en: 'Negohot', he: 'נגוהות' },
  { en: 'Negidat', he: 'נגידאת' },
  { en: 'Negila', he: 'נגילה' },
  { en: 'Nehora', he: 'נהורה' },
  { en: 'Nahalal', he: 'נהלל' },
  { en: 'Nahariya', he: 'נהריה' },
  { en: 'Nov', he: 'נוב' },
  { en: 'Nuba', he: 'נובא' },
  { en: 'Noga', he: 'נוגה' },
  { en: 'Neve', he: 'נוה' },
  { en: 'Neve Efraim', he: 'נוה אפרים' },
  { en: 'Neve Dekalim', he: 'נוה דקלים' },
  { en: 'Neve Avot', he: 'נווה אבות' },
  { en: 'Neve Or', he: 'נווה אור' },
  { en: 'Neve Ativ', he: 'נווה אטי"ב' },
  { en: 'Neve Ilan', he: 'נווה אילן' },
  { en: 'Neve Eitan', he: 'נווה איתן' },
  { en: 'Neve Daniel', he: 'נווה דניאל' },
  { en: 'Neve Zohar', he: 'נווה זוהר' },
  { en: 'Neve Ziv', he: 'נווה זיו' },
  { en: 'Neve Charif', he: 'נווה חריף' },
  { en: 'Neve Yam', he: 'נווה ים' },
  { en: 'Neve Yamin', he: 'נווה ימין' },
  { en: 'Neve Yaraq', he: 'נווה ירק' },
  { en: 'Neve Mivtach', he: 'נווה מבטח' },
  { en: 'Neve Michael', he: 'נווה מיכאל' },
  { en: 'Neve Shalom', he: 'נווה שלום' },
  { en: 'Nueima', he: 'נויעמה' },
  { en: 'Numis', he: 'נומיס' },
  { en: 'Noam', he: 'נועם' },
  { en: 'Nof Ayalon', he: 'נוף איילון' },
  { en: 'Nofim', he: 'נופים' },
  { en: 'Nofit', he: 'נופית' },
  { en: 'Nofech', he: 'נופך' },
  { en: 'Nokdim', he: 'נוקדים' },
  { en: 'Nur al-Shams', he: 'נור אל שמס' },
  { en: 'Nordiya', he: 'נורדיה' },
  { en: 'Nurit', he: 'נורית' },
  { en: 'Nazla al-Gharb', he: 'נזלה אל גרב' },
  { en: 'Nazla al-Wusta', he: 'נזלה אל וסט' },
  { en: 'Nazla al-Sharq', he: 'נזלה אל שרק' },
  { en: 'Nazlat Abu Na', he: 'נזלת אבו נא' },
  { en: 'Nazlat Zeid', he: 'נזלת זיד' },
  { en: 'Nazlat Issa', he: 'נזלת עיסא' },
  { en: 'Nahalin', he: 'נחאלין' },
  { en: 'Nechusha', he: 'נחושה' },
  { en: 'Nachal Adora', he: 'נחל אדורה' },
  { en: 'Nachal Elisha', he: 'נחל אלישע' },
  { en: 'Nachal Amti', he: 'נחל אמתי' },
  { en: 'Nachal Bitronot', he: 'נחל בתרונות' },
  { en: 'Nachal Givot', he: 'נחל גבעות' },
  { en: 'Nachal Ganat', he: 'נחל גנת' },
  { en: 'Nachal Yaalon', he: 'נחל יעלון' },
  { en: 'Nachal Mul Nevo', he: 'נחל מול נבו' },
  { en: 'Nachal Maruva', he: 'נחל מרוה' },
  { en: 'Nachal Nechushtan', he: 'נחל נחושתן' },
  { en: 'Nachal Nimrod', he: 'נחל נמרוד' },
  { en: 'Nachal Netzarim', he: 'נחל נצרים' },
  { en: 'Nachal Oz', he: 'נחל עוז' },
  { en: 'Nachal Irit', he: 'נחל עירית' },
  { en: 'Nachal Tzoref', he: 'נחל צורף' },
  { en: 'Nachal Tzori', he: 'נחל צרי' },
  { en: 'Nachal Shion', he: 'נחל שיאון' },
  { en: 'Nachal (Hafga)', he: 'נחל (חפגה)' },
  { en: 'Nachala', he: 'נחלה' },
  { en: 'Nachliel', he: 'נחליאל' },
  { en: 'Nechalim', he: 'נחלים' },
  { en: 'Nachalat Yehuda', he: 'נחלת יהודה' },
  { en: 'Necham', he: 'נחם' },
  { en: 'Nachf', he: 'נחף' },
  { en: 'Nachsholim', he: 'נחשולים' },
  { en: 'Nachshon', he: 'נחשון' },
  { en: 'Nachshonim', he: 'נחשונים' },
  { en: 'Netua', he: 'נטועה' },
  { en: 'Natur', he: 'נטור' },
  { en: 'Netaim', he: 'נטעים' },
  { en: 'Nataf', he: 'נטף' },
  { en: 'Nein', he: 'ניין' },
  { en: 'Nili', he: 'ניל"י' },
  { en: 'Nisanit', he: 'ניסנית' },
  { en: 'Nitzan', he: 'ניצן' },
  { en: 'Nitzan B', he: 'ניצן ב' },
  { en: 'Nitzana (Chinuch Community)', he: 'ניצנה (קהילת חינוך)' },
  { en: 'Nitzanei Sinai', he: 'ניצני סיני' },
  { en: 'Nitzanei Oz', he: 'ניצני עוז' },
  { en: 'Nitzanim', he: 'ניצנים' },
  { en: 'Nir Eliyahu', he: 'ניר אליהו' },
  { en: 'Nir Banim', he: 'ניר בנים' },
  { en: 'Nir Galim', he: 'ניר גלים' },
  { en: 'Nir David (Tel Amal)', he: 'ניר דוד (תל עמל)' },
  { en: 'Nir Chen', he: 'ניר ח"ן' },
  { en: 'Nir Yafe', he: 'ניר יפה' },
  { en: 'Nir Yitzchak', he: 'ניר יצחק' },
  { en: 'Nir Israel', he: 'ניר ישראל' },
  { en: 'Nir Moshe', he: 'ניר משה' },
  { en: 'Nir Oz', he: 'ניר עוז' },
  { en: 'Nir Am', he: 'ניר עם' },
  { en: 'Nir Etzion', he: 'ניר עציון' },
  { en: 'Nir Akiva', he: 'ניר עקיבא' },
  { en: 'Nir Tzvi', he: 'ניר צבי' },
  { en: 'Nirim', he: 'נירים' },
  { en: 'Nirit', he: 'נירית' },
  { en: 'Niran', he: 'נירן' },
  { en: 'Ben Gurion Airport', he: 'נמל תעופה בן גוריון' },
  { en: 'Nes Harim', he: 'נס הרים' },
  { en: 'Nes Amim', he: 'נס עמים' },
  { en: 'Ness Tziona', he: 'נס ציונה' },
  { en: 'Neurim', he: 'נעורים' },
  { en: 'Naale', he: 'נעלה' },
  { en: 'Nilin', he: 'נעלין' },
  { en: 'Naama', he: 'נעמ"ה' },
  { en: 'Naan', he: 'נען' },
  { en: 'Natsatsra (Tribe)', he: 'נצאצרה (שבט)' },
  { en: 'Natsariya', he: 'נצאריה' },
  { en: 'Natsirat', he: 'נציראת' },
  { en: 'Netsaf Gvil', he: 'נצף גביל' },
  { en: 'Netzer Chazani', he: 'נצר חזני' },
  { en: 'Netzer Sereni', he: 'נצר סרני' },
  { en: 'Nazareth', he: 'נצרת' },
  { en: 'Nazareth Illit', he: 'נצרת עילית' },
  { en: 'Naqa Shaabani', he: 'נקא שעבאני' },
  { en: 'Nesher', he: 'נשר' },
  { en: 'Netiv HaGdud', he: 'נתיב הגדוד' },
  { en: 'Netiv HaLamed-Heh', he: 'נתיב הל"ה' },
  { en: 'Netiv HaAsara', he: 'נתיב העשרה' },
  { en: 'Netiv HaShayara', he: 'נתיב השיירה' },
  { en: 'Netivot', he: 'נתיבות' },
  { en: 'Netanya', he: 'נתניה' },

  // ס
  { en: 'Sagur', he: 'סאגור' },
  { en: 'Sawiya', he: 'סאויה' },
  { en: 'Salem', he: 'סאלם' },
  { en: 'Sasa', he: 'סאסא' },
  { en: 'Savyon', he: 'סביון' },
  { en: 'Sebastia', he: 'סבסטיה' },
  { en: 'Segula', he: 'סגולה' },
  { en: 'Sdom', he: 'סדום' },
  { en: 'Sawahira', he: 'סואחרה' },
  { en: 'Sawaid (Hamriya)', he: 'סואעד (חמרייה)' },
  { en: 'Sawaid (Kamana) (Tribe)', he: 'סואעד (כמאנה) (שבט)' },
  { en: 'Sulam', he: 'סולם' },
  { en: 'Susya', he: 'סוסיה' },
  { en: 'Sufa', he: 'סופה' },
  { en: 'Sakhnin', he: 'סחנין' },
  { en: 'Sayyid (Tribe)', he: 'סייד (שבט)' },
  { en: 'Sayfa', he: 'סייפה' },
  { en: 'Silat al-Daher', he: 'סילת אל דאה' },
  { en: 'Silat al-Harithiya', he: 'סילת אל חאר' },
  { en: 'Siris', he: 'סיריס' },
  { en: 'Silwad', he: 'סלואד' },
  { en: 'Salmana', he: 'סלמאנה' },
  { en: 'Salama', he: 'סלמה' },
  { en: 'Salait', he: 'סלעית' },
  { en: 'Salfit', he: 'סלפית' },
  { en: 'Samua', he: 'סמוע' },
  { en: 'Samar', he: 'סמר' },
  { en: 'Sinjil', he: 'סנג\'ל' },
  { en: 'Santa Katarina', he: 'סנטה קטרינה' },
  { en: 'Saniriya', he: 'סניריה' },
  { en: 'Sansana', he: 'סנסנה' },
  { en: 'Saad', he: 'סעד' },
  { en: 'Sair', he: 'סעיר' },
  { en: 'Saar', he: 'סער' },
  { en: 'Saffarin', he: 'ספארין' },
  { en: 'Sapir', he: 'ספיר' },
  { en: 'Sarda', he: 'סרדה' },
  { en: 'Sitriya', he: 'סתריה' },

  // ע
  { en: 'Abud', he: 'עאבוד' },
  { en: 'Anin', he: 'עאנין' },
  { en: 'Ara', he: 'עארה' },
  { en: 'Arura', he: 'עארורה' },
  { en: 'Abasan al-Kabira', he: 'עבאסן אל כב' },
  { en: 'Abasan al-Saghira', he: 'עבאסן אל צע' },
  { en: 'Avda', he: 'עבדה' },
  { en: 'Avdon', he: 'עבדון' },
  { en: 'Abuyin', he: 'עבוין' },
  { en: 'Ubaydiya', he: 'עבידיה' },
  { en: 'Evron', he: 'עברון' },
  { en: 'Aja', he: 'עג\'ה' },
  { en: 'Agul', he: 'עגול' },
  { en: 'Agur', he: 'עגור' },
  { en: 'Agar', he: 'עגר' },
  { en: 'Adi', he: 'עדי' },
  { en: 'Adanim', he: 'עדנים' },
  { en: 'Uza', he: 'עוזה' },
  { en: 'Uzair', he: 'עוזייר' },
  { en: 'Olesh', he: 'עולש' },
  { en: 'Omer', he: 'עומר' },
  { en: 'Ofer', he: 'עופר' },
  { en: 'Ofra', he: 'עופרה' },
  { en: 'Ofrim', he: 'עופרים' },
  { en: 'Otzem', he: 'עוצם' },
  { en: 'Uqbi (Banu Uqba)', he: 'עוקבי (בנו עוקבה)' },
  { en: 'Urif', he: 'עוריף' },
  { en: 'Urta', he: 'עורתא' },
  { en: 'Izbat al-Drub', he: 'עזבת א דרוב' },
  { en: 'Gaza', he: 'עזה' },
  { en: 'Azuz', he: 'עזוז' },
  { en: 'Azzun', he: 'עזון' },
  { en: 'Azzun Atma', he: 'עזון עתמה' },
  { en: 'Azmut', he: 'עזמוט' },
  { en: 'Ezer', he: 'עזר' },
  { en: 'Azriel', he: 'עזריאל' },
  { en: 'Azarya', he: 'עזריה' },
  { en: 'Azrikam', he: 'עזריקם' },
  { en: 'Atauna (Tribe)', he: 'עטאוונה (שבט)' },
  { en: 'Atatera', he: 'עטאטרה' },
  { en: 'Atara Jenin', he: 'עטארה ג\'נין' },
  { en: 'Atara Ramallah', he: 'עטארה רמאלל' },
  { en: 'Ateret', he: 'עטרת' },
  { en: 'Idan', he: 'עידן' },
  { en: 'Al-Eizariya', he: 'עיזריה' },
  { en: 'Eilaboun', he: 'עיילבון' },
  { en: 'Ayanot', he: 'עיינות' },
  { en: 'Ilut', he: 'עילוט' },
  { en: 'Ein al-Sahla', he: 'עין א סהלה' },
  { en: 'Ein Ayub', he: 'עין איוב' },
  { en: 'Ein Ayala', he: 'עין איילה' },
  { en: 'Ein al-Asad', he: 'עין אל-אסד' },
  { en: 'Ein al-Ahdar', he: 'עין אל אחדר' },
  { en: 'Ein al-Bayda', he: 'עין אל בידא' },
  { en: 'Ein al-Shalta', he: 'עין אל שלטא' },
  { en: 'Ein Gev', he: 'עין גב' },
  { en: 'Ein Gedi', he: 'עין גדי' },
  { en: 'Ein Dor', he: 'עין דור' },
  { en: 'Ein Darvish', he: 'עין דרויש' },
  { en: 'Ein HaBesor', he: 'עין הבשור' },
  { en: 'Ein Hod', he: 'עין הוד' },
  { en: 'Ein HaChoresh', he: 'עין החורש' },
  { en: 'Ein HaMifratz', he: 'עין המפרץ' },
  { en: 'Ein HaNetziv', he: 'עין הנצי"ב' },
  { en: 'Ein HaEmek', he: 'עין העמק' },
  { en: 'Ein HaShofet', he: 'עין השופט' },
  { en: 'Ein HaShlosha', he: 'עין השלושה' },
  { en: 'Ein Vered', he: 'עין ורד' },
  { en: 'Ein Zivan', he: 'עין זיוון' },
  { en: 'Ein Khod', he: 'עין חוד' },
  { en: 'Ein Chatzeva', he: 'עין חצבה' },
  { en: 'Ein Charod (Ichud)', he: 'עין חרוד (איחוד)' },
  { en: 'Ein Charod (Meuchad)', he: 'עין חרוד (מאוחד)' },
  { en: 'Ein Yabrud', he: 'עין יברוד' },
  { en: 'Ein Yahav', he: 'עין יהב' },
  { en: 'Ein Yaakov', he: 'עין יעקב' },
  { en: 'Ein Kerem Agricultural School', he: 'עין כרם-בי"ס חקלאי' },
  { en: 'Ein Carmel', he: 'עין כרמל' },
  { en: 'Ein Mahel', he: 'עין מאהל' },
  { en: 'Ein Nakuba', he: 'עין נקובא' },
  { en: 'Ein Sinya', he: 'עין סיניא' },
  { en: 'Ein Iron', he: 'עין עירון' },
  { en: 'Ein Arik', he: 'עין עריכ' },
  { en: 'Ein Tzadar', he: 'עין צדר' },
  { en: 'Ein Tzurim', he: 'עין צורים' },
  { en: 'Ein Qidkhat', he: 'עין קידכאת' },
  { en: 'Ein Qiniya', he: 'עין קיניא' },
  { en: 'Ein Qanya', he: 'עין קנייא' },
  { en: 'Ein Rafa', he: 'עין ראפה' },
  { en: 'Ein Shemer', he: 'עין שמר' },
  { en: 'Ein Sarid', he: 'עין שריד' },
  { en: 'Ein Tamar', he: 'עין תמר' },
  { en: 'Einabus', he: 'עינאבוס' },
  { en: 'Einat', he: 'עינת' },
  { en: 'Ir Ovot', he: 'עיר אובות' },
  { en: 'Akko', he: 'עכו' },
  { en: 'Alar', he: 'עלאר' },
  { en: 'Alumim', he: 'עלומים' },
  { en: 'Eli', he: 'עלי' },
  { en: 'Eli Zahav', he: 'עלי זהב' },
  { en: 'Alma', he: 'עלמה' },
  { en: 'Almon', he: 'עלמון' },
  { en: 'Alqa', he: 'עלקה' },
  { en: 'Amuka', he: 'עמוקה' },
  { en: 'Amur', he: 'עמור' },
  { en: 'Amuriya', he: 'עמוריה' },
  { en: 'Aminadav', he: 'עמינדב' },
  { en: 'Amiad', he: 'עמיעד' },
  { en: 'Amioz', he: 'עמיעוז' },
  { en: 'Amikam', he: 'עמיקם' },
  { en: 'Amir', he: 'עמיר' },
  { en: 'Immanuel', he: 'עמנואל' },
  { en: 'Emek Chefer', he: 'עמק חפר' },
  { en: 'Amka', he: 'עמקה' },
  { en: 'Anab al-Saghir', he: 'ענאב אל צגי' },
  { en: 'Anata', he: 'ענאתא' },
  { en: 'Inab', he: 'ענב' },
  { en: 'Anabta', he: 'ענבתא' },
  { en: 'Anza', he: 'ענזה' },
  { en: 'Asakira', he: 'עסאכרה' },
  { en: 'Askar', he: 'עסכר' },
  { en: 'Isfiya', he: 'עספיא' },
  { en: 'Afula', he: 'עפולה' },
  { en: 'Etz Efraim', he: 'עץ אפרים' },
  { en: 'Asira al-Qibliya', he: 'עצירה אל קב' },
  { en: 'Asira al-Shamaliya', he: 'עצירה אלשמא' },
  { en: 'Atzmon Segev', he: 'עצמון שגב' },
  { en: 'Aqaba', he: 'עקאבה' },
  { en: 'Aqabat Jabr', he: 'עקבת גבר' },
  { en: 'Aqraba', he: 'עקרבה' },
  { en: 'Arraba', he: 'עראבה' },
  { en: 'Aramsha', he: 'עראמשה' },
  { en: 'Aramsha Tribe', he: 'עראמשה שבט' },
  { en: 'Arana', he: 'עראנה' },
  { en: 'Iraq Burin', he: 'עראק בורין' },
  { en: 'Arab Abu Tsib', he: 'ערב אבו ציב' },
  { en: 'Arab al-Hasin', he: 'ערב אל חסינ' },
  { en: 'Arab al-Naim', he: 'ערב אל נעים' },
  { en: 'Arbuna', he: 'ערבונה' },
  { en: 'Arad', he: 'ערד' },
  { en: 'Arugot', he: 'ערוגות' },
  { en: 'Arara', he: 'ערערה' },
  { en: 'Arara BaNegev', he: 'ערערה-בנגב' },
  { en: 'Arqa', he: 'ערקה' },
  { en: 'Aseret', he: 'עשרת' },
  { en: 'Attil', he: 'עתיל' },
  { en: 'Atlit', he: 'עתלית' },
  { en: 'Otniel', he: 'עתניאל' },

  // פ
  { en: 'Paran', he: 'פארן' },
  { en: 'Peat Sadeh', he: 'פאת שדה' },
  { en: 'Peduel', he: 'פדואל' },
  { en: 'Peduyim', he: 'פדויים' },
  { en: 'Pedaya', he: 'פדיה' },
  { en: 'Fujiya', he: 'פוגיה' },
  { en: 'Fawwar', he: 'פוור' },
  { en: 'Poriya - Kfar Avoda', he: 'פוריה - כפר עבודה' },
  { en: 'Poriya - Neve Oved', he: 'פוריה - נווה עובד' },
  { en: 'Poriya Illit', he: 'פוריה עילית' },
  { en: 'Fureidis', he: 'פוריידיס' },
  { en: 'Porat', he: 'פורת' },
  { en: 'Fachma', he: 'פחמה' },
  { en: 'Patish', he: 'פטיש' },
  { en: 'Firan', he: 'פיראן' },
  { en: 'Falama', he: 'פלאמה' },
  { en: 'Pelech', he: 'פלך' },
  { en: 'Palmachim', he: 'פלמחים' },
  { en: 'Funduq', he: 'פנדק' },
  { en: 'Fundukumiya', he: 'פנדקומיה' },
  { en: 'Pnei Chever', he: 'פני חבר' },
  { en: 'Psagot', he: 'פסגות' },
  { en: 'Fassouta', he: 'פסוטה' },
  { en: 'Paamei Tashaz', he: 'פעמי תש"ז' },
  { en: 'Fatsael', he: 'פצאיל' },
  { en: 'Fatsal', he: 'פצאל' },
  { en: 'Pekiin', he: 'פקועה' },
  { en: 'Pekiin (Buqeia)', he: 'פקיעין (בוקייעה)' },
  { en: 'Pekiin Chadasha', he: 'פקיעין חדשה' },
  { en: 'Pardes Chana-Karkur', he: 'פרדס חנה-כרכור' },
  { en: 'Pardesiya', he: 'פרדסיה' },
  { en: 'Parod', he: 'פרוד' },
  { en: 'Farush Beit Dajan', he: 'פרוש בית דג' },
  { en: 'Prazon', he: 'פרזון' },
  { en: 'Parcha', he: 'פרחה' },
  { en: 'Pri Gan', he: 'פרי גן' },
  { en: 'Faranga', he: 'פרנגה' },
  { en: 'Faraa al-Jif', he: 'פרעה אל גיפ' },
  { en: 'Faraun', he: 'פרעון' },
  { en: 'Farata', he: 'פרעתה' },
  { en: 'Petach Tikva', he: 'פתח תקווה' },
  { en: 'Patchiya', he: 'פתחיה' },

  // צ
  { en: 'Tzalim', he: 'צאלים' },
  { en: 'Tzanur', he: 'צאנור' },
  { en: 'Tzivya', he: 'צביה' },
  { en: 'Tzvaon', he: 'צבעון' },
  { en: 'Tzova', he: 'צובה' },
  { en: 'Tzochar', he: 'צוחר' },
  { en: 'Tzofiya', he: 'צופיה' },
  { en: 'Tzofim', he: 'צופים' },
  { en: 'Tzofit', he: 'צופית' },
  { en: 'Tzofar', he: 'צופר' },
  { en: 'Tzukei Yam', he: 'צוקי ים' },
  { en: 'Tzukim', he: 'צוקים' },
  { en: 'Tzur Hadassa', he: 'צור הדסה' },
  { en: 'Tzur Yigal', he: 'צור יגאל' },
  { en: 'Tzur Yitzchak', he: 'צור יצחק' },
  { en: 'Tzur Moshe', he: 'צור משה' },
  { en: 'Tzur Natan', he: 'צור נתן' },
  { en: 'Tzuriel', he: 'צוריאל' },
  { en: 'Tzurif', he: 'צוריף' },
  { en: 'Tzurit', he: 'צורית' },
  { en: 'Tzoran', he: 'צורן' },
  { en: 'Tzida', he: 'צידא' },
  { en: 'Tzipori', he: 'ציפורי' },
  { en: 'Tzir', he: 'ציר' },
  { en: 'Tzalfon', he: 'צלפון' },
  { en: 'Tzandalah', he: 'צנדלה' },
  { en: 'Tzafa', he: 'צפא' },
  { en: 'Tzafriya', he: 'צפריה' },
  { en: 'Tzafririm', he: 'צפרירים' },
  { en: 'Tzfat', he: 'צפת' },
  { en: 'Tzara', he: 'צרה' },
  { en: 'Tzrufa', he: 'צרופה' },
  { en: 'Tzarta', he: 'צרטא' },
  { en: 'Tzora', he: 'צרעה' },

  // ק
  { en: 'KM 45', he: 'ק.מ. 45' },
  { en: 'Qabatiya', he: 'קבאטיה' },
  { en: 'Qabba', he: 'קבה' },
  { en: 'Kabuaa (Tribe)', he: 'קבועה (שבט)' },
  { en: 'Kvutzat Yavne', he: 'קבוצת יבנה' },
  { en: 'Qibya', he: 'קביא' },
  { en: 'Qabiba', he: 'קביבה' },
  { en: 'Qabalan', he: 'קבלאן' },
  { en: 'Qabr Amir', he: 'קבר עמיר' },
  { en: 'Kedumim', he: 'קדומים' },
  { en: 'Kadima-Tzoran', he: 'קדימה-צורן' },
  { en: 'Kadma', he: 'קדמה' },
  { en: 'Kidmat Tzvi', he: 'קדמת צבי' },
  { en: 'Kedar', he: 'קדר' },
  { en: 'Kidron', he: 'קדרון' },
  { en: 'Kedraim', he: 'קדרים' },
  { en: 'Kudeirat al-Sane (Tribe)', he: 'קודייראת א-צאנע (שבט)' },
  { en: 'Kuwaain (Tribe)', he: 'קוואעין (שבט)' },
  { en: 'Komemiyut', he: 'קוממיות' },
  { en: 'Kutzima', he: 'קוצימה' },
  { en: 'Kutzin', he: 'קוצין' },
  { en: 'Kornit', he: 'קורנית' },
  { en: 'Ketura', he: 'קטורה' },
  { en: 'Katif', he: 'קטיף' },
  { en: 'Katana', he: 'קטנה' },
  { en: 'Caesarea', he: 'קיסריה' },
  { en: 'Kira', he: 'קירה' },
  { en: 'Kilchim', he: 'קלחים' },
  { en: 'Kalya', he: 'קליה' },
  { en: 'Kalandia', he: 'קלנדיה' },
  { en: 'Kalansawa', he: 'קלנסווה' },
  { en: 'Kala', he: 'קלע' },
  { en: 'Qalqilya', he: 'קלקיליה' },
  { en: 'Qaffin', he: 'קפין' },
  { en: 'Katzir', he: 'קציר' },
  { en: 'Qatser al-Sir', he: 'קצר א-סר' },
  { en: 'Katzara', he: 'קצרה' },
  { en: 'Katzrin', he: 'קצרין' },
  { en: 'Karaot Bani Z', he: 'קראות בני ז' },
  { en: 'Karaot Bani H', he: 'קראות בני ח' },
  { en: 'Karara', he: 'קרארה' },
  { en: 'Krayot', he: 'קריות' },
  { en: 'Kiryat Ono', he: 'קרית אונו' },
  { en: 'Kiryat Arba', he: 'קרית ארבע' },
  { en: 'Kiryat Ata', he: 'קרית אתא' },
  { en: 'Kiryat Bialik', he: 'קרית ביאליק' },
  { en: 'Kiryat Gat', he: 'קרית גת' },
  { en: 'Kiryat Chaim', he: 'קרית חיים' },
  { en: 'Kiryat Tivon', he: 'קרית טבעון' },
  { en: 'Kiryat Yam', he: 'קרית ים' },
  { en: 'Kiryat Yearim', he: 'קרית יערים' },
  { en: 'Kiryat Yearim (Institution)', he: 'קרית יערים (מוסד)' },
  { en: 'Kiryat Motzkin', he: 'קרית מוצקין' },
  { en: 'Kiryat Malachi', he: 'קרית מלאכי' },
  { en: 'Kiryat Netafim', he: 'קרית נטפים' },
  { en: 'Kiryat Anavim', he: 'קרית ענבים' },
  { en: 'Kiryat Ekron', he: 'קרית עקרון' },
  { en: 'Kiryat Shlomo', he: 'קרית שלמה' },
  { en: 'Kiryat Shmona', he: 'קרית שמונה' },
  { en: 'Karnei Shomron', he: 'קרני שומרון' },
  { en: 'Keshet', he: 'קשת' },

  // ר
  { en: 'Raba', he: 'ראבא' },
  { en: 'Rabud', he: 'ראבוד' },
  { en: 'Raam', he: 'ראם' },
  { en: 'Rame', he: 'ראמה' },
  { en: 'Ramin', he: 'ראמין' },
  { en: 'Ras', he: 'ראס' },
  { en: 'Ras al-Ein', he: 'ראס אל-עין' },
  { en: 'Ras al-Nakab', he: 'ראס אל נקב' },
  { en: 'Ras Karkar', he: 'ראס כרכר' },
  { en: 'Ras Nasrani', he: 'ראס נצראני' },
  { en: 'Ras Salem', he: 'ראס סאלם' },
  { en: 'Ras Snisel', he: 'ראס סניסל' },
  { en: 'Ras Ali', he: 'ראס עלי' },
  { en: 'Rafat Hebron', he: 'ראפאת חברון' },
  { en: 'Rafat Tulkarm', he: 'ראפאת טול כ' },
  { en: 'Rafat Ramallah', he: 'ראפאת רמאלל' },
  { en: 'Rosh HaAyin', he: 'ראש העין' },
  { en: 'Rosh Pina', he: 'ראש פינה' },
  { en: 'Rosh Tzurim', he: 'ראש צורים' },
  { en: 'Rishon LeTzion', he: 'ראשון לציון' },
  { en: 'Revava', he: 'רבבה' },
  { en: 'Revadim', he: 'רבדים' },
  { en: 'Revivim', he: 'רביבים' },
  { en: 'Revid', he: 'רביד' },
  { en: 'Rabaa Kolel B', he: 'רבעה כולל ב' },
  { en: 'Rigba', he: 'רגבה' },
  { en: 'Regavim', he: 'רגבים' },
  { en: 'Rahat', he: 'רהט' },
  { en: 'Rujib', he: 'רוגיב' },
  { en: 'Revacha', he: 'רווחה' },
  { en: 'Reviya', he: 'רוויה' },
  { en: 'Ruach Midbar', he: 'רוח מדבר' },
  { en: 'Ruchama', he: 'רוחמה' },
  { en: 'Rumana', he: 'רומאנה' },
  { en: 'Rumat Heib', he: 'רומת הייב' },
  { en: 'Roi', he: 'רועי' },
  { en: 'Rotem', he: 'רותם' },
  { en: 'Rechov', he: 'רחוב' },
  { en: 'Rechovot', he: 'רחובות' },
  { en: 'Rechima', he: 'רחימה' },
  { en: 'Reihaniya', he: 'ריחאניה' },
  { en: 'Richiya', he: 'ריחיה' },
  { en: 'Reichan', he: 'ריחן' },
  { en: 'Reine', he: 'ריינה' },
  { en: 'Rimonim', he: 'רימונים' },
  { en: 'Rinatya', he: 'רינתיה' },
  { en: 'Risan', he: 'ריסאן' },
  { en: 'Rakum', he: 'רכום' },
  { en: 'Rechasim', he: 'רכסים' },
  { en: 'Ram On', he: 'רם-און' },
  { en: 'Ramallah', he: 'רמאללה' },
  { en: 'Ramana', he: 'רמאנה' },
  { en: 'Ramon', he: 'רמון' },
  { en: 'Ramot', he: 'רמות' },
  { en: 'Ramot HaShavim', he: 'רמות השבים' },
  { en: 'Ramot Meir', he: 'רמות מאיר' },
  { en: 'Ramot Menashe', he: 'רמות מנשה' },
  { en: 'Ramot Naftali', he: 'רמות נפתלי' },
  { en: 'Ramle', he: 'רמלה' },
  { en: 'Ramsa', he: 'רמסה' },
  { en: 'Ramat Efal', he: 'רמת אפעל' },
  { en: 'Ramat Gan', he: 'רמת גן' },
  { en: 'Ramat David', he: 'רמת דוד' },
  { en: 'Ramat HaKovesh', he: 'רמת הכובש' },
  { en: 'Ramat HaShofet', he: 'רמת השופט' },
  { en: 'Ramat HaSharon', he: 'רמת השרון' },
  { en: 'Ramat Chovav', he: 'רמת חובב' },
  { en: 'Ramat Yochanan', he: 'רמת יוחנן' },
  { en: 'Ramat Yishai', he: 'רמת ישי' },
  { en: 'Ramat Magshimim', he: 'רמת מגשימים' },
  { en: 'Ramat Pinkas', he: 'רמת פנקס' },
  { en: 'Ramat Tzvi', he: 'רמת צבי' },
  { en: 'Ramat Raziel', he: 'רמת רזיאל' },
  { en: 'Ramat Rachel', he: 'רמת רחל' },
  { en: 'Ranen', he: 'רנן' },
  { en: 'Rantis', he: 'רנתיס' },
  { en: 'Reim', he: 'רעים' },
  { en: 'Raanana', he: 'רעננה' },
  { en: 'Rafida', he: 'רפידה' },
  { en: 'Rafidiya', he: 'רפידיה' },
  { en: 'Rafah', he: 'רפיח' },
  { en: 'Rafah City', he: 'רפיח העיר' },
  { en: 'Rafah Yam', he: 'רפיח ים' },
  { en: 'Rakefet', he: 'רקפת' },
  { en: 'Rishpon', he: 'רשפון' },
  { en: 'Reshafim', he: 'רשפים' },
  { en: 'Retamim', he: 'רתמים' },

  // ש
  { en: 'Sa-Nur', he: 'שא-נור' },
  { en: 'Shati', he: 'שאטי' },
  { en: 'Shear Yashuv', he: 'שאר ישוב' },
  { en: 'Shavei Tzion', he: 'שבי ציון' },
  { en: 'Shavei Shomron', he: 'שבי שומרון' },
  { en: 'Shibli-Umm al-Ghanam', he: 'שבלי - אום אל-גנם' },
  { en: 'Sheva Beerot', he: 'שבע בארות' },
  { en: 'Shabtin', he: 'שבתין' },
  { en: 'Segev-Shalom', he: 'שגב-שלום' },
  { en: 'Sdeh Ilan', he: 'שדה אילן' },
  { en: 'Sdeh Eliyahu', he: 'שדה אליהו' },
  { en: 'Sdeh Eliezer', he: 'שדה אליעזר' },
  { en: 'Sdeh Boker', he: 'שדה בוקר' },
  { en: 'Sdeh David', he: 'שדה דוד' },
  { en: 'Sdeh Warburg', he: 'שדה ורבורג' },
  { en: 'Sdeh Yoav', he: 'שדה יואב' },
  { en: 'Sdeh Yaakov', he: 'שדה יעקב' },
  { en: 'Sdeh Yitzchak', he: 'שדה יצחק' },
  { en: 'Sdeh Moshe', he: 'שדה משה' },
  { en: 'Sdeh Nachum', he: 'שדה נחום' },
  { en: 'Sdeh Nechemia', he: 'שדה נחמיה' },
  { en: 'Sdeh Nitzan', he: 'שדה ניצן' },
  { en: 'Sdeh Uziyahu', he: 'שדה עוזיהו' },
  { en: 'Sdeh Tzvi', he: 'שדה צבי' },
  { en: 'Sdot Yam', he: 'שדות ים' },
  { en: 'Sdot Micha', he: 'שדות מיכה' },
  { en: 'Sdei Avraham', he: 'שדי אברהם' },
  { en: 'Sdei Chemed', he: 'שדי חמד' },
  { en: 'Sdei Trumot', he: 'שדי תרומות' },
  { en: 'Sdema', he: 'שדמה' },
  { en: 'Sdemot Devora', he: 'שדמות דבורה' },
  { en: 'Sdemot Mechola', he: 'שדמות מחולה' },
  { en: 'Sderot', he: 'שדרות' },
  { en: 'Shuava', he: 'שואבה' },
  { en: 'Shuva', he: 'שובה' },
  { en: 'Shoval', he: 'שובל' },
  { en: 'Shoham', he: 'שוהם' },
  { en: 'Shweika', he: 'שויכה' },
  { en: 'Shukhat al-Tsufi', he: 'שוכת א צופי' },
  { en: 'Shomra', he: 'שומרה' },
  { en: 'Shomriya', he: 'שומריה' },
  { en: 'Shufa', he: 'שופה' },
  { en: 'Shokeda', he: 'שוקדה' },
  { en: 'Shoresh', he: 'שורש' },
  { en: 'Shorashim', he: 'שורשים' },
  { en: 'Shoshanat HaAmakim', he: 'שושנת העמקים' },
  { en: 'Shezor', he: 'שזור' },
  { en: 'Shachar', he: 'שחר' },
  { en: 'Shacharut', he: 'שחרות' },
  { en: 'Shibolim', he: 'שיבולים' },
  { en: 'Shiyuch', he: 'שיוח' },
  { en: 'Sheikh Ahmad', he: 'שיח אחמד' },
  { en: 'Sheikh Ahmad Al', he: 'שיח אחמד אל' },
  { en: 'Sheikh Brik', he: 'שיח בריכ' },
  { en: 'Sheikh Zuweid', he: 'שיח זויד' },
  { en: 'Sheikh Hashash', he: 'שיח חשש' },
  { en: 'Sheikh Suleiman', he: 'שיח סלימאן' },
  { en: 'Sheikh Said', he: 'שיח סעיד' },
  { en: 'Sheikh Ijlin', he: 'שיח עגלין' },
  { en: 'Sheikh Oud', he: 'שיח עוד' },
  { en: 'Shitim', he: 'שיטים' },
  { en: 'Sheikh Dannun', he: 'שייח דנון' },
  { en: 'Shilo', he: 'שילה' },
  { en: 'Shilat', he: 'שילת' },
  { en: 'Shechem', he: 'שכם' },
  { en: 'Shchaniya', he: 'שכניה' },
  { en: 'Shalaq VeJura', he: 'שלאק וג\'ורה' },
  { en: 'Shalva', he: 'שלווה' },
  { en: 'Shalva BaMidbar', he: 'שלווה במדבר' },
  { en: 'Shluchot', he: 'שלוחות' },
  { en: 'Shlomi', he: 'שלומי' },
  { en: 'Shlomit', he: 'שלומית' },
  { en: 'Shaliv', he: 'שליו' },
  { en: 'Shamir', he: 'שמיר' },
  { en: 'Shimaa', he: 'שמעה' },
  { en: 'Shamrat', he: 'שמרת' },
  { en: 'Shamshit', he: 'שמשית' },
  { en: 'Shani', he: 'שני' },
  { en: 'Snir', he: 'שניר' },
  { en: 'Shaab', he: 'שעב' },
  { en: 'Seorim', he: 'שעורים' },
  { en: 'Shaal', he: 'שעל' },
  { en: 'Shaalvim', he: 'שעלבים' },
  { en: 'Shaar Efraim', he: 'שער אפרים' },
  { en: 'Shaar HaGolan', he: 'שער הגולן' },
  { en: 'Shaar HaAmakim', he: 'שער העמקים' },
  { en: 'Shaar Menashe', he: 'שער מנשה' },
  { en: 'Shaarei Avraham', he: 'שערי אברהם' },
  { en: 'Shaarei Tikva', he: 'שערי תקווה' },
  { en: 'Shfayim', he: 'שפיים' },
  { en: 'Shafir', he: 'שפיר' },
  { en: 'Shefer', he: 'שפר' },
  { en: 'Shfaram', he: 'שפרעם' },
  { en: 'Shaqba', he: 'שקבה' },
  { en: 'Shaked', he: 'שקד' },
  { en: 'Shekef', he: 'שקף' },
  { en: 'Sharona', he: 'שרונה' },
  { en: 'Srigim (Li-On)', he: 'שריגים (לי-און)' },
  { en: 'Sarid', he: 'שריד' },
  { en: 'Sharsheret', he: 'שרשרת' },
  { en: 'Shtula', he: 'שתולה' },
  { en: 'Shtulim', he: 'שתולים' },

  // ת
  { en: 'Taashur', he: 'תאשור' },
  { en: 'Tidhar', he: 'תדהר' },
  { en: 'Tuval', he: 'תובל' },
  { en: 'Tomer', he: 'תומר' },
  { en: 'Tushiya', he: 'תושיה' },
  { en: 'Tayasir', he: 'תיאסיר' },
  { en: 'Timorim', he: 'תימורים' },
  { en: 'Tirosh', he: 'תירוש' },
  { en: 'Tel', he: 'תל' },
  { en: 'Tel al-Shamsiya', he: 'תל א שמסיה' },
  { en: 'Tel Abu Shanaar', he: 'תל אבו שנאר' },
  { en: 'Tel Aviv-Yafo', he: 'תל אביב - יפו' },
  { en: 'Tel al-Ahmar', he: 'תל אל אחמר' },
  { en: 'Tel al-Bayda', he: 'תל אל בידא' },
  { en: 'Tel Yosef', he: 'תל יוסף' },
  { en: 'Tel Yitzchak', he: 'תל יצחק' },
  { en: 'Tel Mond', he: 'תל מונד' },
  { en: 'Tel Adashim', he: 'תל עדשים' },
  { en: 'Tel Katzir', he: 'תל קציר' },
  { en: 'Tel Sheva', he: 'תל שבע' },
  { en: 'Tel Teomim', he: 'תל תאומים' },
  { en: 'Telem', he: 'תלם' },
  { en: 'Talmei Eliyahu', he: 'תלמי אליהו' },
  { en: 'Talmei Elazar', he: 'תלמי אלעזר' },
  { en: 'Talmei Bilu', he: 'תלמי ביל"ו' },
  { en: 'Talmei Yosef', he: 'תלמי יוסף' },
  { en: 'Talmei Yechiel', he: 'תלמי יחיאל' },
  { en: 'Talmei Yafe', he: 'תלמי יפה' },
  { en: 'Talmim', he: 'תלמים' },
  { en: 'Talfit Jenin', he: 'תלפית ג\'נין' },
  { en: 'Talfit Shechem', he: 'תלפית שכם' },
  { en: 'Tamad', he: 'תמד' },
  { en: 'Timrat', he: 'תמרת' },
  { en: 'Tenuvot', he: 'תנובות' },
  { en: 'Taoz', he: 'תעוז' },
  { en: 'Taanakh', he: 'תענך' },
  { en: 'Tapuach', he: 'תפוח' },
  { en: 'Tifrah', he: 'תפרח' },
  { en: 'Tekuma', he: 'תקומה' },
  { en: 'Tekoa', he: 'תקוע' },
  { en: 'Tarabin al-Sane (Tribe)', he: 'תראבין א-צאנע (שבט)' },
  { en: 'Tarabin al-Sane (Settlement)', he: 'תראבין א-צאנע (ישוב)' },
  { en: 'Tarum', he: 'תרום' },
  { en: 'Turmus Ayya', he: 'תרמוסעיא' },
  { en: 'Tarfat al-Qadr', he: 'תרפת אל קדר' },
  { en: 'Tarqumiya', he: 'תרקומיא' },
];

export interface IsraelCitiesAutocompleteProps {
  value: string;
  onChange: (value: string) => void;
  onSelect?: (city: string) => void;
  label?: string;
  placeholder?: string;
  error?: string;
  disabled?: boolean;
  className?: string;
  required?: boolean;
  id?: string;
  locale?: 'en' | 'he';
}

const IsraelCitiesAutocomplete = React.forwardRef<
  HTMLInputElement,
  IsraelCitiesAutocompleteProps
>(
  (
    {
      value,
      onChange,
      onSelect,
      label,
      placeholder,
      error,
      disabled = false,
      className,
      required = false,
      id: providedId,
      locale = 'en',
    },
    ref
  ) => {
    const [isOpen, setIsOpen] = React.useState(false);
    const [isFocused, setIsFocused] = React.useState(false);
    const [filteredCities, setFilteredCities] = React.useState<typeof ISRAEL_CITIES>([]);
    const [highlightedIndex, setHighlightedIndex] = React.useState(0);
    const generatedId = React.useId();
    const finalId = providedId || generatedId;
    const listRef = React.useRef<HTMLUListElement>(null);
    const finalPlaceholder = placeholder ?? (locale === 'he' ? 'חפש עיר...' : 'Search for a city...');

    // Filter logic: use .includes() for better UX (e.g., "Saba" finds "Kfar Saba")
    // Sort based on locale - English ABC or Hebrew אב"ג
    React.useEffect(() => {
      const searchTerm = value.trim().toLowerCase();
      
      const sortByLocale = (cities: typeof ISRAEL_CITIES) => {
        return [...cities].sort((a, b) => {
          if (locale === 'he') {
            return a.he.localeCompare(b.he, 'he');
          }
          return a.en.localeCompare(b.en, 'en');
        });
      };
      
      if (searchTerm) {
        const filtered = ISRAEL_CITIES.filter((city) => {
          const enMatch = city.en.toLowerCase().includes(searchTerm);
          const heMatch = city.he.includes(searchTerm);
          return enMatch || heMatch;
        });
        setFilteredCities(sortByLocale(filtered));
        setIsOpen(true);
        setHighlightedIndex(0);
      } else if (isFocused) {
        // Show all cities when focused but no search term
        setFilteredCities(sortByLocale(ISRAEL_CITIES));
        setIsOpen(true);
        setHighlightedIndex(0);
      } else {
        setFilteredCities([]);
        setIsOpen(false);
      }
    }, [value, isFocused, locale]);

    const handleSelect = (cityValue: string) => {
      onChange(cityValue);
      setIsOpen(false);
      onSelect?.(cityValue);
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (!isOpen) return;

      switch (e.key) {
        case 'ArrowDown':
          e.preventDefault();
          setHighlightedIndex((prev) =>
            prev < filteredCities.length - 1 ? prev + 1 : prev
          );
          break;
        case 'ArrowUp':
          e.preventDefault();
          setHighlightedIndex((prev) => (prev > 0 ? prev - 1 : 0));
          break;
        case 'Enter':
          e.preventDefault();
          if (filteredCities[highlightedIndex]) {
            const selection = locale === 'he' ? filteredCities[highlightedIndex].he : filteredCities[highlightedIndex].en;
            handleSelect(selection);
          }
          break;
        case 'Escape':
          setIsOpen(false);
          break;
      }
    };

    // Auto-scroll to highlighted item
    React.useEffect(() => {
      if (highlightedIndex >= 0 && listRef.current) {
        const item = listRef.current.children[highlightedIndex] as HTMLElement;
        item?.scrollIntoView({ block: 'nearest' });
      }
    }, [highlightedIndex]);

    return (
      <div className={cn('relative w-full', className)} dir={locale === 'he' ? 'rtl' : 'ltr'}>
        {label && (
          <label
            htmlFor={finalId}
            className="block text-sm font-medium text-text dark:text-text-dark mb-1.5"
          >
            {label}
            {required && <span className="text-red-500 ms-1">*</span>}
          </label>
        )}

        <Popover.Root open={isOpen} onOpenChange={setIsOpen}>
          <div className="relative">
            <div
              className={cn(
                'max-w-[14rem] flex-1',
                'relative flex items-center h-10 w-full rounded-xl px-3 py-2 text-sm transition-all bord bg-input dark:bg-input-dark',
                'focus-within:border-brand-main ',
                disabled && 'opacity-50 cursor-not-allowed',
                error && 'border-red-500'
              )}
            >
              <Popover.Trigger asChild>
                <input
                  ref={ref}
                  id={finalId}
                  type="text"
                  value={value}
                  onChange={(e) => onChange(e.target.value)}
                  onKeyDown={handleKeyDown}
                  onFocus={() => setIsFocused(true)}
                  onBlur={() => setIsFocused(false)}
                  placeholder={finalPlaceholder}
                  disabled={disabled}
                  required={required}
                  autoComplete="off"
                  className="flex-1 bg-transparent outline-none text-slate-900 dark:text-slate-100 placeholder:text-text-secondary dark:placeholder:text-text-secondary-dark focus-visible:outline-none"
                />
              </Popover.Trigger>

              {value && (
                <button
                  type="button"
                  onClick={() => onChange('')}
                  className="p-1 hover:bg-gray-hover-bg dark:hover:bg-gray-hover-bg-dark rounded-full transition-color duration-200"
                >
                  <X className="h-3.5 w-3.5 text-gray dark:text-gray-dark" />
                </button>
              )}
            </div>

            <Popover.Content
              side="bottom"
              align="start"
              sideOffset={4}
              onOpenAutoFocus={(e) => e.preventDefault()}
              className="z-50 w-[var(--radix-popover-trigger-width)] overflow-hidden rounded-lg border border-border dark:border-border-dark bg-background dark:bg-background-dark shadow-xl"
            >
              <ul ref={listRef} className="max-h-60 overflow-y-auto p-1">
                {filteredCities.length > 0 ? (
                  filteredCities.map((city, index) => {
                    const displayName = locale === 'he' ? city.he : city.en;
                    const isSelected = value.toLowerCase() === displayName.toLowerCase();
                    
                    return (
                      <li key={`${city.en}-${index}`}>
                        <button
                          type="button"
                          onClick={() => handleSelect(displayName)}
                          className={cn(
                            'w-full px-3 py-1.5 my-0.5 text-sm rounded-md transition-colors text-start',
                            highlightedIndex === index
                              ? 'bg-brand-main/5 dark:bg-brand-dark/10 text-brand-main dark:text-brand-dark'
                              : 'text-gray dark:text-gray-dark hover:bg-gray-bg/50 dark:hover:bg-gray-bg-dark ',
                            isSelected && 'bg-brand-main/50 dark:bg-brand-dark/20 font-medium'
                          )}
                        >
                          {displayName}
                        </button>
                      </li>
                    );
                  })
                ) : (
                  <li className="px-3 py-2 text-sm text-slate-500 dark:text-slate-400">
                    {locale === 'he' ? 'אין תוצאות' : 'No results'}
                  </li>
                )}
              </ul>
            </Popover.Content>
          </div>
        </Popover.Root>

        {error && (
          <p className="text-xs text-red-500 mt-1.5 px-1">{error}</p>
        )}
      </div>
    );
  }
);

IsraelCitiesAutocomplete.displayName = 'IsraelCitiesAutocomplete';

export { IsraelCitiesAutocomplete, ISRAEL_CITIES };