'use client';

import * as React from 'react';
import { X } from 'lucide-react';
import * as Popover from '@radix-ui/react-popover';
import { cn } from '@/lib/utils';


// Comprehensive list of Israeli cities and towns with Hebrew names
const ISRAEL_CITIES = [
  { en: 'Abu Juweiid', he: 'אבו ג\'אמדה' },
  { en: 'Abu Ghosh', he: 'אבו גוש' },
  { en: 'Abu Sinan', he: 'אבו סנאן' },
  { en: 'Abu Abdun', he: 'אבו עבדון' },
  { en: 'Abu Ammar', he: 'אבו עמאר' },
  { en: 'Abu Amre', he: 'אבו עמר' },
  { en: 'Abu Rubeia', he: 'אבו עפאש' },
  { en: 'Abu Qureinat', he: 'אבו קורינאת' },
  { en: 'Abu Ruqayyeq', he: 'אבו רוקייק' },
  { en: 'Abu Tulul', he: 'אבו תלול' },
  { en: 'Afula', he: 'עפולה' },
  { en: 'Arad', he: 'ערד' },
  { en: 'Ariel', he: 'אריאל' },
  { en: 'Ashdod', he: 'אשדוד' },
  { en: 'Ashkelon', he: 'אשקלון' },
  { en: 'Bat Yam', he: 'בת ים' },
  { en: 'Be\'er Sheva', he: 'באר שבע' },
  { en: 'Beit She\'an', he: 'בית שאן' },
  { en: 'Beit Shemesh', he: 'בית שמש' },
  { en: 'Bnei Brak', he: 'בני ברק' },
  { en: 'Carmiel', he: 'כרמיאל' },
  { en: 'Caesarea', he: 'קיסריה' },
  { en: 'Dimona', he: 'דימונה' },
  { en: 'Eilat', he: 'אילת' },
  { en: 'Elad', he: 'אלעד' },
  { en: 'Eshkol', he: 'אשכול' },
  { en: 'Gedera', he: 'גדרה' },
  { en: 'Givatayim', he: 'גבעתיים' },
  { en: 'Giv\'at Shmuel', he: 'גבעת שמואל' },
  { en: 'Gonen', he: 'גונן' },
  { en: 'Hadera', he: 'חדרה' },
  { en: 'Haifa', he: 'חיפה' },
  { en: 'Hatzor', he: 'חצור' },
  { en: 'Hertzliya', he: 'הרצליה' },
  { en: 'Hod Hasharon', he: 'הוד השרון' },
  { en: 'Holon', he: 'חולון' },
  { en: 'Hurfeish', he: 'חורפיש' },
  { en: 'Jaffa', he: 'יפו' },
  { en: 'Jerusalem', he: 'ירושלים' },
  { en: 'Jish', he: 'ג\'יש' },
  { en: 'Kafr Qasim', he: 'כפר קאסם' },
  { en: 'Karmiel', he: 'כרמיאל' },
  { en: 'Kastel', he: 'קסטל' },
  { en: 'Kfar Saba', he: 'כפר סבא' },
  { en: 'Kfar Tabia', he: 'כפר תביא' },
  { en: 'Kiryat Ata', he: 'קריית אתא' },
  { en: 'Kiryat Bialik', he: 'קריית ביאליק' },
  { en: 'Kiryat Gat', he: 'קריית גת' },
  { en: 'Kiryat Malachi', he: 'קריית מלאכי' },
  { en: 'Kiryat Motzkin', he: 'קריית מוצקין' },
  { en: 'Kiryat Shmona', he: 'קריית שמונה' },
  { en: 'Kiryat Yam', he: 'קריית ים' },
  { en: 'Kochav Yair', he: 'כוכב יאיר' },
  { en: 'Kochelis', he: 'כחליים' },
  { en: 'Kuseife', he: 'כוסיפה' },
  { en: 'Lachish', he: 'לכיש' },
  { en: 'Latroun', he: 'לטרון' },
  { en: 'Lod', he: 'לוד' },
  { en: 'Ma\'ale Adumim', he: 'מעלה אדומים' },
  { en: 'Maccabi', he: 'מכבי' },
  { en: 'Maccabim', he: 'מכבים' },
  { en: 'Maghar', he: 'מגאר' },
  { en: 'Mahane Yehuda', he: 'מחנה יהודה' },
  { en: 'Mamshit', he: 'ממשית' },
  { en: 'Manahat', he: 'מנחת' },
  { en: 'Manara', he: 'מנרה' },
  { en: 'Manof', he: 'מנוף' },
  { en: 'Maoz Zion', he: 'מעוז ציון' },
  { en: 'Marbek', he: 'מרבק' },
  { en: 'Marj al-Zahur', he: 'מרג אל-זהור' },
  { en: 'Mas\'uda', he: 'מסעודה' },
  { en: 'Masada', he: 'מצדה' },
  { en: 'Matzuv', he: 'מצוב' },
  { en: 'Megiddo', he: 'מגידו' },
  { en: 'Mehola', he: 'מחולה' },
  { en: 'Meiron', he: 'מירון' },
  { en: 'Meithalun', he: 'מיתלון' },
  { en: 'Meron', he: 'מרון' },
  { en: 'Mervat Zion', he: 'מרוות ציון' },
  { en: 'Metula', he: 'מטולה' },
  { en: 'Misgav', he: 'משגב' },
  { en: 'Mishmar Hasharon', he: 'משמר השרון' },
  { en: 'Mishmar HaYarden', he: 'משמר הירדן' },
  { en: 'Mishmeret', he: 'משמרת' },
  { en: 'Mitzpe Ramon', he: 'מצפה רמון' },
  { en: 'Mizpe Yeriho', he: 'מצפה יריחו' },
  { en: 'Mizrah', he: 'מזרח' },
  { en: 'Moadim', he: 'מועדים' },
  { en: 'Modiin', he: 'מודיעין' },
  { en: 'Modi\'in Ilit', he: 'מודיעין עילית' },
  { en: 'Molad', he: 'מולד' },
  { en: 'Monfort', he: 'מונפור' },
  { en: 'Moriah', he: 'מוריה' },
  { en: 'Moshav', he: 'מושב' },
  { en: 'Motti', he: 'מוטי' },
  { en: 'Mount Carmel', he: 'הר הכרמל' },
  { en: 'Mukhmas', he: 'מוכמס' },
  { en: 'Mu\'ar', he: 'מוער' },
  { en: 'Na\'an', he: 'נעין' },
  { en: 'Nahariya', he: 'נהריה' },
  { en: 'Nahshon', he: 'נחשון' },
  { en: 'Nazareth', he: 'נצרת' },
  { en: 'Nazareth Illit', he: 'נצרת עילית' },
  { en: 'Netanya', he: 'נתניה' },
  { en: 'Nir Am', he: 'ניר עם' },
  { en: 'Nir David', he: 'ניר דוד' },
  { en: 'Niv\'im', he: 'נביעים' },
  { en: 'Omer', he: 'עומר' },
  { en: 'Or Akiva', he: 'אור עקיבא' },
  { en: 'Or Yehuda', he: 'אור יהודה' },
  { en: 'Petach Tikva', he: 'פתח תקוה' },
  { en: 'Raanana', he: 'רעננה' },
  { en: 'Rahat', he: 'רהט' },
  { en: 'Ramla', he: 'רמלה' },
  { en: 'Ramat Gan', he: 'רמת גן' },
  { en: 'Ramat Hasharon', he: 'רמת השרון' },
  { en: 'Ramat Yishai', he: 'רמת ישי' },
  { en: 'Ramot', he: 'רמות' },
  { en: 'Rechovot', he: 'רחובות' },
  { en: 'Rishon Lezion', he: 'ראשון לציון' },
  { en: 'Rosh Haayin', he: 'ראש העין' },
  { en: 'Rosh Pina', he: 'ראש פינה' },
  { en: 'Rosh Tzurim', he: 'ראש צורים' },
  { en: 'Saar', he: 'סער' },
  { en: 'Safed', he: 'צפת' },
  { en: 'Sakhnin', he: 'סכנין' },
  { en: 'Salim', he: 'סלים' },
  { en: 'Samaria', he: 'שומרון' },
  { en: 'Sasa', he: 'סאסא' },
  { en: 'Sdei Boker', he: 'שדי בוקר' },
  { en: 'Sedom', he: 'סדום' },
  { en: 'Shaar HaGolan', he: 'שער הגולן' },
  { en: 'Shaar HaNegev', he: 'שער הנגב' },
  { en: 'Shaharut', he: 'שהרות' },
  { en: 'Shefaram', he: 'שפרעם' },
  { en: 'Shoham', he: 'שוהם' },
  { en: 'Shuafat', he: 'שועפט' },
  { en: 'Tel Aviv', he: 'תל אביב' },
  { en: 'Tiberias', he: 'טבריה' },
  { en: 'Tivon', he: 'טיבון' },
  { en: 'Tzfat', he: 'צפת' },
  { en: 'Yed Mordechai', he: 'יד מרדכי' },
  { en: 'Yotvata', he: 'יטבתה' },
  { en: 'Yavne', he: 'יבנה' },
  { en: 'Yokneam', he: 'יקנעם' },
  { en: 'Zichron Yaakov', he: 'זיכרון יעקב' },
  { en: 'Zomer', he: 'זומר' },
  { en: 'Zomet Ilanot', he: 'זומט אילנות' },
  // Additional settlements
  { en: 'A-Taiyba', he: 'א-טייבה א-זועביה' },
  { en: 'Abu Sameh', he: 'אבו סנינא' },
  { en: 'Abu Afish', he: 'אבו עפאש' },
  { en: 'Abu Sheihe', he: 'אבו עשיבה' },
  { en: 'Avtalyon', he: 'אבטליון' },
  { en: 'Aviel', he: 'אביאל' },
  { en: 'Avivim', he: 'אביבים' },
  { en: 'Avigedor', he: 'אביגדור' },
  { en: 'Avihayil', he: 'אביחיל' },
  { en: 'Avital', he: 'אביטל' },
  { en: 'Aviezer', he: 'אביעזר' },
  { en: 'Abbirim', he: 'אבירים' },
  { en: 'Even Yehuda', he: 'אבן יהודה' },
  { en: 'Even Menahem', he: 'אבן מנחם' },
  { en: 'Even Sappir', he: 'אבן ספיר' },
  { en: 'Even Shemuel', he: 'אבן שמואל' },
  { en: 'Avne Etan', he: 'אבני איתן' },
  { en: 'Avshalom', he: 'אבשלום' },
  { en: 'Adora', he: 'אדירים' },
  { en: 'Adamit', he: 'אדמית' },
  { en: 'Adderet', he: 'אדרת' },
  { en: 'Udim', he: 'אודים' },
  { en: 'Odem', he: 'אודם' },
  { en: 'Ohad', he: 'אוהד' },
  { en: 'Umm Alfahm', he: 'אום אל-פחם' },
  { en: 'Umm Batin', he: 'אום בטין' },
  { en: 'Umm Mitnan', he: 'אום מיתנאן' },
  { en: 'Umm Ratham', he: 'אום רתאם' },
  { en: 'Omen', he: 'אומן' },
  { en: 'Omez', he: 'אומץ' },
  { en: 'Ofaqim', he: 'אופקים' },
  { en: 'Or Haganuz', he: 'אור הגנוז' },
  { en: 'Or Haner', he: 'אור הנר' },
  { en: 'Or Yehuda', he: 'אור יהודה' },
  { en: 'Or Aqiva', he: 'אור עקיבא' },
  { en: 'Ora', he: 'אורה' },
  { en: 'Orot', he: 'אורות' },
  { en: 'Ortal', he: 'אורטל' },
  { en: 'Urim', he: 'אורים' },
  { en: 'Oranim', he: 'אורנים' },
  { en: 'Oranit', he: 'אורנית' },
  { en: 'Usha', he: 'אושה' },
  { en: 'Azor', he: 'אזור' },
  { en: 'Ahuzzam', he: 'אחוזם' },
  { en: 'Ahuzzat Baraq', he: 'אחוזת ברק' },
  { en: 'Ahihud', he: 'אחיהוד' },
  { en: 'Ahituv', he: 'אחיטוב' },
  { en: 'Ahisamakh', he: 'אחיסמך' },
  { en: 'Ahiezer', he: 'אחיעזר' },
  { en: 'Atrash', he: 'אטרש' },
  { en: 'Ibbim', he: 'איבים' },
  { en: 'Eyal', he: 'איילה' },
  { en: 'Elon', he: 'אילון' },
  { en: 'Elot', he: 'אילות' },
  { en: 'Ilaniyya', he: 'אילניה' },
  { en: 'Elat', he: 'אילת' },
  { en: 'Irus', he: 'איירוס' },
  { en: 'Itamar', he: 'איתן' },
  { en: 'Etan', he: 'איתנים' },
  { en: 'Iksal', he: 'אכסל' },
  { en: 'Almagor', he: 'אלמגור' },
  { en: 'Alummot', he: 'אלומות' },
  { en: 'Elon More', he: 'אלון הגליל' },
  { en: 'Allone Abba', he: 'אלוני אבא' },
  { en: 'Allone Habashan', he: 'אלוני הבשן' },
  { en: 'Allone Yizhaq', he: 'אלוני יצחק' },
  { en: 'Allonim', he: 'אלונים' },
  { en: 'Eliav', he: 'אליאב' },
  { en: 'Elifaz', he: 'אליפז' },
  { en: 'Elifelet', he: 'אליפלט' },
  { en: 'Elyaqim', he: 'אליקים' },
  { en: 'Elyashiv', he: 'אלישיב' },
  { en: 'Elishama', he: 'אלישמע' },
  { en: 'Almagor', he: 'אלמגור' },
  { en: 'Almog', he: 'אלמוג' },
  { en: 'Elad', he: 'אלעד' },
  { en: 'Elqosh', he: 'אלקוש' },
  { en: 'Elunim', he: 'אמונים' },
  { en: 'Amirim', he: 'אמירים' },
  { en: 'Amnun', he: 'אמנון' },
  { en: 'Amazya', he: 'אמציה' },
  { en: 'Aniam', he: 'אניעם' },
  { en: 'Asfar', he: 'אעצם' },
  { en: 'Afiq', he: 'אפיק' },
  { en: 'Afiqim', he: 'אפיקים' },
  { en: 'Afeq', he: 'אפק' },
  { en: 'Arbel', he: 'ארבל' },
  { en: 'Arz', he: 'ארז' },
  { en: 'Arsuf', he: 'ארסוף' },
  { en: 'Eshbol', he: 'אשבול' },
  { en: 'Eshbal', he: 'אשבל' },
  { en: 'Ashdod', he: 'אשדוד' },
  { en: 'Ashdot Yaaqov Ihud', he: 'אשדות יעקב איחוד' },
  { en: 'Ashdot Yaaqov Meuhad', he: 'אשדות יעקב מאוחד' },
  { en: 'Eshhar', he: 'אשחר' },
  { en: 'Eshel Hanasi', he: 'אשל הנשיא' },
  { en: 'Eshkolot', he: 'אשלים' },
  { en: 'Ashqelon', he: 'אשקלון' },
  { en: 'Asherat', he: 'אשרת' },
  { en: 'Eshtaol', he: 'אשתאול' },
  { en: 'Baqa Algharbiyye', he: 'באקה אל-גרביה' },
  { en: 'Beer Ora', he: 'באר אורה' },
  { en: 'Beer Milka', he: 'באר מילכה' },
  { en: 'Beer Sheva', he: 'באר שבע' },
  { en: 'Beerotayim', he: 'בארותיים' },
  { en: 'Beeri', he: 'בארי' },
  { en: 'Buqata', he: 'בוסתן הגליל' },
  { en: 'Burgeta', he: 'בורגתה' },
  { en: 'Bahan', he: 'בחן' },
  { en: 'Bitha', he: 'בטחה' },
  { en: 'Bizzaron', he: 'ביצרון' },
  { en: 'Bir Hadage', he: 'ביר א-סיכה' },
  { en: 'Biriyya', he: 'ביריה' },
  { en: 'Bet Oren', he: 'בית אורן' },
  { en: 'Bet Elazari', he: 'בית אלעזרי' },
  { en: 'Bet Alfa', he: 'בית אלפא' },
  { en: 'Bet Gamliel', he: 'בית גמליאל' },
  { en: 'Bet Guvrin', he: 'בית גוברין' },
  { en: 'Beit Jann', he: 'בית ג\'ן' },
  { en: 'Bet Dagan', he: 'בית דגן' },
  { en: 'Bet Hagaddi', he: 'בית הגדי' },
  { en: 'Bet Halewi', he: 'בית הלוי' },
  { en: 'Bet Hillel', he: 'בית הלל' },
  { en: 'Bet Haemeq', he: 'בית העמק' },
  { en: 'Bet Haarava', he: 'בית השיטה' },
  { en: 'Bet Zeid', he: 'בית זייד' },
  { en: 'Bet Zayit', he: 'בית זית' },
  { en: 'Bet Zera', he: 'בית זרע' },
  { en: 'Bet Hogla', he: 'בית חלקיה' },
  { en: 'Bet Hanan', he: 'בית חנן' },
  { en: 'Bet Hananya', he: 'בית חנניה' },
  { en: 'Bet Herut', he: 'בית חרות' },
  { en: 'Bet Hashmonay', he: 'בית חשמונאי' },
  { en: 'Bet Yehoshua', he: 'בית יהושע' },
  { en: 'Bet Yosef', he: 'בית יוסף' },
  { en: 'Bet Yannay', he: 'בית ינאי' },
  { en: 'Bet Yizhaq Shaer Hefer', he: 'בית יצחק - שער חפר' },
  { en: 'Bet Lehem Hagelilit', he: 'בית לחם הגלילית' },
  { en: 'Bet Meir', he: 'בית מאיר' },
  { en: 'Bet Nehemya', he: 'בית נחמיה' },
  { en: 'Bet Nir', he: 'בית ניר' },
  { en: 'Bet Neqofa', he: 'בית נקופה' },
  { en: 'Bet Oved', he: 'בית עובד' },
  { en: 'Bet Uzziel', he: 'בית עוזיאל' },
  { en: 'Bet Ezra', he: 'בית עזרא' },
  { en: 'Bet Arif', he: 'בית עריף' },
  { en: 'Bet Pelet', he: 'בית פלט' },
  { en: 'Bet Kama', he: 'בית קמה' },
  { en: 'Bet Qeshet', he: 'בית קשת' },
  { en: 'Bet Rimmon', he: 'בית רימון' },
  { en: 'Bet Shean', he: 'בית שאן' },
  { en: 'Bet Shearim', he: 'בית שערים' },
  { en: 'Bet Shiqma', he: 'בית שיקמה' },
  { en: 'Bet Shemesh', he: 'בית שמש' },
  { en: 'Bitan Aharon', he: 'ביתן אהרן' },
  { en: 'Balfurya', he: 'בלפוריה' },
  { en: 'Ben Zakkay', he: 'בן זכאי' },
  { en: 'Ben Ammi', he: 'בן עמי' },
  { en: 'Ben Shemen', he: 'בן שמן' },
  { en: 'Bene Beraq', he: 'בני ברק' },
  { en: 'Bne Deqalim', he: 'בני דקלים' },
  { en: 'Bene Darom', he: 'בני דרום' },
  { en: 'Bene Deror', he: 'בני דרור' },
  { en: 'Bene Yehuda', he: 'בני יהודה' },
  { en: 'Bne Netsarim', he: 'בני נצרים' },
  { en: 'Bene Atarot', he: 'בני עטרות' },
  { en: 'Bene Ayish', he: 'בני עי"ש' },
  { en: 'Bene Ziyyon', he: 'בני ציון' },
  { en: 'Bene Reem', he: 'בני ראם' },
  { en: 'Benaya', he: 'בניה' },
  { en: 'Binyaminagivat Ada', he: 'בנימינה' },
  { en: 'Basmat Tabun', he: 'בסמת טבעון' },
  { en: 'Barqan', he: 'בערינה נג\'ידת' },
  { en: 'Baraka', he: 'בענה' },
  { en: 'Bazra', he: 'בצרה' },
  { en: 'Bezet', he: 'בצת' },
  { en: 'Beqoa', he: 'בקוע' },
  { en: 'Bar Giyyora', he: 'בר גיורא' },
  { en: 'Bar Yohay', he: 'בר יוחאי' },
  { en: 'Brukhin', he: 'ברור חיל' },
  { en: 'Berosh', he: 'ברוש' },
  { en: 'Berakha', he: 'ברכיה' },
  { en: 'Baram', he: 'ברעם' },
  { en: 'Baraq', he: 'ברק' },
  { en: 'Barkay', he: 'ברקאי' },
  { en: 'Bareqet', he: 'ברקת' },
  { en: 'Bat Hadar', he: 'בת הדר' },
  { en: 'Bat Hen', he: 'בת חן' },
  { en: 'Bat Hefer', he: 'בת חפר' },
  { en: 'Bat Yam', he: 'בת ים' },
  { en: 'Bat Shlomo', he: 'בת שלמה' },
  { en: 'Julis', he: 'ג\'וליס' },
  { en: 'Jaljaliya', he: 'ג\'לג\'וליה' },
  { en: 'Janabin', he: 'ג\'נאביב' },
  { en: 'Jish', he: 'ג\'ש' },
  { en: 'Jat', he: 'ג\'ת' },
  { en: 'Geulim', he: 'גאולי תימן' },
  { en: 'Gealya', he: 'גאליה' },
  { en: 'Gevulot', he: 'גבולות' },
  { en: 'Gevim', he: 'גבים' },
  { en: 'Geva', he: 'גבע' },
  { en: 'Givolim', he: 'גבעולים' },
  { en: 'Gevaot Bar', he: 'גבעות בר' },
  { en: 'Givot Eden', he: 'גבעות עדן' },
  { en: 'Givat Avni', he: 'גבעות אבני' },
  { en: 'Givat Ela', he: 'גבעת אלה' },
  { en: 'Givat Allonim', he: 'גבעת אלונים' },
  { en: 'Givat Brenner', he: 'גבעת ברנר' },
  { en: 'Givat Hashelosha', he: 'גבעת השלושה' },
  { en: 'Givat Hen', he: 'גבעת ח"ן' },
  { en: 'Givat Habiba', he: 'גבעת חביבה' },
  { en: 'Givat Hayyim Ihud', he: 'גבעת חיים (איחוד)' },
  { en: 'Givat Hayyim Meuhad', he: 'גבעת חיים (מאוחד)' },
  { en: 'Givat Yoav', he: 'גבעת יואב' },
  { en: 'Givat Yearim', he: 'גבעת יערים' },
  { en: 'Givat Yeshayahu', he: 'גבעת ישעיהו' },
  { en: 'Givat Koah', he: 'גבעת כח' },
  { en: 'Givat Nili', he: 'גבעת ניל"י' },
  { en: 'Givat Ada', he: 'גבעת עדה' },
  { en: 'Givat Oz', he: 'גבעת עוז' },
  { en: 'Givat Shemuel', he: 'גבעת שמואל' },
  { en: 'Givat Shemesh', he: 'גבעת שמש' },
  { en: 'Givat Shapira', he: 'גבעת שפירא' },
  { en: 'Givatati', he: 'גבעתי' },
  { en: 'Givatayim', he: 'גבעתיים' },
  { en: 'Gevaram', he: 'גברעם' },
  { en: 'Gevat', he: 'גבת' },
  { en: 'Gadot', he: 'גדות' },
  { en: 'Judeidemaaker', he: 'ג\'דיידה-מכר' },
  { en: 'Gadish', he: 'גדיש' },
  { en: 'Gidona', he: 'גדעונה' },
  { en: 'Gedera', he: 'גדרה' },
  { en: 'Julis', he: 'ג\'וליס' },
  { en: 'Gonen', he: 'גונן' },
  { en: 'Goren', he: 'גורן' },
  { en: 'Gazit', he: 'גזית' },
  { en: 'Gezer', he: 'גזר' },
  { en: 'Gea', he: 'גיאה' },
  { en: 'Gibbeton', he: 'גיבתון' },
  { en: 'Gizo', he: 'גיזו' },
  { en: 'Gilon', he: 'גילון' },
  { en: 'Gilat', he: 'גילת' },
  { en: 'Ginnegar', he: 'גינדל' },
  { en: 'Ginnosar', he: 'גינסור' },
  { en: 'Ginnaton', he: 'גינתון' },
  { en: 'Gitta', he: 'גיתה' },
  { en: 'Galon', he: 'גלאון' },
  { en: 'Galil Yam', he: 'גליל ים' },
  { en: 'Galed', he: 'גלעד' },
  { en: 'Gamzo', he: 'גמזו' },
  { en: 'Gan Hayyim', he: 'גן חיים' },
  { en: 'Gan Yavne', he: 'גן יבנה' },
  { en: 'Gan Ner', he: 'גן נר' },
  { en: 'Gan Soreq', he: 'גן שורק' },
  { en: 'Gan Shelomo', he: 'גן שלמה' },
  { en: 'Gan Shemuel', he: 'גן שמואל' },
  { en: 'Gannot', he: 'גנות' },
  { en: 'Ganne Hadar', he: 'גנות הדר' },
  { en: 'Ganne Tal', he: 'גני טל' },
  { en: 'Ganne Yohanan', he: 'גני יוחנן' },
  { en: 'Ganne Am', he: 'גני עם' },
  { en: 'Ganne Tiqwa', he: 'גני תקווה' },
  { en: 'Ganeniger', he: 'גניגר' },
  { en: 'Gaash', he: 'געש' },
  { en: 'Gaton', he: 'געתון' },
  { en: 'Gefen', he: 'גפן' },
  { en: 'Gerofit', he: 'גרופית' },
  { en: 'Gornot Hagalil', he: 'גרנות הגליל' },
  { en: 'Geshur', he: 'גשור' },
  { en: 'Gesher', he: 'גשר' },
  { en: 'Gesher Haziw', he: 'גשר הזיו' },
  { en: 'Gat', he: 'גת' },
  { en: 'Gat Rimmon', he: 'גת רימון' },
  { en: 'Devora', he: 'דבורה' },
  { en: 'Daburiyya', he: 'דבוריה' },
  { en: 'Dvir', he: 'דביר' },
  { en: 'Daverat', he: 'דברת' },
  { en: 'Deganya Alef', he: 'דגניה א\'' },
  { en: 'Deganya Bet', he: 'דגניה ב\'' },
  { en: 'Dahmash', he: 'דהמש' },
  { en: 'Dovev', he: 'דור' },
  { en: 'Dorot', he: 'דורות' },
  { en: 'Dimona', he: 'דימונה' },
  { en: 'Deir Alasad', he: 'דיר אל אסד' },
  { en: 'Deir Hanna', he: 'דיר חנא' },
  { en: 'Dishon', he: 'דישון' },
  { en: 'Daliyya', he: 'דליה' },
  { en: 'Daliyat Alkarmel', he: 'דלית אל-כרמל' },
  { en: 'Dalton', he: 'דלתון' },
  { en: 'Demeide', he: 'דמיידה' },
  { en: 'Dan', he: 'דן' },
  { en: 'Dafna', he: 'דפנה' },
  { en: 'Deqel', he: 'דקל' },
  { en: 'Derigat', he: 'דריג\'את' },
  { en: 'Haon', he: 'האון' },
  { en: 'Habonim', he: 'הבונים' },
  { en: 'Hagosherim', he: 'הגושרים' },
  { en: 'Hadar Am', he: 'הדר עם' },
  { en: 'Hodayot', he: 'הודיה' },
  { en: 'Hodiyya', he: 'הודיה' },
  { en: 'Hawashla', he: 'הוואשלה' },
  { en: 'Huzayyel', he: 'הוזייל' },
  { en: 'Hoshaaya', he: 'הושעיה' },
  { en: 'Hazorea', he: 'הזורע' },
  { en: 'Hazoreim', he: 'הזורעים' },
  { en: 'Hahoterim', he: 'החותרים' },
  { en: 'Hayogev', he: 'היוגב' },
  { en: 'Hella', he: 'היובל' },
  { en: 'Hamapil', he: 'המעפיל' },
  { en: 'Hasolelim', he: 'הסוללים' },
  { en: 'Haogen', he: 'העוגן' },
  { en: 'Har Adar', he: 'הר חלוץ' },
  { en: 'Har Gillo', he: 'הר עמשא' },
  { en: 'Harel', he: 'הראל' },
  { en: 'Harduf', he: 'הרדוף' },
  { en: 'Herzliyya', he: 'הרצליה' },
  { en: 'Hararit', he: 'הררית' },
  { en: 'Hod Hasharon', he: 'הוד השרון' },
  { en: 'Wered', he: 'ורדון' },
  { en: 'Zabarga', he: 'זבארגה' },
  { en: 'Zavdiel', he: 'זבדיאל' },
  { en: 'Zohar', he: 'זוהר' },
  { en: 'Ziqim', he: 'זיקים' },
  { en: 'Zetan', he: 'זיתן' },
  { en: 'Zekharya', he: 'זכריה' },
  { en: 'Zemer', he: 'זלפה' },
  { en: 'Zimrat', he: 'זימרת' },
  { en: 'Zanoah', he: 'זנוח' },
  { en: 'Zerua', he: 'זרועה' },
  { en: 'Zarzir', he: 'זרזיר' },
  { en: 'Zerahya', he: 'זרחיה' },
  { en: 'Zereit', he: 'זרעית' },
  { en: 'Hever', he: 'חבר' },
  { en: 'Hagor', he: 'חגור' },
  { en: 'Haggay', he: 'חגלה' },
  { en: 'Hagol', he: 'חד נס' },
  { en: 'Hadid', he: 'חדיד' },
  { en: 'Hadera', he: 'חדרה' },
  { en: 'Khawaled', he: 'חוואלד' },
  { en: 'Hulda', he: 'חולדה' },
  { en: 'Holon', he: 'חולון' },
  { en: 'Holit', he: 'חולית' },
  { en: 'Hulata', he: 'חולתה' },
  { en: 'Hosen', he: 'חוסן' },
  { en: 'Hussniyya', he: 'חוסנייה' },
  { en: 'Hofit', he: 'חופית' },
  { en: 'Huqoq', he: 'חוקוק' },
  { en: 'Hura', he: 'חורה' },
  { en: 'Hurfeish', he: 'חורפיש' },
  { en: 'Horeshim', he: 'חורשים' },
  { en: 'Hazon', he: 'חזון' },
  { en: 'Hinnanit', he: 'חיבת ציון' },
  { en: 'Haifa', he: 'חיפה' },
  { en: 'Herut', he: 'חלץ' },
  { en: 'Haluz', he: 'חלוץ' },
  { en: 'Helez', he: 'חלץ' },
  { en: 'Hemed', he: 'חמ"ד' },
  { en: 'Hamam', he: 'חמדון' },
  { en: 'Hamadya', he: 'חמדיה' },
  { en: 'Hemdat', he: 'חמדת ימים' },
  { en: 'Hanniel', he: 'חניאל' },
  { en: 'Hanita', he: 'חניתה' },
  { en: 'Hannaton', he: 'חנתון' },
  { en: 'Haspin', he: 'חפץ חיים' },
  { en: 'Hefzibah', he: 'חפציבה' },
  { en: 'Hazav', he: 'חצב' },
  { en: 'Hazeva', he: 'חצבה' },
  { en: 'Hazor Hagelilit', he: 'חצור הגלילית' },
  { en: 'Hazor Ashdod', he: 'חצור אשדוד' },
  { en: 'Hazerim', he: 'חצרים' },
  { en: 'Haruzim', he: 'חרוזים' },
  { en: 'Harish', he: 'חריש' },
  { en: 'Harashim', he: 'חרשים' },
  { en: 'Tiberias', he: 'טבריה' },
  { en: 'Turan', he: 'טורעאן' },
  { en: 'Tayibe', he: 'טייבה' },
  { en: 'Tire', he: 'טירה' },
  { en: 'Tirat Zevi', he: 'טירת צבי' },
  { en: 'Tirat Yehuda', he: 'טירת יהודה' },
  { en: 'Tirat Karmel', he: 'טירת כרמל' },
  { en: 'Tirat Shalom', he: 'טירת שלום' },
  { en: 'Tal Shahar', he: 'טל שחר' },
  { en: 'Talel', he: 'טל-אל' },
  { en: 'Talalim', he: 'טללים' },
  { en: 'Tamra', he: 'טמרה' },
  { en: 'Tene', he: 'טנובות' },
  { en: 'Tefahot', he: 'טפחות' },
  { en: 'Yevul', he: 'יבול' },
  { en: 'Yavneel', he: 'יבנאל' },
  { en: 'Yavne', he: 'יבנה' },
  { en: 'Yagur', he: 'יגור' },
  { en: 'Yagel', he: 'יגל' },
  { en: 'Yad Binyamin', he: 'יד בנימין' },
  { en: 'Yad Hashemona', he: 'יד השמונה' },
  { en: 'Yad Hanna', he: 'יד חנה' },
  { en: 'Yad Mordechai', he: 'יד מרדכי' },
  { en: 'Yad Natan', he: 'יד נתן' },
  { en: 'Yad Rambam', he: 'יד רמב"ם' },
  { en: 'Yedida', he: 'יהוד מונוסון' },
  { en: 'Yahel', he: 'יהל' },
  { en: 'Yuval', he: 'יובלים' },
  { en: 'Yodefat', he: 'יודפת' },
  { en: 'Yonatan', he: 'יונתן' },
  { en: 'Yoshivya', he: 'יושיביה' },
  { en: 'Yizreel', he: 'יזרעאל' },
  { en: 'Yizraam', he: 'יזרעם' },
  { en: 'Yihad', he: 'יחד' },
  { en: 'Yihiam', he: 'יחיעם' },
  { en: 'Yotvata', he: 'יטבתה' },
  { en: 'Yakhini', he: 'יכיני' },
  { en: 'Yama', he: 'ימה' },
  { en: 'Yamin Arod', he: 'ימין אורד' },
  { en: 'Yanuv', he: 'ינוב' },
  { en: 'Yinnon', he: 'ינון' },
  { en: 'Yesodot', he: 'יסוד המעלה' },
  { en: 'Yasur', he: 'יסעור' },
  { en: 'Yaad', he: 'יעד' },
  { en: 'Yael', he: 'יעל' },
  { en: 'Yeaf', he: 'יעף' },
  { en: 'Yaara', he: 'יערה' },
  { en: 'Yafi', he: 'יפיע' },
  { en: 'Yafit', he: 'יפעת' },
  { en: 'Yifat', he: 'יפתח' },
  { en: 'Yad Mordechai', he: 'יציץ' },
  { en: 'Yaqum', he: 'יקום' },
  { en: 'Yaqir', he: 'יראון' },
  { en: 'Yiron', he: 'ירדנה' },
  { en: 'Yardena', he: 'ירוחם' },
  { en: 'Yeroham', he: 'ירושלים' },
  { en: 'Jerusalem', he: 'ירחיב' },
  { en: 'Yarhiv', he: 'ירכא' },
  { en: 'Yirka', he: 'ירקונה' },
  { en: 'Yarqona', he: 'ישוב בדואי' },
  { en: 'Yesha', he: 'ישע' },
  { en: 'Yishi', he: 'ישעי' },
  { en: 'Yashresh', he: 'ישרש' },
  { en: 'Yated', he: 'יתד' },
  { en: 'Kabul', he: 'כאבול' },
  { en: 'Kabri', he: 'כברי' },
  { en: 'Kadoorie', he: 'כדורי' },
  { en: 'Kaddita', he: 'כדיתה' },
  { en: 'Kokhav Yair', he: 'כוכב יאיר צור יגאל' },
  { en: 'Korazim', he: 'כורזים' },
  { en: 'Kahal', he: 'כחל' },
  { en: 'Kissufim', he: 'כיסופים' },
  { en: 'Kishor', he: 'כישור' },
  { en: 'Kelil', he: 'כליל' },
  { en: 'Kallanit', he: 'כלנית' },
  { en: 'Kamane', he: 'כמאנה' },
  { en: 'Kemehin', he: 'כמון' },
  { en: 'Kannot', he: 'כנות' },
  { en: 'Kanaf', he: 'כנף' },
  { en: 'Kuseife', he: 'כוסיפה' },
  { en: 'Kesalon', he: 'כסלון' },
  { en: 'Kefar Aviiv', he: 'כפר אביב' },
  { en: 'Kefar Ahim', he: 'כפר אחים' },
  { en: 'Kefar Bialik', he: 'כפר ביאליק' },
  { en: 'Kefar Bilu', he: 'כפר ביל"ו' },
  { en: 'Kefar Blum', he: 'כפר בלום' },
  { en: 'Kafar Bara', he: 'כפר ברא' },
  { en: 'Kefar Barukh', he: 'כפר ברוך' },
  { en: 'Kefar Gidon', he: 'כפר גדעון' },
  { en: 'Kefar Gallim', he: 'כפר גלים' },
  { en: 'Kefar Glikson', he: 'כפר גליקסון' },
  { en: 'Kefar Galadi', he: 'כפר גלעדי' },
  { en: 'Kefar Daniyyel', he: 'כפר דניאל' },
  { en: 'Kefar Hahoresh', he: 'כפר החורש' },
  { en: 'Kefar Hamakkabbi', he: 'כפר המכבי' },
  { en: 'Kefar Hanagid', he: 'כפר הנגיד' },
  { en: 'Kefar Hanasi', he: 'כפר הנשיא' },
  { en: 'Kefar Hess', he: 'כפר הס' },
  { en: 'Kefar Harif', he: 'כפר הרי"ף' },
  { en: 'Kefar Vitkin', he: 'כפר ויתקין' },
  { en: 'Kefar Zetim', he: 'כפר זיתים' },
  { en: 'Kefar Habad', he: 'כפר חב"ד' },
  { en: 'Kefar Hittim', he: 'כפר חיטים' },
  { en: 'Kefar Hayyim', he: 'כפר חיים' },
  { en: 'Kefar Hananya', he: 'כפר חנניה' },
  { en: 'Kefar Hasidim', he: 'כפר חסידים' },
  { en: 'Kefar Haruv', he: 'כפר חרוב' },
  { en: 'Kafar Yasif', he: 'כפר יאסיף' },
  { en: 'Kefar Yona', he: 'כפר יונה' },
  { en: 'Kefar Yabez', he: 'כפר יעבץ' },
  { en: 'Kafar Kama', he: 'כפר כמא' },
  { en: 'Kefar Kana', he: 'כפר כנא' },
  { en: 'Kefar Monash', he: 'כפר מונש' },
  { en: 'Kefar Maymon', he: 'כפר מימון' },
  { en: 'Kafar Misr', he: 'כפר מיסר' },
  { en: 'Kefar Szold', he: 'כפר מל"ל' },
  { en: 'Kafar Manda', he: 'כפר מנדא' },
  { en: 'Kefar Menahem', he: 'כפר מנחם' },
  { en: 'Kefar Masaryk', he: 'כפר מסריק' },
  { en: 'Kefar Mordekhay', he: 'כפר מרדכי' },
  { en: 'Kefar Netter', he: 'כפר נטר' },
  { en: 'Kefar Silver', he: 'כפר סאלד' },
  { en: 'Kafar Qasem', he: 'כפר קאסם' },
  { en: 'Kefar Kisch', he: 'כפר קיש' },
  { en: 'Kafar Qara', he: 'כפר קרע' },
  { en: 'Kefar Ruppin', he: 'כפר רופין' },
  { en: 'Kefar Rut', he: 'כפר רות' },
  { en: 'Kefar Rafael', he: 'כפר רפאל' },
  { en: 'Kefar Shammay', he: 'כפר שמאי' },
  { en: 'Kefar Shemuel', he: 'כפר שמואל' },
  { en: 'Kefar Shemaryahu', he: 'כפר שמריהו' },
  { en: 'Kefar Tavor', he: 'כפר תבור' },
  { en: 'Kefar Tappuah', he: 'כפר תקווה' },
  { en: 'Karkom', he: 'כרי דשא' },
  { en: 'Karme Zur', he: 'כרי נעמן' },
  { en: 'Karme Beyavne', he: 'כרם בן זמרה' },
  { en: 'Karme Maharal', he: 'כרם מהר"ל' },
  { en: 'Karme Shalom', he: 'כרם שלום' },
  { en: 'Karme Yosef', he: 'כרמי יוסף' },
  { en: 'Karme Katif', he: 'כרמי קטיף' },
  { en: 'Karmiel', he: 'כרמיאל' },
  { en: 'Karmiyya', he: 'כרמיה' },
  { en: 'Keramim', he: 'כרמים' },
  { en: 'Karmel', he: 'כרמית' },
  { en: 'Lahav', he: 'לב יתיר' },
  { en: 'Lavon', he: 'לבון' },
  { en: 'Lavi', he: 'לביא' },
  { en: 'Livnim', he: 'ליבנים' },
  { en: 'Lahav', he: 'להב' },
  { en: 'Lehavim', he: 'להבות הבשן' },
  { en: 'Lod', he: 'לוד' },
  { en: 'Luzit', he: 'לוזית' },
  { en: 'Lotem', he: 'לוטם' },
  { en: 'Lotan', he: 'לוטן' },
  { en: 'Liman', he: 'לימן' },
  { en: 'Lakhish', he: 'לכיש' },
  { en: 'Lappid', he: 'לפיד' },
  { en: 'Lappidot', he: 'לפידות' },
  { en: 'Laqye', he: 'לקיה' },
  { en: 'Maor', he: 'מאור' },
  { en: 'Mevo Betar', he: 'מבוא ביתר' },
  { en: 'Mevo Dotan', he: 'מבוא חמה' },
  { en: 'Mevo Horon', he: 'מבוא מודיעים' },
  { en: 'Mevoot Yam', he: 'מבועים' },
  { en: 'Mabbuim', he: 'מבטחים' },
  { en: 'Mivtahim', he: 'מבקיעים' },
  { en: 'Mavqiim', he: 'מבשרת ציון' },
  { en: 'Mughar', he: 'מג\'ד אל-כרום' },
  { en: 'Megadim', he: 'מג\'דל שמס' },
  { en: 'Migdal', he: 'מגדל' },
  { en: 'Migdal Oz', he: 'מגדל העמק' },
  { en: 'Migdalim', he: 'מגדים' },
  { en: 'Megiddo', he: 'מגידו' },
  { en: 'Maggal', he: 'מגל' },
  { en: 'Magen', he: 'מגן' },
  { en: 'Magshimim', he: 'מגשימים' },
  { en: 'Midrakh Oz', he: 'מדרך עוז' },
  { en: 'Meir Shefeya', he: 'מדרשת בן גוריון' },
  { en: 'Modiin Illit', he: 'מודיעין-מכבים-רעות' },
  { en: 'Moledet', he: 'מולדה' },
  { en: 'Moza Illit', he: 'מולדת' },
  { en: 'Muqeible', he: 'מוסמוס' },
  { en: 'Moran', he: 'מורן' },
  { en: 'Moreshet', he: 'מורשת' },
  { en: 'Moza', he: 'מוצא' },
  { en: 'Moza Illit', he: 'מוצא עילית' },
  { en: 'Muqibilla', he: 'מוקיבלה' },
  { en: 'Mazor', he: 'מזור' },
  { en: 'Mizra', he: 'מזכרת בתיה' },
  { en: 'Mazraa', he: 'מזרעה' },
  { en: 'Mehola', he: 'מחניים' },
  { en: 'Mahanayim', he: 'מחסיה' },
  { en: 'Metula', he: 'מטולה' },
  { en: 'Matta', he: 'מטע' },
  { en: 'Me Ammi', he: 'מי עמי' },
  { en: 'Metav', he: 'מיטב' },
  { en: 'Metal', he: 'מייסר' },
  { en: 'Meiser', he: 'מילצ\'ן' },
  { en: 'Mezar', he: 'מיצר' },
  { en: 'Merav', he: 'מירב' },
  { en: 'Meron', he: 'מירון' },
  { en: 'Meshar', he: 'מישר' },
  { en: 'Metar', he: 'מיתר' },
  { en: 'Mekhora', he: 'מכחול' },
  { en: 'Makchul', he: 'מכמורת' },
  { en: 'Mikhmannim', he: 'מכמנים' },
  { en: 'Melea', he: 'מלאה' },
  { en: 'Melilot', he: 'מלילות' },
  { en: 'Malkiyya', he: 'מלכיה' },
  { en: 'Menuha', he: 'מנוחה' },
  { en: 'Manof', he: 'מנוף' },
  { en: 'Manot', he: 'מנות' },
  { en: 'Menahemya', he: 'מנחמיה' },
  { en: 'Menara', he: 'מנרה' },
  { en: 'Manshiyyet Zabda', he: 'מנשייה זבדה' },
  { en: 'Massad', he: 'מסד' },
  { en: 'Massada', he: 'מסדה' },
  { en: 'Mesillot', he: 'מסילות' },
  { en: 'Mesillat Ziyyon', he: 'מסילת ציון' },
  { en: 'Maslul', he: 'מסלול' },
  { en: 'Masade', he: 'מסעדה' },
  { en: 'Mabarot', he: 'מעברות' },
  { en: 'Magalim', he: 'מעגלים' },
  { en: 'Maagan', he: 'מעגן' },
  { en: 'Maagan Mikhael', he: 'מעגן מיכאל' },
  { en: 'Maoz Hayyim', he: 'מעוז חיים' },
  { en: 'Maon', he: 'מעוז ציון' },
  { en: 'Meona', he: 'מעונה' },
  { en: 'Mayan Barukh', he: 'מעיין ברוך' },
  { en: 'Mayan Zevi', he: 'מעיין צבי' },
  { en: 'Mielya', he: 'מעיליא' },
  { en: 'Maale Efrayim', he: 'מעלה גלבוע' },
  { en: 'Maale Amos', he: 'מעלה גמלא' },
  { en: 'Maale Hahamisha', he: 'מעלה החמישה' },
  { en: 'Maale Levona', he: 'מעלה צביה' },
  { en: 'Maalot Tarshiha', he: 'מעלות תרשיחא' },
  { en: 'Mazuva', he: 'מצובה' },
  { en: 'Mazliah', he: 'מצליח' },
  { en: 'Mizpa', he: 'מצפה' },
  { en: 'Mizpe Aviv', he: 'מצפה אביב' },
  { en: 'Mitspe Ilan', he: 'מצפה אילן' },
  { en: 'Mizpe Ramon', he: 'מצפה רמון' },
  { en: 'Mezer', he: 'מצר' },
  { en: 'Maale Adummim', he: 'מעלה אדומים' },
  { en: 'Margaliyyot', he: 'מרגליות' },
  { en: 'Merom Golan', he: 'מרום גולן' },
  { en: 'Merhav Am', he: 'מרחב עם' },
  { en: 'Merkaz Shapira', he: 'מרכז שפירא' },
  { en: 'Mashabbe Sade', he: 'משאבי שדה' },
  { en: 'Misgav Dov', he: 'משגב דב' },
  { en: 'Misgav Am', he: 'משגב עם' },
  { en: 'Meshhed', he: 'משהד' },
  { en: 'Massuot', he: 'משואות יצחק' },
  { en: 'Mishmar Ayyalon', he: 'משמר איילון' },
  { en: 'Mishmar Dawid', he: 'משמר דוד' },
  { en: 'Mishmar Hayarden', he: 'משמר הירדן' },
  { en: 'Mishmar Hanegev', he: 'משמר הנגב' },
  { en: 'Mishmar Haemeq', he: 'משמר העמק' },
  { en: 'Mishmar Hashiva', he: 'משמר השבעה' },
  { en: 'Mishmar Hasharon', he: 'משמר השרון' },
  { en: 'Mishmarot', he: 'משמרות' },
  { en: 'Mishmeret', he: 'משמרת' },
  { en: 'Mashen', he: 'משען' },
  { en: 'Mattan', he: 'מתן' },
  { en: 'Mattat', he: 'מתת' },
  { en: 'Neot Golan', he: 'נאות גולן' },
  { en: 'Naura', he: 'נאות הכיכר' },
  { en: 'Neot Mordekhay', he: 'נאות מרדכי' },
  { en: 'Neot Smadar', he: 'נאות סמדר' },
  { en: 'Nevatim', he: 'נבטים' },
  { en: 'Negba', he: 'נגבה' },
  { en: 'Massuot Yizhaq', he: 'משואות יצחק' },
  { en: 'Mishmar Ayyalon', he: 'משמר איילון' },
  { en: 'Neot Hakikkar', he: 'נאות הכיכר' },
  { en: 'Nahariyya', he: 'נהריה' },
  { en: 'Nov', he: 'נוב' },
  { en: 'Nogah', he: 'נוגה' },
  { en: 'Nave', he: 'נוה אילן' },
  { en: 'Newe Avot', he: 'נוה אילן' },
  { en: 'Newe Ur', he: 'נוה אטי"ב' },
  { en: 'Newe Ativ', he: 'נוה איתן' },
  { en: 'Newe Ilan', he: 'נוה זוהר' },
  { en: 'Newe Etan', he: 'נוה זוהר' },
  { en: 'Newe Zohar', he: 'נוה זיו' },
  { en: 'Newe Ziv', he: 'נוה חריף' },
  { en: 'Newe Harif', he: 'נוה חריף' },
  { en: 'Newe Yam', he: 'נוה ים' },
  { en: 'Newe Yamin', he: 'נוה ירק' },
  { en: 'Newe Yaraq', he: 'נוה מבטח' },
  { en: 'Newe Mivtah', he: 'נוה עמיאל' },
  { en: 'Newe Daniel', he: 'נוה ניר' },
  { en: 'Newe Mikhael', he: 'נוה שלום' },
  { en: 'Noam', he: 'נוביט' },
  { en: 'Nof Ayyalon', he: 'נוף איילון' },
  { en: 'Nof Hagalil', he: 'נוף הגליל' },
  { en: 'Nofim', he: 'נופית' },
  { en: 'Nofit', he: 'נופך' },
  { en: 'Nofekh', he: 'נוקדים' },
  { en: 'Noqedim', he: 'נוקדים' },
  { en: 'Nordiyya', he: 'נורדיה' },
  { en: 'Nurit', he: 'נורית' },
  { en: 'Nehusha', he: 'נחושה' },
  { en: 'Nahal Oz', he: 'נחל עוז' },
  { en: 'Nahala', he: 'נחלה' },
  { en: 'Nahaliel', he: 'נחלים' },
  { en: 'Nehalim', he: 'נחלים' },
  { en: 'Naham', he: 'נחם' },
  { en: 'Nahef', he: 'נחף' },
  { en: 'Nahsholim', he: 'נחשולים' },
  { en: 'Nahshon', he: 'נחשון' },
  { en: 'Nahshonim', he: 'נחשונים' },
  { en: 'Netua', he: 'נטועה' },
  { en: 'Natur', he: 'נטור' },
  { en: 'Neta', he: 'נטע' },
  { en: 'Netaim', he: 'נטעים' },
  { en: 'Nataf', he: 'נטף' },
  { en: 'Nein', he: 'ניין' },
  { en: 'Nili', he: 'ניצן' },
  { en: 'Nizzan B', he: 'ניצן ב\'' },
  { en: 'Nizzana', he: 'ניצנה' },
  { en: 'Nizzane Sinay', he: 'ניצני סיני' },
  { en: 'Nizzane Oz', he: 'ניצני עוז' },
  { en: 'Nizzanim', he: 'ניצנים' },
  { en: 'Nir Eliyyahu', he: 'ניר אליהו' },
  { en: 'Nir Banim', he: 'ניר בנים' },
  { en: 'Nir Gallim', he: 'ניר גלים' },
  { en: 'Nir Hen', he: 'ניר דוד' },
  { en: 'Nir David', he: 'ניר ח"ן' },
  { en: 'Nir Yafe', he: 'ניר יפה' },
  { en: 'Nir Yizhaq', he: 'ניר יצחק' },
  { en: 'Nir Yisrael', he: 'ניר ישראל' },
  { en: 'Nir Moshe', he: 'ניר משה' },
  { en: 'Nir Oz', he: 'ניר עוז' },
  { en: 'Nir Am', he: 'ניר עם' },
  { en: 'Nir Ezyon', he: 'ניר עציון' },
  { en: 'Nir Aqiva', he: 'ניר עקיבא' },
  { en: 'Nir Zevi', he: 'ניר צבי' },
  { en: 'Nirim', he: 'נירים' },
  { en: 'Nirit', he: 'נירית' },
  { en: 'Nimrod', he: 'נמרוד' },
  { en: 'Nes Harim', he: 'נס הרים' },
  { en: 'Nes Ammim', he: 'נס עמים' },
  { en: 'Nes Ziyyona', he: 'נס ציונה' },
  { en: 'Neurim', he: 'נעורה' },
  { en: 'Naale', he: 'נעלן' },
  { en: 'Naama', he: 'נעמה' },
  { en: 'Naan', he: 'נעין' },
  { en: 'Naaran', he: 'נעררה' },
  { en: 'Nasasra', he: 'נצאצרה' },
  { en: 'Nazareth', he: 'נצרת' },
  { en: 'Nesher', he: 'נשר' },
  { en: 'Nezer Hazzani', he: 'נצר חזני' },
  { en: 'Nezer Sereni', he: 'נצר סרני' },
  { en: 'Netiv Hagedud', he: 'נתיב הל"ה' },
  { en: 'Netiv Halamedhe', he: 'נתיב העשרה' },
  { en: 'Netiv Hashayyara', he: 'נתיב השיירה' },
  { en: 'Netivot', he: 'נתיבות' },
  { en: 'Sawaid', he: 'סאג\' ור' },
  { en: 'Sassa', he: 'סאסא' },
  { en: 'Sabion', he: 'סביון' },
  { en: 'Sagula', he: 'סגולה' },
  { en: 'Sufa', he: 'סופה' },
  { en: 'Sakhnin', he: 'סכנין' },
  { en: 'Salim', he: 'סלים' },
  { en: 'Sallama', he: 'סלמה' },
  { en: 'Samar', he: 'סמר' },
  { en: 'Sansana', he: 'סנדלה' },
  { en: 'Saad', he: 'סעד' },
  { en: 'Sawa', he: 'סעווה' },
  { en: 'Saar', he: 'סער' },
  { en: 'Sappir', he: 'ספיר' },
  { en: 'Sitriyya', he: 'סרעיאה' },
  { en: 'Saharut', he: 'סתריה' },
  { en: 'Avdon', he: 'עבדה' },
  { en: 'Evron', he: 'עברון' },
  { en: 'Agur', he: 'עגור' },
  { en: 'Adi', he: 'עדי' },
  { en: 'Adanim', he: 'עדנים' },
  { en: 'Uza', he: 'עוזה' },
  { en: 'Uzeir', he: 'עוזיר' },
  { en: 'Olesh', he: 'עולש' },
  { en: 'Omer', he: 'עומר' },
  { en: 'Ofer', he: 'עופר' },
  { en: 'Ozem', he: 'עוצם' },
  { en: 'Uqbi', he: 'עוקבי' },
  { en: 'Uzuz', he: 'עזוז' },
  { en: 'Ezer', he: 'עזר' },
  { en: 'Azriel', he: 'עזריאל' },
  { en: 'Azarya', he: 'עזריה' },
  { en: 'Azriqam', he: 'עזריקם' },
  { en: 'Atawne', he: 'עיבלין' },
  { en: 'Ateret', he: 'עידן' },
  { en: 'Iddan', he: 'עיינות' },
  { en: 'Eilabun', he: 'עילבון' },
  { en: 'Ayanot', he: 'עין א-דיסה' },
  { en: 'Ilut', he: 'עין אל אסד' },
  { en: 'En Ayyala', he: 'עין בוקק' },
  { en: 'En Alasad', he: 'עין בוקק' },
  { en: 'En Gev', he: 'עין גב' },
  { en: 'En Gedi', he: 'עין גדי' },
  { en: 'En Dor', he: 'עין דור' },
  { en: 'En Habesor', he: 'עין הבשור' },
  { en: 'En Hod', he: 'עין הוד' },
  { en: 'En Hamifraz', he: 'עין המפרץ' },
  { en: 'En Hanaziv', he: 'עין הנציב' },
  { en: 'En Haemeq', he: 'עין העמק' },
  { en: 'En Hashofet', he: 'עין השופט' },
  { en: 'En Wered', he: 'עין ורד' },
  { en: 'En Ziwan', he: 'עין זיוון' },
  { en: 'En Hahoresh', he: 'עין חוד' },
  { en: 'En Hashelosha', he: 'עין השלושה' },
  { en: 'En Hazeva', he: 'עין הזבע' },
  { en: 'En Yahav', he: 'עין יהב' },
  { en: 'En Yaaqov', he: 'עין יעקב' },
  { en: 'En Karmel', he: 'עין כרמל' },
  { en: 'Ein Mahel', he: 'עין מאהל' },
  { en: 'Ein Naqquba', he: 'עין נקובא' },
  { en: 'En Iron', he: 'עין עירון' },
  { en: 'En Zurim', he: 'עין צורים' },
  { en: 'Ein Qiniyye', he: 'עין קנייא' },
  { en: 'Ein Rafa', he: 'עין ראפה' },
  { en: 'En Shemer', he: 'עין שמר' },
  { en: 'En Sarid', he: 'עין שריד' },
  { en: 'En Tamar', he: 'עין תמר' },
  { en: 'Enat', he: 'עינת' },
  { en: 'Ir Ovot', he: 'עיר אובות' },
  { en: 'Akko', he: 'עכו' },
  { en: 'Alumim', he: 'עלוט' },
  { en: 'Eli', he: 'עלי' },
  { en: 'Ale Zahav', he: 'עלומים' },
  { en: 'Alma', he: 'עלמה' },
  { en: 'Almon', he: 'עמוקה' },
  { en: 'Amuqqa', he: 'עמינדב' },
  { en: 'Ammihay', he: 'עמיעד' },
  { en: 'Amminadav', he: 'עמיעוז' },
  { en: 'Ammiad', he: 'עמיקם' },
  { en: 'Ammioz', he: 'עמיר' },
  { en: 'Ammiqam', he: 'עמקה' },
  { en: 'Amir', he: 'ענבר' },
  { en: 'Immanuel', he: 'עספיא' },
  { en: 'Amqa', he: 'עפולה' },
  { en: 'Enav', he: 'עצמון שגב' },
  { en: 'Isifya', he: 'עקדה' },
  { en: 'Afula', he: 'עפולה' },
  { en: 'Ofra', he: 'עף' },
  { en: 'Arrabe', he: 'עראבה' },
  { en: 'Aramsha', he: 'ערב א-נעים' },
  { en: 'Arab Al Naim', he: 'ערב אל מוריסאת' },
  { en: 'Arad', he: 'ערד' },
  { en: 'Arugot', he: 'ערוגות' },
  { en: 'Arara', he: 'ערערה' },
  { en: 'Asael', he: 'עשרת' },
  { en: 'Aseret', he: 'עתיר' },
  { en: 'Atlit', he: 'עתלית' },
  { en: 'Otniel', he: 'פארן' },
  { en: 'Paran', he: 'פדויים' },
  { en: 'Peduel', he: 'פדיה' },
  { en: 'Peduyim', he: 'פוריה - נווה עובד' },
  { en: 'Pedaya', he: 'פוריה כפר עבודה' },
  { en: 'Fureidis', he: 'פוריה עילית' },
  { en: 'Poriyya Illit', he: 'פוריידיס' },
  { en: 'Porat', he: 'פורת' },
  { en: 'Pattish', he: 'פטיש' },
  { en: 'Atsmon', he: 'פלך' },
  { en: 'Segev', he: 'פלמחים' },
  { en: 'Arara Banegev', he: 'פסוטה' },
  { en: 'Pesagot', he: 'פעמי תש"ז' },
  { en: 'Fassuta', he: 'פקיעין' },
  { en: 'Pezael', he: 'פקיעין החדשה' },
  { en: 'Pardesiyya', he: 'פקיעין מערבית' },
  { en: 'Paame Tashaz', he: 'פרדס חנה-כרכור' },
  { en: 'Peqiin', he: 'פרדסיה' },
  { en: 'Buqeia', he: 'פרוד' },
  { en: 'Peqiin Hadasha', he: 'פרזון' },
  { en: 'Pardes Hanna Karkur', he: 'פרי גן' },
  { en: 'Parod', he: 'פתח תקווה' },
  { en: 'Perazon', he: 'פתחיה' },
  { en: 'Peri Gan', he: 'צאלים' },
  { en: 'Petah Tiqwa', he: 'צבעון' },
  { en: 'Petahya', he: 'צובה' },
  { en: 'Zeelim', he: 'צוחר' },
  { en: 'Zviyya', he: 'צופית' },
  { en: 'Zivon', he: 'צופר' },
  { en: 'Zova', he: 'צוקי ים' },
  { en: 'Zohar', he: 'צוקים' },
  { en: 'Zofiyya', he: 'צור הדסה' },
  { en: 'Zufim', he: 'צור יצחק' },
  { en: 'Zofit', he: 'צור משה' },
  { en: 'Zofar', he: 'צור נתן' },
  { en: 'Zuqi Yam', he: 'צוריאל' },
  { en: 'Zuqim', he: 'צורית' },
  { en: 'Zur Hadassa', he: 'צורן' },
  { en: 'Zur Yizhaq', he: 'ציפורי' },
  { en: 'Zur Moshe', he: 'צלפון' },
  { en: 'Zur Natan', he: 'צפריה' },
  { en: 'Zuriel', he: 'צפרירים' },
  { en: 'Zurit', he: 'צפת' },
  { en: 'Zippori', he: 'צרופה' },
  { en: 'Zelafon', he: 'צרעה' },
  { en: 'Sandala', he: 'קבועה' },
  { en: 'Zafriyya', he: 'קבוצת יבנה' },
  { en: 'Zafririm', he: 'קבוצת כנרת' },
  { en: 'Zefat', he: 'קדימה' },
  { en: 'Zerufa', he: 'קדמה' },
  { en: 'Zora', he: 'קדמת צבי' },
  { en: 'Qabboa', he: 'קדרון' },
  { en: 'Qedumim', he: 'קדרים' },
  { en: 'Qevuzat Yavne', he: 'קוממיות' },
  { en: 'Qedma', he: 'קורנית' },
  { en: 'Qidmat Zevi', he: 'קטורה' },
  { en: 'Qedar', he: 'קיבוץ מרחביה' },
  { en: 'Qidron', he: 'קיסריה' },
  { en: 'Qaddarim', he: 'קלחים' },
  { en: 'Qawain', he: 'קלנסווה' },
  { en: 'Qomemiyyut', he: 'קלע אלון' },
  { en: 'Qoranit', he: 'קציר' },
  { en: 'Qetura', he: 'קצר א סיר' },
  { en: 'Qesaryya', he: 'קצרין' },
  { en: 'Qelahim', he: 'קריית אונו' },
  { en: 'Qalya', he: 'קריית ביאליק' },
  { en: 'Qalansawe', he: 'קריית גת' },
  { en: 'Qela', he: 'קריית טבעון' },
  { en: 'Qadimazoran', he: 'קריית טבעון' },
  { en: 'Qudeirat Assani', he: 'קריית ים' },
  { en: 'Qazir', he: 'קרית אתא' },
  { en: 'Qasr Asir', he: 'קרית ההגנה' },
  { en: 'Qazrin', he: 'קרית יערים' },
  { en: 'Qiryat Ono', he: 'קרית מלאכי' },
  { en: 'Qiryat Arba', he: 'קרית עקרון' },
  { en: 'Qiryat Atta', he: 'קרית שמונה' },
  { en: 'Qiryat Bialik', he: 'קשכר נבארי' },
  { en: 'Qiryat Gat', he: 'קשת' },
  { en: 'Qiryat Tivon', he: 'ראמה' },
  { en: 'Qiryat Yam', he: 'ראס אל-עין' },
  { en: 'Qiryat Yearim', he: 'ראס עלי' },
  { en: 'Qiryat Motzkin', he: 'ראש הנקרה' },
  { en: 'Qiryat Malakhi', he: 'ראש העין' },
  { en: 'Qiryat Netafim', he: 'ראש פינה' },
  { en: 'Qiryat Anavim', he: 'ראשון לציון' },
  { en: 'Qiryat Eqron', he: 'רבדים' },
  { en: 'Qiryat Shelomo', he: 'רביבים' },
  { en: 'Qiryat Shemona', he: 'רביד' },
  { en: 'Qarne Shomeron', he: 'רגבה' },
  { en: 'Qeshet Rame', he: 'רגבים' },
  { en: 'Ras Alein', he: 'רהט' },
  { en: 'Ras Ali', he: 'רווחה' },
  { en: 'Rosh Haayin', he: 'רוויה' },
  { en: 'Rosh Pinna', he: 'רוחמה' },
  { en: 'Rosh Zurim', he: 'רומאנה' },
  { en: 'Revava', he: 'רומת היב' },
  { en: 'Revadim', he: 'רח\'מה' },
  { en: 'Rishon Leziyyon', he: 'רחוב' },
  { en: 'Revivim', he: 'רחובות' },
  { en: 'Ravid', he: 'ריחאנייה' },
  { en: 'Regba', he: 'ריינה' },
  { en: 'Regavim', he: 'רינתיה' },
  { en: 'Rahat', he: 'רכסים' },
  { en: 'Rewaha', he: 'רם און' },
  { en: 'Rewaya', he: 'רמות' },
  { en: 'Ruah Midbar', he: 'רמות השבים' },
  { en: 'Ruhama', he: 'רמות מאיר' },
  { en: 'Rummane', he: 'רמות מנשה' },
  { en: 'Rumat Heib', he: 'רמות נפתלי' },
  { en: 'Roi', he: 'רמלה' },
  { en: 'Rotem', he: 'רמת ארבל' },
  { en: 'Rehov', he: 'רמת גן' },
  { en: 'Rehovot', he: 'רמת דוד' },
  { en: 'Rehelim', he: 'רמת הדסה' },
  { en: 'Reihaniyye', he: 'רמת הכובש' },
  { en: 'Rehan', he: 'רמת השופט' },
  { en: 'Reine', he: 'רמת השרון' },
  { en: 'Rimmonim', he: 'רמת טראמפ' },
  { en: 'Rinnatya', he: 'רמת יוחנן' },
  { en: 'Rekhasim', he: 'רמת ישי' },
  { en: 'Ramon', he: 'רמת מגשימים' },
  { en: 'Ramot', he: 'רמת צבי' },
  { en: 'Ramot Meir', he: 'רמת רזיאל' },
  { en: 'Ramla', he: 'רמת רחל' },
  { en: 'Ramat Gan', he: 'רנן' },
  { en: 'Ramot Hashavim', he: 'רעים' },
  { en: 'Ramot Menashe', he: 'רעננה' },
  { en: 'Ramot Naftali', he: 'רקפת' },
  { en: 'Ramat David', he: 'רשפון' },
  { en: 'Ramat Hakovesh', he: 'רשפים' },
  { en: 'President Trump Heights', he: 'רתמים' },
  { en: 'Ramat Hashofet', he: 'שאר ישוב' },
  { en: 'Ramat Hasharon', he: 'שבי דרום' },
  { en: 'Ramat Yohanan', he: 'שבי ציון' },
  { en: 'Ramat Yishay', he: 'שבלי - אום אל-גנם' },
  { en: 'Ramat Magshimim', he: 'שגב שלום' },
  { en: 'Ramat Zevi', he: 'שדה אילן' },
  { en: 'Ramat Rahel', he: 'שדה אליהו' },
  { en: 'Rannen', he: 'שדה אליעזר' },
  { en: 'Reim', he: 'שדה בוקר' },
  { en: 'Raannana', he: 'שדה דוד' },
  { en: 'Raqqefet', he: 'שדה ורבורג' },
  { en: 'Rishpon', he: 'שדה יואב' },
  { en: 'Reshafim', he: 'שדה יעקב' },
  { en: 'Retamim', he: 'שדה משה' },
  { en: 'Ramat Raziel', he: 'שדה נחום' },
  { en: 'Shear Yishuv', he: 'שדה נחמיה' },
  { en: 'Shave Darom', he: 'שדה ניצן' },
  { en: 'Shave Ziyyon', he: 'שדה עוזיהו' },
  { en: 'Shave Shomeron', he: 'שדה צבי' },
  { en: 'Shiblium Alghaman', he: 'שדות ים' },
  { en: 'Segev Shalom', he: 'שדות מיכה' },
  { en: 'Sede Ilan', he: 'שדי אברהם' },
  { en: 'Sede Boqer', he: 'שדי חמד' },
  { en: 'Sede David', he: 'שדי תרומות' },
  { en: 'Sede Eliyyahu', he: 'שדמה' },
  { en: 'Sede Eliezer', he: 'שדמות דבורה' },
  { en: 'Sede Warburg', he: 'שדרות' },
  { en: 'Sede Yoav', he: 'שואבה' },
  { en: 'Sede Yizhaq', he: 'שובה' },
  { en: 'Sede Moshe', he: 'שובל' },
  { en: 'Sede Nahum', he: 'שוהם' },
  { en: 'Sede Nizzan', he: 'שומרה' },
  { en: 'Sede Zevi', he: 'שומריה' },
  { en: 'Sedot Yam', he: 'שוקדה' },
  { en: 'Sedot Mikha', he: 'שורש' },
  { en: 'Sede Hemed', he: 'שורשים' },
  { en: 'Shedema', he: 'שוש' },
  { en: 'Sederot', he: 'שיבולים' },
  { en: 'Shoeva', he: 'שיבלי' },
  { en: 'Shuva', he: 'שיזף' },
  { en: 'Shoval', he: 'שיטים' },
  { en: 'Shoham', he: 'שייח דנון' },
  { en: 'Shomera', he: 'שילת' },
  { en: 'Shomeriyya', he: 'שכניה' },
  { en: 'Shoqeda', he: 'שלווה' },
  { en: 'Shoresh', he: 'שלוחות' },
  { en: 'Shorashim', he: 'שלומי' },
  { en: 'Shezor', he: 'שלומית' },
  { en: 'Shahar', he: 'שלפים' },
  { en: 'Sede Yaaqov', he: 'שמיר' },
  { en: 'Sede Nehemya', he: 'שמרת' },
  { en: 'Sede Uzziyyahu', he: 'שמשית' },
  { en: 'Sede Avraham', he: 'שני' },
  { en: 'Sede Terumot', he: 'שניר' },
  { en: 'Shadmot Devora', he: 'שעב' },
  { en: 'Shadmot Mehola', he: 'שעל' },
  { en: 'Shoshannat Haamaqim', he: 'שעלבים' },
  { en: 'Shaharut', he: 'שער אפרים' },
  { en: 'Shaharit', he: 'שער הגולן' },
  { en: 'Shibbolim', he: 'שער העמקים' },
  { en: 'Shezaf', he: 'שפיים' },
  { en: 'Shittim', he: 'שפיר' },
  { en: 'Shilo', he: 'שפר' },
  { en: 'Shilat', he: 'שפרעם' },
  { en: 'Shekhanya', he: 'שקף' },
  { en: 'Shalwa', he: 'שרונה' },
  { en: 'Sheluhot', he: 'שריגים (לי-און)' },
  { en: 'Shelomi', he: 'שריד' },
  { en: 'Shlomit', he: 'שרשרת' },
  { en: 'Shamir', he: 'שתולה' },
  { en: 'Shima', he: 'שתולים' },
  { en: 'Shamerat', he: 'תאשור' },
  { en: 'Shimshit', he: 'תדהר' },
  { en: 'Shani', he: 'תובל' },
  { en: 'Senir', he: 'תושייה' },
  { en: 'Shaab', he: 'תימורים' },
  { en: 'Shaal', he: 'תירוש' },
  { en: 'Shaalvim', he: 'תל אביב–יפו' },
  { en: 'Shefayim', he: 'תל יוסף' },
  { en: 'Shafir', he: 'תל יצחק' },
  { en: 'Sheikh Dannun', he: 'תל מונד' },
  { en: 'Shalva Bamidbar', he: 'תל עדשים' },
  { en: 'Shaar Efrayim', he: 'תל ערד' },
  { en: 'Shaar Hagolan', he: 'תל קציר' },
  { en: 'Shaar Haamaqim', he: 'תל שבע' },
  { en: 'Shaar Menashe', he: 'תל תאומים' },
  { en: 'Shaar Shomron', he: 'תל-אלמלח' },
  { en: 'Shefer', he: 'תלמי אליהו' },
  { en: 'Shefaram', he: 'תלמי אלעזר' },
  { en: 'Shaqed', he: 'תלמי ביל"ו' },
  { en: 'Sheqef', he: 'תלמי יוסף' },
  { en: 'Sharona', he: 'תלמי יחיאל' },
  { en: 'Sarid', he: 'תלמי יפה' },
  { en: 'Sharsheret', he: 'תלמים' },
  { en: 'Shetula', he: 'תמרת' },
  { en: 'Shetulim', he: 'תנובות' },
  { en: 'Teashur', he: 'תעוז' },
  { en: 'Tidhar', he: 'תפרח' },
  { en: 'Tuval', he: 'תקומה' },
  { en: 'Tomer', he: 'תראבין א-צאנע' },
  { en: 'Tushiyya', he: 'תרום' },
].sort((a, b) => a.en.localeCompare(b.en));

export interface IsraelCitiesAutocompleteProps {
  value: string;
  onChange: (value: string) => void;
  onSelect?: (city: string) => void;
  label?: string;
  placeholder?: string;
  error?: string;
  disabled?: boolean;
  className?: string;
  required?: boolean;
  id?: string;
  locale?: 'en' | 'he';
}

const IsraelCitiesAutocomplete = React.forwardRef<
  HTMLInputElement,
  IsraelCitiesAutocompleteProps
>(
  (
    {
      value,
      onChange,
      onSelect,
      label,
      placeholder,
      error,
      disabled = false,
      className,
      required = false,
      id: providedId,
      locale = 'en',
    },
    ref
  ) => {
    const [isOpen, setIsOpen] = React.useState(false);
    const [filteredCities, setFilteredCities] = React.useState<typeof ISRAEL_CITIES>([]);
    const [highlightedIndex, setHighlightedIndex] = React.useState(0);
    const generatedId = React.useId();
    const finalId = providedId || generatedId;
    const listRef = React.useRef<HTMLUListElement>(null);
    const finalPlaceholder = placeholder ?? (locale === 'he' ? 'חפש עיר...' : 'Search for a city...');

    // Filter logic: use .includes() for better UX (e.g., "Saba" finds "Kfar Saba")
    React.useEffect(() => {
      const searchTerm = value.trim().toLowerCase();
      if (searchTerm) {
        const filtered = ISRAEL_CITIES.filter((city) => {
          const enMatch = city.en.toLowerCase().includes(searchTerm);
          const heMatch = city.he.includes(searchTerm);
          return enMatch || heMatch;
        });
        setFilteredCities(filtered);
        setIsOpen(true);
        setHighlightedIndex(0);
      } else {
        setFilteredCities([]);
        setIsOpen(false);
      }
    }, [value]);

    const handleSelect = (cityValue: string) => {
      onChange(cityValue);
      setIsOpen(false);
      onSelect?.(cityValue);
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
      if (!isOpen) return;

      switch (e.key) {
        case 'ArrowDown':
          e.preventDefault();
          setHighlightedIndex((prev) =>
            prev < filteredCities.length - 1 ? prev + 1 : prev
          );
          break;
        case 'ArrowUp':
          e.preventDefault();
          setHighlightedIndex((prev) => (prev > 0 ? prev - 1 : 0));
          break;
        case 'Enter':
          e.preventDefault();
          if (filteredCities[highlightedIndex]) {
            const selection = locale === 'he' ? filteredCities[highlightedIndex].he : filteredCities[highlightedIndex].en;
            handleSelect(selection);
          }
          break;
        case 'Escape':
          setIsOpen(false);
          break;
      }
    };

    // Auto-scroll to highlighted item
    React.useEffect(() => {
      if (highlightedIndex >= 0 && listRef.current) {
        const item = listRef.current.children[highlightedIndex] as HTMLElement;
        item?.scrollIntoView({ block: 'nearest' });
      }
    }, [highlightedIndex]);

    return (
      <div className={cn('relative w-full', className)} dir={locale === 'he' ? 'rtl' : 'ltr'}>
        {label && (
          <label
            htmlFor={finalId}
            className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1.5"
          >
            {label}
            {required && <span className="text-red-500 ms-1">*</span>}
          </label>
        )}

        <Popover.Root open={isOpen} onOpenChange={setIsOpen}>
          <div className="relative">
            <div
              className={cn(
                'relative flex items-center h-10 w-full rounded-xl px-3 py-2 text-sm transition-all bord bg-input dark:bg-input-dark',
                'focus-within:border-brand-main ',
                disabled && 'opacity-50 cursor-not-allowed',
                error && 'border-red-500'
              )}
            >
              <Popover.Trigger asChild>
                <input
                  ref={ref}
                  id={finalId}
                  type="text"
                  value={value}
                  onChange={(e) => onChange(e.target.value)}
                  onKeyDown={handleKeyDown}
                  placeholder={finalPlaceholder}
                  disabled={disabled}
                  required={required}
                  autoComplete="off"
                  className="flex-1 bg-transparent outline-none text-slate-900 dark:text-slate-100 placeholder:text-slate-400 focus-visible:outline-none"
                />
              </Popover.Trigger>

              {value && (
                <button
                  type="button"
                  onClick={() => onChange('')}
                  className="p-1 hover:bg-gray-hover-bg dark:hover:bg-gray-hover-bg-dark rounded-full"
                >
                  <X className="h-3.5 w-3.5 text-gray dark:text-gray-dark" />
                </button>
              )}
            </div>

            <Popover.Content
              side="bottom"
              align="start"
              sideOffset={4}
              onOpenAutoFocus={(e) => e.preventDefault()}
              className="z-50 w-[var(--radix-popover-trigger-width)] overflow-hidden rounded-lg border border-border dark:border-border-dark bg-background dark:bg-background-dark shadow-xl"
            >
              <ul ref={listRef} className="max-h-60 overflow-y-auto p-1">
                {filteredCities.length > 0 ? (
                  filteredCities.map((city, index) => {
                    const displayName = locale === 'he' ? city.he : city.en;
                    const isSelected = value.toLowerCase() === displayName.toLowerCase();
                    
                    return (
                      <li key={`${city.en}-${index}`}>
                        <button
                          type="button"
                          onClick={() => handleSelect(displayName)}
                          className={cn(
                            'w-full px-3 py-1.5 my-0.5 text-sm rounded-md transition-colors text-start',
                            highlightedIndex === index
                              ? 'bg-brand-main/5 dark:bg-brand-dark/10 text-brand-main dark:text-brand-dark'
                              : 'text-gray dark:text-gray-dark hover:bg-gray-bg/50 dark:hover:bg-gray-bg-dark ',
                            isSelected && 'bg-blue-50 dark:bg-blue-900/20 font-medium'
                          )}
                        >
                          {displayName}
                        </button>
                      </li>
                    );
                  })
                ) : (
                  <li className="px-3 py-2 text-sm text-slate-500 dark:text-slate-400">
                    {locale === 'he' ? 'אין תוצאות' : 'No results'}
                  </li>
                )}
              </ul>
            </Popover.Content>
          </div>
        </Popover.Root>

        {error && (
          <p className="text-xs text-red-500 mt-1.5 px-1">{error}</p>
        )}
      </div>
    );
  }
);

IsraelCitiesAutocomplete.displayName = 'IsraelCitiesAutocomplete';

export { IsraelCitiesAutocomplete, ISRAEL_CITIES };