export const featureFlags = {
  xpSystem: process.env.NEXT_PUBLIC_ENABLE_XP_SYSTEM === 'true',
  awardPopups: process.env.NEXT_PUBLIC_ENABLE_AWARD_POPUPS === 'true',
  leaderboard: process.env.NEXT_PUBLIC_ENABLE_LEADERBOARD === 'true',
  personalRanking: process.env.NEXT_PUBLIC_ENABLE_PERSONAL_RANKING === 'true',
  seasonalLeaderboard: process.env.NEXT_PUBLIC_ENABLE_SEASONAL_LEADERBOARD === 'true',
  locationCheckins: process.env.NEXT_PUBLIC_ENABLE_LOCATION_CHECKINS === 'true',
  guideQuizzes: process.env.NEXT_PUBLIC_ENABLE_GUIDE_QUIZZES === 'true',
  eventWinnerClaims: process.env.NEXT_PUBLIC_ENABLE_EVENT_WINNER_CLAIMS === 'true',
  surveyRewards: process.env.NEXT_PUBLIC_ENABLE_SURVEY_REWARDS === 'true',
  reviewRewards: process.env.NEXT_PUBLIC_ENABLE_REVIEW_REWARDS === 'true',
  eventSignupRewards: process.env.NEXT_PUBLIC_ENABLE_EVENT_SIGNUP_REWARDS === 'true',
  kudos: process.env.NEXT_PUBLIC_ENABLE_KUDOS === 'true',
  streaks: process.env.NEXT_PUBLIC_ENABLE_STREAKS === 'true',
  crews: process.env.NEXT_PUBLIC_ENABLE_CREWS === 'true',
  crewLeaderboard: process.env.NEXT_PUBLIC_ENABLE_CREW_LEADERBOARD === 'true',
  explorerMap: process.env.NEXT_PUBLIC_ENABLE_EXPLORER_MAP === 'true',
  skateparkKing: process.env.NEXT_PUBLIC_ENABLE_SKATEPARK_KING === 'true',
  pioneerBadge: process.env.NEXT_PUBLIC_ENABLE_PIONEER_BADGE === 'true',
  weeklyChallenges: process.env.NEXT_PUBLIC_ENABLE_WEEKLY_CHALLENGES === 'true',
  xpMultiplier: process.env.NEXT_PUBLIC_ENABLE_XP_MULTIPLIER === 'true',
  adminRanking: process.env.NEXT_PUBLIC_ENABLE_ADMIN_RANKING === 'true',
} as const;

export const serverFlags = {
  xpSkatepark: Number(process.env.XP_SKATEPARK_CHECKIN ?? 50),
  xpQuizPassed: Number(process.env.XP_GUIDE_QUIZ_PASSED ?? 100),
  xpEventSignup: Number(process.env.XP_EVENT_SIGNUP ?? 20),
  xpEventWinner1st: Number(process.env.XP_EVENT_WINNER_1ST ?? 500),
  xpEventWinner2nd: Number(process.env.XP_EVENT_WINNER_2ND ?? 300),
  xpEventWinner3rd: Number(process.env.XP_EVENT_WINNER_3RD ?? 150),
  xpSurveyCompleted: Number(process.env.XP_SURVEY_COMPLETED ?? 75),
  xpReviewWritten: Number(process.env.XP_REVIEW_WRITTEN ?? 40),
  xpKudosReceived: Number(process.env.XP_KUDOS_RECEIVED ?? 5),
  xpKudosGiven: Number(process.env.XP_KUDOS_GIVEN ?? 2),
  xpWeeklyChallenge: Number(process.env.XP_WEEKLY_CHALLENGE_COMPLETED ?? 80),
  xpStreakWeeklyBonus: Number(process.env.XP_STREAK_WEEKLY_BONUS ?? 50),
  xpStreakMonthlyBonus: Number(process.env.XP_STREAK_MONTHLY_BONUS ?? 200),
  xpPioneerBonus: Number(process.env.XP_PIONEER_FIRST_CHECKIN ?? 100),
  xpCrewContribution: Number(process.env.XP_CREW_CONTRIBUTION_BONUS ?? 10),
  /** Min check-in hours in a week to count that week for the streak (default 4). */
  streakWeeklyMinHours: Number(process.env.STREAK_WEEKLY_MIN_HOURS ?? 4),
  /** Min check-in hours in a month to count that month for the streak (default 16). */
  streakMonthlyMinHours: Number(process.env.STREAK_MONTHLY_MIN_HOURS ?? 16),
} as const;

